import { ExerciseItem, RecipeItem } from '../types';

export const EXERCISES_CATALOG: ExerciseItem[] = [
  // 1. MANCUERNAS / PESAS LIBRES
  {
    id: 'ex_db_squat',
    name: 'Sentadilla Goblet con Mancuerna',
    category: 'mancuernas',
    targetMuscle: 'Cuádriceps y Glúteos',
    suggestedSets: 3,
    suggestedRepsOrSeconds: '10 - 12 reps',
    restSeconds: 60,
    description: 'Sostén una mancuerna pegada al pecho con ambas manos. Desciende como si fueras a sentarte en una silla sin despegar los talones.',
    tips: ['Mantén el pecho erguido', 'Rodillas apuntando en la misma dirección que la punta de tus pies'],
    requiresEquipment: '1 mancuerna (o botella rellena)',
    difficulty: 'principiante',
  },
  {
    id: 'ex_db_row',
    name: 'Remo a una Mano apoyado en Silla',
    category: 'mancuernas',
    targetMuscle: 'Espalda y Dorsales',
    suggestedSets: 3,
    suggestedRepsOrSeconds: '12 reps por lado',
    restSeconds: 45,
    description: 'Apoya una mano y rodilla en una silla resistente. Con el otro brazo jala la mancuerna hacia tu cadera apretando la espalda.',
    tips: ['No gires el torso', 'Conduce el movimiento con el codo'],
    requiresEquipment: '1 mancuerna + 1 silla',
    difficulty: 'principiante',
  },
  {
    id: 'ex_db_press',
    name: 'Press de Hombros Sentado',
    category: 'mancuernas',
    targetMuscle: 'Deltoides (Hombros)',
    suggestedSets: 3,
    suggestedRepsOrSeconds: '10 - 12 reps',
    restSeconds: 60,
    description: 'Sentado con la espalda recta, eleva dos mancuernas desde la altura de las orejas hacia el techo de forma controlada.',
    tips: ['No arquees la espalda baja', 'Baja lento en 2 a 3 segundos'],
    requiresEquipment: '2 mancuernas + silla',
    difficulty: 'intermedio',
  },

  // 2. LIGAS DE RESISTENCIA (TUBULARES / CON ASAS)
  {
    id: 'ex_band_row',
    name: 'Remo Sentado con Liga en Pies',
    category: 'ligas',
    targetMuscle: 'Espalda Media y Bíceps',
    suggestedSets: 3,
    suggestedRepsOrSeconds: '12 - 15 reps',
    restSeconds: 45,
    description: 'Siéntate en el suelo con piernas estiradas. Pasa la liga por la planta de los pies y jala las asas hacia tu ombligo retrayendo omóplatos.',
    tips: ['Pecho hacia afuera al jalar', 'Mantén la tensión en todo el recorrido'],
    requiresEquipment: 'Liga con asas',
    difficulty: 'principiante',
  },
  {
    id: 'ex_band_lateral',
    name: 'Elevaciones Laterales con Liga Pisada',
    category: 'ligas',
    targetMuscle: 'Hombro Lateral',
    suggestedSets: 3,
    suggestedRepsOrSeconds: '12 - 15 reps',
    restSeconds: 45,
    description: 'Pisa la liga con uno o ambos pies y eleva los brazos lateralmente hasta la altura de los hombros con codos suaves.',
    tips: ['No levantes por encima de los hombros', 'Movimiento controlado al bajar'],
    requiresEquipment: 'Liga elástica',
    difficulty: 'intermedio',
  },
  {
    id: 'ex_band_biceps',
    name: 'Curl de Bíceps con Liga',
    category: 'ligas',
    targetMuscle: 'Bíceps',
    suggestedSets: 3,
    suggestedRepsOrSeconds: '12 - 14 reps',
    restSeconds: 45,
    description: 'Pisa la liga al centro, mantén codos pegados a las costillas y flexiona antebrazos apretando al final.',
    tips: ['No balancees el cuerpo', 'Pausa 1 segundo arriba'],
    requiresEquipment: 'Liga elástica',
    difficulty: 'principiante',
  },

  // 3. BANDAS DE RESISTENCIA PARA PIERNAS (BOOTY / MINI-BANDS)
  {
    id: 'ex_mini_glute_bridge',
    name: 'Puente de Glúteos con Banda en Rodillas',
    category: 'bandas_pierna',
    targetMuscle: 'Glúteos y Femorales',
    suggestedSets: 3,
    suggestedRepsOrSeconds: '15 reps',
    restSeconds: 45,
    description: 'Acostado boca arriba con rodillas dobladas y la banda justo arriba de las rodillas. Empuja con los talones y abre rodillas contra la banda.',
    tips: ['Aprieta glúteos 2 segundos arriba', 'No hiperextiendas la columna'],
    requiresEquipment: 'Banda elástica corta de pierna',
    difficulty: 'principiante',
  },
  {
    id: 'ex_mini_clamshell',
    name: 'Abducciones Clamshell (Ostra)',
    category: 'bandas_pierna',
    targetMuscle: 'Glúteo Medio y Cadera',
    suggestedSets: 3,
    suggestedRepsOrSeconds: '12 - 15 reps por pierna',
    restSeconds: 30,
    description: 'Acostado de lado con rodillas a 90 grados y pies juntos. Abre la rodilla superior como una concha venciendo la resistencia de la banda.',
    tips: ['Mantén la pelvis estable sin rotar hacia atrás'],
    requiresEquipment: 'Banda elástica corta de pierna',
    difficulty: 'principiante',
  },
  {
    id: 'ex_mini_monster_walk',
    name: 'Pasos Laterales en Sentadilla (Monster Walk)',
    category: 'bandas_pierna',
    targetMuscle: 'Abductores y Glúteos',
    suggestedSets: 3,
    suggestedRepsOrSeconds: '10 pasos a cada lado',
    restSeconds: 60,
    description: 'Coloca la banda arriba de los tobillos o rodillas. Adopta una posición de media sentadilla y da pasos laterales controlados.',
    tips: ['Mantén siempre tensión en la banda, nunca juntes los pies del todo'],
    requiresEquipment: 'Banda elástica corta de pierna',
    difficulty: 'intermedio',
  },

  // 4. CARDIO EN CASA (SIN MÁQUINAS NI IMPACTO PELIGROSO)
  {
    id: 'ex_cardio_step_jack',
    name: 'Step Jacks (Jumping Jacks sin Salto)',
    category: 'cardio',
    targetMuscle: 'Cuerpo Completo / Cardiovascular',
    suggestedSets: 3,
    suggestedRepsOrSeconds: '45 segundos',
    restSeconds: 30,
    description: 'Abre un pie al lateral coordinando con brazos arriba, regresa al centro y abre el otro. Cero impacto para rodillas y tobillos.',
    tips: ['Mantén un ritmo constante y respiración fluida'],
    requiresEquipment: 'Ninguno',
    difficulty: 'principiante',
  },
  {
    id: 'ex_cardio_shadow_box',
    name: 'Boxeo al Aire con Giros Suaves de Torso',
    category: 'cardio',
    targetMuscle: 'Cardio y Core',
    suggestedSets: 3,
    suggestedRepsOrSeconds: '45 segundos',
    restSeconds: 30,
    description: 'Lanza golpes rectos alternados al aire contrayendo el abdomen en cada impacto virtual.',
    tips: ['No bloquees los codos de golpe', 'Mueve ligeramente los pies'],
    requiresEquipment: 'Ninguno',
    difficulty: 'principiante',
  },

  // 5. PESO CORPORAL
  {
    id: 'ex_body_incline_pushup',
    name: 'Flexiones Inclinadas en Pared o Sofá',
    category: 'peso_corporal',
    targetMuscle: 'Pectoral, Tríceps y Core',
    suggestedSets: 3,
    suggestedRepsOrSeconds: '10 - 12 reps',
    restSeconds: 45,
    description: 'Apoya las manos en la pared o borde del sofá manteniendo el cuerpo recto como una tabla. Flexiona brazos hasta acercar el pecho.',
    tips: ['Cuerpo alineado como una plancha', 'No dejes caer la cadera'],
    requiresEquipment: 'Pared o sofá',
    difficulty: 'principiante',
  },
];

export const RECIPES_CATALOG: RecipeItem[] = [
  // 1. DESAYUNOS
  {
    id: 'rec_des_1',
    title: 'Huevos a la Mexicana con Tortillas de Maíz',
    mealType: 'breakfast',
    prepTimeMinutes: 10,
    isBudgetFriendly: true,
    ingredients: [
      '2 huevos enteros',
      '1 tomate picado',
      '1/4 de cebolla picada',
      '1 cucharadita de aceite común',
      '2 tortillas de maíz',
    ],
    instructions: [
      'Pica el tomate y la cebolla finamente.',
      'Sofríelos en sartén con una cucharadita de aceite durante 2 minutos.',
      'Bate los huevos, agrégalos al sartén con sal al gusto y revuelve.',
      'Acompaña con las 2 tortillas calientes y café o té sin azúcar.',
    ],
    approxCalories: 320,
    approxProteinGrams: 16,
  },
  {
    id: 'rec_des_2',
    title: 'Avena Cocida con Manzana, Canela y Huevo Duro',
    mealType: 'breakfast',
    prepTimeMinutes: 8,
    isBudgetFriendly: true,
    ingredients: [
      '4 cucharadas soperas de hojuelas de avena',
      '1 taza de agua o leche semidescremada',
      '1/2 manzana picada en cubitos',
      '1 pizca de canela en polvo',
      '1 huevo duro aparte',
    ],
    instructions: [
      'Hierve el agua o leche y agrega la avena.',
      'Cocina a fuego medio por 3-4 minutos moviendo constantemente.',
      'Sirve caliente, agrega la manzana en cubos y espolvorea canela.',
      'Come el huevo duro para asegurar tu aporte de proteína y saciedad.',
    ],
    approxCalories: 310,
    approxProteinGrams: 15,
  },
  {
    id: 'rec_des_3',
    title: 'Omelette Esponjoso de Espinacas y Queso Panela',
    mealType: 'breakfast',
    prepTimeMinutes: 10,
    isBudgetFriendly: true,
    ingredients: [
      '2 huevos enteros',
      '1 taza de espinacas frescas picadas',
      '40g de queso panela en cubos',
      '1 cucharadita de aceite',
      '1 tortilla de maíz o rebanada de pan integral',
    ],
    instructions: [
      'Bate los 2 huevos con sal y pimienta al gusto.',
      'Calienta el sartén con la cucharadita de aceite y vierte los huevos con la espinaca picada.',
      'Coloca el queso panela en el centro y dobla en forma de media luna.',
      'Cocina 1 minuto más y sirve con la tortilla de maíz caliente.',
    ],
    approxCalories: 310,
    approxProteinGrams: 18,
  },
  {
    id: 'rec_des_4',
    title: 'Pan Tostado con Dip de Huevo Cocido y Espinaca',
    mealType: 'breakfast',
    prepTimeMinutes: 8,
    isBudgetFriendly: true,
    ingredients: [
      '2 rebanadas de pan de molde integral',
      '2 huevos cocidos',
      '1 puñado de espinacas finamente picadas',
      '1/4 de aguacate',
      '1 cucharada de yogur natural sin azúcar',
    ],
    instructions: [
      'Tuesta las 2 rebanadas de pan integral hasta que estén crujientes.',
      'En un tazón, machaca los huevos cocidos con el aguacate, la espinaca y el yogur con sal y pimienta.',
      'Unta la mezcla generosamente sobre las rebanadas de pan tostado.',
    ],
    approxCalories: 290,
    approxProteinGrams: 15,
  },
  {
    id: 'rec_des_5',
    title: 'Sope Casero de Avena con Frijolitos y Huevo Revuelto',
    mealType: 'breakfast',
    prepTimeMinutes: 15,
    isBudgetFriendly: true,
    ingredients: [
      '4 cucharadas de avena molida (harina de avena)',
      '3-4 cucharadas de agua tibia',
      '2 cucharadas de frijoles molidos sin manteca',
      '1 huevo revuelto',
      'Salsa de tomate casera y 20g de queso fresco',
    ],
    instructions: [
      'Mezcla la avena molida con agua tibia y pizca de sal hasta formar una masa suave.',
      'Forma un sope con las manos y dóralo en comal por ambos lados hasta que esté cocido.',
      'Unta los frijoles calientes, agrega el huevo revuelto encima y corona con queso fresco y salsa.',
    ],
    approxCalories: 330,
    approxProteinGrams: 16,
  },
  {
    id: 'rec_des_6',
    title: 'Chilaquiles Ligeros al Comal con Huevo Estrellado',
    mealType: 'breakfast',
    prepTimeMinutes: 12,
    isBudgetFriendly: true,
    ingredients: [
      '2 tortillas de maíz cortadas en triángulos',
      '1/2 taza de salsa verde o roja hervida casera',
      '1 huevo estrellado a la plancha',
      '30g de queso fresco desmoronado',
      'Cebolla picada y cilantro al gusto',
    ],
    instructions: [
      'Dora los triángulos de tortilla en comal sin aceite hasta que queden como totopos crujientes.',
      'Calienta la salsa en una ollita y baña los totopos en el plato.',
      'Coloca el huevo estrellado encima y decora con queso fresco, cebolla y cilantro.',
    ],
    approxCalories: 320,
    approxProteinGrams: 15,
  },
  {
    id: 'rec_des_7',
    title: 'Pancitos Individuales de Avena Express al Microondas',
    mealType: 'breakfast',
    prepTimeMinutes: 6,
    isBudgetFriendly: true,
    ingredients: [
      '4 cucharadas de avena molida',
      '1 huevo entero',
      '1 cucharada de yogur natural sin azúcar',
      '1/4 cucharadita de polvo para hornear',
      'Canela en polvo al gusto',
    ],
    instructions: [
      'Mezcla todos los ingredientes en una taza o molde pequeño apto para microondas.',
      'Cocina en microondas por 1.5 a 2 minutos hasta que esponje.',
      'Desmolda, rebana a la mitad y acompaña con café o té caliente sin azúcar.',
    ],
    approxCalories: 280,
    approxProteinGrams: 14,
  },
  {
    id: 'rec_des_8',
    title: 'Huevos Rancheros Ligeros con Tostadas Horneadas',
    mealType: 'breakfast',
    prepTimeMinutes: 10,
    isBudgetFriendly: true,
    ingredients: [
      '2 huevos a la plancha',
      '2 tostadas de maíz horneadas sin grasa',
      '1/2 taza de salsa ranchera de tomate y chile asado',
      '2 cucharadas de frijoles de la olla enteros',
    ],
    instructions: [
      'Coloca las 2 tostadas horneadas con los frijoles machacados ligeramente.',
      'Monta un huevo a la plancha sobre cada tostada.',
      'Baña con la salsa ranchera caliente.',
    ],
    approxCalories: 315,
    approxProteinGrams: 16,
  },

  // 2. COMIDAS / ALMUERZOS
  {
    id: 'rec_com_1',
    title: 'Pechuga a la Plancha con Arroz y Ensalada Fresca',
    mealType: 'lunch',
    prepTimeMinutes: 15,
    isBudgetFriendly: true,
    ingredients: [
      '130g de pechuga de pollo',
      '1/2 taza de arroz cocido',
      '1 taza de lechuga picada con pepino y limón',
      '1 cucharadita de aceite para dorar',
    ],
    instructions: [
      'Sazona el pollo con ajo, sal, pimienta y limón.',
      'Dora en sartén caliente 3-4 minutos por lado hasta que esté bien cocido.',
      'Sirve con el arroz al lado y la ensalada fresca aderezada con limón y sal.',
    ],
    approxCalories: 410,
    approxProteinGrams: 34,
  },
  {
    id: 'rec_com_2',
    title: 'Atún en Lata a la Mexicana con Papita Cocida',
    mealType: 'lunch',
    prepTimeMinutes: 10,
    isBudgetFriendly: true,
    ingredients: [
      '1 lata de atún en agua escurrido',
      '1 tomate picado, cilantro y cebolla',
      '1 papa mediana cocida',
      'Gotas de limón y sal',
    ],
    instructions: [
      'Cuece la papa en agua con sal o microondas por 5 minutos hasta que esté suave.',
      'Mezcla el atún escurrido con el tomate, cebolla, cilantro y limón.',
      'Pica la papa y combínala con el atún fresco.',
    ],
    approxCalories: 330,
    approxProteinGrams: 28,
  },
  {
    id: 'rec_com_3',
    title: 'Calabacitas a la Bolognesa Casera con Carne Magra',
    mealType: 'lunch',
    prepTimeMinutes: 15,
    isBudgetFriendly: true,
    ingredients: [
      '120g de carne molida magra de res o pollo',
      '2 calabacitas medianas en cubos',
      '2 jitomates licuados con ajo, cebolla y orégano',
      '1 cucharadita de aceite común',
    ],
    instructions: [
      'Sofríe la carne molida en sartén con la cucharadita de aceite hasta que cambie de color.',
      'Agrega las calabacitas picadas y vierte el puré de jitomate natural con sal y orégano.',
      'Tapa y cocina a fuego medio por 8 minutos hasta que las calabacitas estén tiernas y jugosas.',
    ],
    approxCalories: 380,
    approxProteinGrams: 32,
  },
  {
    id: 'rec_com_4',
    title: 'Atún en Salsa Cremosa de Chipotle con Tostadas y Aguacate',
    mealType: 'lunch',
    prepTimeMinutes: 10,
    isBudgetFriendly: true,
    ingredients: [
      '1 lata de atún en agua escurrida',
      '1 jitomate licuado con 1/2 chipotle y 1 cda de yogur natural',
      '1/4 de cebolla en plumitas',
      '2 tostadas de maíz horneadas',
      '1/4 de aguacate y lechuga picada',
    ],
    instructions: [
      'Acitrona la cebolla en sartén con gotitas de agua o aceite.',
      'Agrega el atún y vierte la salsa licuada de jitomate con chipotle y yogur.',
      'Cocina por 3 minutos hasta que espese. Sirve sobre las tostadas con lechuga y rebanadas de aguacate.',
    ],
    approxCalories: 340,
    approxProteinGrams: 28,
  },
  {
    id: 'rec_com_5',
    title: 'Tostadas de Tinga de Pollo Ligera',
    mealType: 'lunch',
    prepTimeMinutes: 15,
    isBudgetFriendly: true,
    ingredients: [
      '120g de pechuga de pollo cocida y deshebrada',
      '2 jitomates y 1/2 chile chipotle licuados',
      '1/4 de cebolla rebanada',
      '2 tostadas de maíz horneadas',
      'Lechuga picada y 30g de queso panela desmoronado',
    ],
    instructions: [
      'Sofríe la cebolla en sartén, agrega la salsa de jitomate con chipotle y sazona con orégano y sal.',
      'Incorpora el pollo deshebrado y deja hervir por 5 minutos.',
      'Sirve sobre las tostadas horneadas con lechuga fresca y queso panela.',
    ],
    approxCalories: 390,
    approxProteinGrams: 34,
  },
  {
    id: 'rec_com_6',
    title: 'Pescadillas / Tacos de Atún al Comal con Ensalada de Col',
    mealType: 'lunch',
    prepTimeMinutes: 12,
    isBudgetFriendly: true,
    ingredients: [
      '1 lata de atún guisado a la mexicana (jitomate, cebolla, cilantro)',
      '2 tortillas de maíz calientes',
      '1 taza de col rallada con zanahoria y limón',
    ],
    instructions: [
      'Rellena las tortillas con el atún guisado y dobla en forma de quesadilla/taco.',
      'Dora en comal caliente a fuego medio-bajo sin aceite hasta que queden crujientes y doraditas.',
      'Acompaña con la ensalada de col fresca aderezada con limón y sal.',
    ],
    approxCalories: 360,
    approxProteinGrams: 30,
  },
  {
    id: 'rec_com_7',
    title: 'Cochinita Pibil Ligera con Frijoles de la Olla y Ensalada',
    mealType: 'lunch',
    prepTimeMinutes: 15,
    isBudgetFriendly: true,
    ingredients: [
      '120g de carne magra de cerdo o pechuga cocida en achiote y naranja',
      '1/2 taza de frijoles de la olla enteros',
      'Cebolla morada curtida con limón y orégano',
      '1 taza de ensalada verde fresca',
    ],
    instructions: [
      'Deshebra la carne sazonada en achiote con toque de orégano y naranja agria.',
      'Sirve con 1/2 taza de frijoles de la olla calientes y la ensalada verde.',
      'Corona con cebollita morada curtida.',
    ],
    approxCalories: 400,
    approxProteinGrams: 33,
  },
  {
    id: 'rec_com_8',
    title: 'Fajitas de Pollo con Pimientos, Calabacita y Tortillas',
    mealType: 'lunch',
    prepTimeMinutes: 15,
    isBudgetFriendly: true,
    ingredients: [
      '130g de pechuga de pollo en tiras',
      '1/2 pimiento y 1 calabacita en julianas',
      '1/4 de cebolla',
      '2 tortillas de maíz',
      '1 cucharadita de aceite para saltear',
    ],
    instructions: [
      'Saltea las fajitas de pollo con la cebolla, el pimiento y la calabacita con ajo en polvo y sal.',
      'Cocina tapado por 6 minutos hasta que los vegetales estén al dente y el pollo dorado.',
      'Arma tus taquitos con las 2 tortillas calientes.',
    ],
    approxCalories: 370,
    approxProteinGrams: 33,
  },

  // 3. CENAS
  {
    id: 'rec_cen_1',
    title: 'Quesadillas Ligeras de Maíz con Champiñones y Panela',
    mealType: 'dinner',
    prepTimeMinutes: 8,
    isBudgetFriendly: true,
    ingredients: [
      '2 tortillas de maíz',
      '50g de queso panela o queso fresco desmoronado',
      '1/2 taza de champiñones picados',
    ],
    instructions: [
      'Dora los champiñones en sartén caliente sin aceite por 2 minutos con pizca de sal.',
      'Coloca el queso y los champiñones dentro de las tortillas.',
      'Calienta en el comal hasta que el queso se suavice.',
    ],
    approxCalories: 260,
    approxProteinGrams: 14,
  },
  {
    id: 'rec_cen_2',
    title: 'Sándwich Clásico Casero de Jamón de Pavo y Queso Panela',
    mealType: 'dinner',
    prepTimeMinutes: 5,
    isBudgetFriendly: true,
    ingredients: [
      '2 rebanadas de pan de molde común o integral',
      '2 rebanadas de jamón de pavo',
      '1 rebanada de queso panela',
      'Hojas de lechuga, rodajas de jitomate y mostaza al gusto',
    ],
    instructions: [
      'Unta una capa fina de mostaza en el pan.',
      'Arma el sándwich con el jamón, queso, lechuga y jitomate.',
      'Tuesta ligeramente en sartén si te gusta crujiente.',
    ],
    approxCalories: 270,
    approxProteinGrams: 16,
  },
  {
    id: 'rec_cen_3',
    title: 'Crepa Ligera de Avena con Yogur Natural y Fresas',
    mealType: 'dinner',
    prepTimeMinutes: 10,
    isBudgetFriendly: true,
    ingredients: [
      '3 cucharadas de avena molida licuada con 1 huevo y 3 cdas de agua',
      '3 cucharadas de yogur natural sin azúcar',
      '1/2 taza de fresas rebanadas',
      'Canela en polvo al gusto',
    ],
    instructions: [
      'Vierte la mezcla líquida en sartén antiadherente caliente para formar una crepa delgada.',
      'Cocina 2 minutos por lado a fuego medio.',
      'Rellena con el yogur natural, las fresas frescas y espolvorea canela.',
    ],
    approxCalories: 260,
    approxProteinGrams: 14,
  },
  {
    id: 'rec_cen_4',
    title: 'Mug Cake / Panqué Express de Plátano y Avena',
    mealType: 'dinner',
    prepTimeMinutes: 5,
    isBudgetFriendly: true,
    ingredients: [
      '1/2 plátano maduro machacado',
      '1 huevo entero',
      '3 cucharadas de avena molida',
      '1/4 cucharadita de polvo para hornear',
      'Canela en polvo',
    ],
    instructions: [
      'Machaca el plátano en una taza y bate con el huevo, la avena molida, polvo de hornear y canela.',
      'Lleva al microondas por 1.5 a 2 minutos hasta que esté firme y esponjoso.',
      'Disfruta tibio como una cena ligera y reconfortante.',
    ],
    approxCalories: 270,
    approxProteinGrams: 12,
  },
  {
    id: 'rec_cen_5',
    title: 'Tacos Ligeros de Champiñones al Ajillo con Queso Panela',
    mealType: 'dinner',
    prepTimeMinutes: 8,
    isBudgetFriendly: true,
    ingredients: [
      '2 tortillas de maíz',
      '1 taza de champiñones rebanados',
      '1 diente de ajo picado',
      '40g de queso panela en tiras',
    ],
    instructions: [
      'Saltea los champiñones con el ajo picado y una pizca de sal en sartén sin grasa.',
      'Calienta las tortillas en comal, agrega el queso panela y los champiñones salteados.',
    ],
    approxCalories: 250,
    approxProteinGrams: 13,
  },
  {
    id: 'rec_cen_6',
    title: 'Sopa Reconfortante de Verduras con Pollo Deshebrado',
    mealType: 'dinner',
    prepTimeMinutes: 10,
    isBudgetFriendly: true,
    ingredients: [
      '80g de pechuga de pollo deshebrada',
      '1 taza de caldo claro de verduras con calabacita y chayote',
      '1/4 de aguacate picado',
      'Gotas de limón y cilantro',
    ],
    instructions: [
      'Calienta el caldo con las verduras picadas y el pollo deshebrado.',
      'Sirve caliente en un plato hondo con el aguacate picado y jugo de limón.',
    ],
    approxCalories: 240,
    approxProteinGrams: 22,
  },
  {
    id: 'rec_cen_7',
    title: 'Tostadas Ligeras de Requesón con Ensalada de Nopales',
    mealType: 'dinner',
    prepTimeMinutes: 7,
    isBudgetFriendly: true,
    ingredients: [
      '2 tostadas de maíz horneadas',
      '60g de requesón o queso fresco',
      '1 taza de nopales cocidos o asados con jitomate, cebolla y orégano',
    ],
    instructions: [
      'Unta el requesón sobre las tostadas horneadas.',
      'Corona con la ensalada fresca de nopales sazonada con limón y orégano.',
    ],
    approxCalories: 230,
    approxProteinGrams: 15,
  },
  {
    id: 'rec_cen_8',
    title: 'Ensalada Fresca de Atún con Huevo Cocido y Limón',
    mealType: 'dinner',
    prepTimeMinutes: 6,
    isBudgetFriendly: true,
    ingredients: [
      '1/2 lata de atún en agua escurrida',
      '1 huevo cocido picado en cubitos',
      '1 taza de lechuga, pepino y jitomate picado',
      'Jugo de limón y pizca de sal',
    ],
    instructions: [
      'Mezcla la lechuga, pepino y jitomate en un tazón.',
      'Agrega el atún y el huevo cocido picado.',
      'Adereza con limón y sal para una cena fresca y saciante.',
    ],
    approxCalories: 245,
    approxProteinGrams: 23,
  },

  // 4. SNACKS (CONTROL DE ANSIEDAD)
  {
    id: 'rec_snk_1',
    title: 'Pepino y Jícama con Limón y Chile Piquín',
    mealType: 'snack',
    prepTimeMinutes: 3,
    isBudgetFriendly: true,
    ingredients: [
      '1 taza de pepino y/o jícama en bastoncitos',
      'Jugo de 1 limón',
      'Sal y chile piquín en polvo sin azúcar',
    ],
    instructions: [
      'Corta el pepino y jícama.',
      'Baña con limón, sal y chile. Alto en agua, fibra y saciedad instantánea.',
    ],
    approxCalories: 45,
    approxProteinGrams: 1,
  },
  {
    id: 'rec_snk_2',
    title: 'Manzana Verde con Puñadito de Cacahuates Tostados',
    mealType: 'snack',
    prepTimeMinutes: 2,
    isBudgetFriendly: true,
    ingredients: [
      '1 manzana pequeña de temporada',
      '15 cacahuates tostados sin sal (o 1 cucharadita de crema de cacahuate)',
    ],
    instructions: [
      'Rebana la manzana y acompaña con los cacahuates para una combinación saciante de fibra y grasa saludable.',
    ],
    approxCalories: 140,
    approxProteinGrams: 4,
  },
  {
    id: 'rec_snk_3',
    title: 'Mini Carlota Saludable Express en Vaso',
    mealType: 'snack',
    prepTimeMinutes: 3,
    isBudgetFriendly: true,
    ingredients: [
      '3 cucharadas de yogur natural o griego sin azúcar',
      'Gotas de jugo de limón y pizca de canela',
      '2 galletas Marías simples troceadas',
      '2 fresas rebanadas',
    ],
    instructions: [
      'Mezcla el yogur con las gotas de limón y canela.',
      'En un vasito intercala una capa de galleta troceada, yogur y decora con fresas.',
    ],
    approxCalories: 115,
    approxProteinGrams: 7,
  },
  {
    id: 'rec_snk_4',
    title: 'Huevo Cocido con Gotitas de Salsa Botanera y Sal',
    mealType: 'snack',
    prepTimeMinutes: 2,
    isBudgetFriendly: true,
    ingredients: [
      '1 huevo cocido entero',
      'Pizca de sal y gotas de limón/salsa casera',
    ],
    instructions: [
      'Pela el huevo cocido, parte a la mitad y sazona con sal, limón y gotitas de salsa picante.',
    ],
    approxCalories: 75,
    approxProteinGrams: 6,
  },
  {
    id: 'rec_snk_5',
    title: 'Bocaditos de Plátano con Canela y Crema de Cacahuate',
    mealType: 'snack',
    prepTimeMinutes: 2,
    isBudgetFriendly: true,
    ingredients: [
      '1/2 plátano en rodajas',
      '1 cucharadita de crema de cacahuate natural sin azúcar',
      'Canela en polvo',
    ],
    instructions: [
      'Coloca las rodajas de plátano, unta una pizca de crema de cacahuate y espolvorea canela.',
    ],
    approxCalories: 120,
    approxProteinGrams: 3,
  },
  {
    id: 'rec_snk_6',
    title: 'Palomitas de Maíz Caseras al Natural con Limón y Chile',
    mealType: 'snack',
    prepTimeMinutes: 5,
    isBudgetFriendly: true,
    ingredients: [
      '1.5 tazas de palomitas de maíz naturales hechas en olla con 3 gotas de aceite',
      'Jugo de limón y chile en polvo sin azúcar',
    ],
    instructions: [
      'Prepara el maíz palomero en olla tapada con mínimo aceite.',
      'Sirve caliente con jugo de limón y chile piquín para una botana con alto volumen y saciedad.',
    ],
    approxCalories: 70,
    approxProteinGrams: 2,
  },
  {
    id: 'rec_snk_7',
    title: 'Vasito de Yogur Griego Natural con Fresas',
    mealType: 'snack',
    prepTimeMinutes: 2,
    isBudgetFriendly: true,
    ingredients: [
      '1/2 taza de yogur griego sin azúcar',
      '1/4 taza de fresas frescas picadas',
      'Canela en polvo',
    ],
    instructions: [
      'Sirve el yogur griego frío en un vaso, agrega las fresas frescas y espolvorea canela.',
    ],
    approxCalories: 95,
    approxProteinGrams: 10,
  },
];
