import { ExerciseItem, RecipeItem } from '../types';

export const EXERCISES_CATALOG: ExerciseItem[] = [
  // 1. MANCUERNAS / PESAS LIBRES
  {
    id: 'ex_db_squat',
    name: 'Sentadilla Goblet con Mancuerna',
    category: 'mancuernas',
    targetMuscle: 'Cuádriceps y Glúteos',
    suggestedSets: 3,
    suggestedRepsOrSeconds: '10 - 12 reps',
    restSeconds: 60,
    description: 'Sostén una mancuerna pegada al pecho con ambas manos. Desciende como si fueras a sentarte en una silla sin despegar los talones.',
    tips: ['Mantén el pecho erguido', 'Rodillas apuntando en la misma dirección que la punta de tus pies'],
    requiresEquipment: '1 mancuerna (o botella rellena)',
    difficulty: 'principiante',
  },
  {
    id: 'ex_db_row',
    name: 'Remo a una Mano apoyado en Silla',
    category: 'mancuernas',
    targetMuscle: 'Espalda y Dorsales',
    suggestedSets: 3,
    suggestedRepsOrSeconds: '12 reps por lado',
    restSeconds: 45,
    description: 'Apoya una mano y rodilla en una silla resistente. Con el otro brazo jala la mancuerna hacia tu cadera apretando la espalda.',
    tips: ['No gires el torso', 'Conduce el movimiento con el codo'],
    requiresEquipment: '1 mancuerna + 1 silla',
    difficulty: 'principiante',
  },
  {
    id: 'ex_db_press',
    name: 'Press de Hombros Sentado',
    category: 'mancuernas',
    targetMuscle: 'Deltoides (Hombros)',
    suggestedSets: 3,
    suggestedRepsOrSeconds: '10 - 12 reps',
    restSeconds: 60,
    description: 'Sentado con la espalda recta, eleva dos mancuernas desde la altura de las orejas hacia el techo de forma controlada.',
    tips: ['No arquees la espalda baja', 'Baja lento en 2 a 3 segundos'],
    requiresEquipment: '2 mancuernas + silla',
    difficulty: 'intermedio',
  },

  // 2. LIGAS DE RESISTENCIA (TUBULARES / CON ASAS)
  {
    id: 'ex_band_row',
    name: 'Remo Sentado con Liga en Pies',
    category: 'ligas',
    targetMuscle: 'Espalda Media y Bíceps',
    suggestedSets: 3,
    suggestedRepsOrSeconds: '12 - 15 reps',
    restSeconds: 45,
    description: 'Siéntate en el suelo con piernas estiradas. Pasa la liga por la planta de los pies y jala las asas hacia tu ombligo retrayendo omóplatos.',
    tips: ['Pecho hacia afuera al jalar', 'Mantén la tensión en todo el recorrido'],
    requiresEquipment: 'Liga con asas',
    difficulty: 'principiante',
  },
  {
    id: 'ex_band_lateral',
    name: 'Elevaciones Laterales con Liga Pisada',
    category: 'ligas',
    targetMuscle: 'Hombro Lateral',
    suggestedSets: 3,
    suggestedRepsOrSeconds: '12 - 15 reps',
    restSeconds: 45,
    description: 'Pisa la liga con uno o ambos pies y eleva los brazos lateralmente hasta la altura de los hombros con codos suaves.',
    tips: ['No levantes por encima de los hombros', 'Movimiento controlado al bajar'],
    requiresEquipment: 'Liga elástica',
    difficulty: 'intermedio',
  },
  {
    id: 'ex_band_biceps',
    name: 'Curl de Bíceps con Liga',
    category: 'ligas',
    targetMuscle: 'Bíceps',
    suggestedSets: 3,
    suggestedRepsOrSeconds: '12 - 14 reps',
    restSeconds: 45,
    description: 'Pisa la liga al centro, mantén codos pegados a las costillas y flexiona antebrazos apretando al final.',
    tips: ['No balancees el cuerpo', 'Pausa 1 segundo arriba'],
    requiresEquipment: 'Liga elástica',
    difficulty: 'principiante',
  },

  // 3. BANDAS DE RESISTENCIA PARA PIERNAS (BOOTY / MINI-BANDS)
  {
    id: 'ex_mini_glute_bridge',
    name: 'Puente de Glúteos con Banda en Rodillas',
    category: 'bandas_pierna',
    targetMuscle: 'Glúteos y Femorales',
    suggestedSets: 3,
    suggestedRepsOrSeconds: '15 reps',
    restSeconds: 45,
    description: 'Acostado boca arriba con rodillas dobladas y la banda justo arriba de las rodillas. Empuja con los talones y abre rodillas contra la banda.',
    tips: ['Aprieta glúteos 2 segundos arriba', 'No hiperextiendas la columna'],
    requiresEquipment: 'Banda elástica corta de pierna',
    difficulty: 'principiante',
  },
  {
    id: 'ex_mini_clamshell',
    name: 'Abducciones Clamshell (Ostra)',
    category: 'bandas_pierna',
    targetMuscle: 'Glúteo Medio y Cadera',
    suggestedSets: 3,
    suggestedRepsOrSeconds: '12 - 15 reps por pierna',
    restSeconds: 30,
    description: 'Acostado de lado con rodillas a 90 grados y pies juntos. Abre la rodilla superior como una concha venciendo la resistencia de la banda.',
    tips: ['Mantén la pelvis estable sin rotar hacia atrás'],
    requiresEquipment: 'Banda elástica corta de pierna',
    difficulty: 'principiante',
  },
  {
    id: 'ex_mini_monster_walk',
    name: 'Pasos Laterales en Sentadilla (Monster Walk)',
    category: 'bandas_pierna',
    targetMuscle: 'Abductores y Glúteos',
    suggestedSets: 3,
    suggestedRepsOrSeconds: '10 pasos a cada lado',
    restSeconds: 60,
    description: 'Coloca la banda arriba de los tobillos o rodillas. Adopta una posición de media sentadilla y da pasos laterales controlados.',
    tips: ['Mantén siempre tensión en la banda, nunca juntes los pies del todo'],
    requiresEquipment: 'Banda elástica corta de pierna',
    difficulty: 'intermedio',
  },

  // 4. CARDIO EN CASA (SIN MÁQUINAS NI IMPACTO PELIGROSO)
  {
    id: 'ex_cardio_step_jack',
    name: 'Step Jacks (Jumping Jacks sin Salto)',
    category: 'cardio',
    targetMuscle: 'Cuerpo Completo / Cardiovascular',
    suggestedSets: 3,
    suggestedRepsOrSeconds: '45 segundos',
    restSeconds: 30,
    description: 'Abre un pie al lateral coordinando con brazos arriba, regresa al centro y abre el otro. Cero impacto para rodillas y tobillos.',
    tips: ['Mantén un ritmo constante y respiración fluida'],
    requiresEquipment: 'Ninguno',
    difficulty: 'principiante',
  },
  {
    id: 'ex_cardio_shadow_box',
    name: 'Boxeo al Aire con Giros Suaves de Torso',
    category: 'cardio',
    targetMuscle: 'Cardio y Core',
    suggestedSets: 3,
    suggestedRepsOrSeconds: '45 segundos',
    restSeconds: 30,
    description: 'Lanza golpes rectos alternados al aire contrayendo el abdomen en cada impacto virtual.',
    tips: ['No bloquees los codos de golpe', 'Mueve ligeramente los pies'],
    requiresEquipment: 'Ninguno',
    difficulty: 'principiante',
  },

  // 5. PESO CORPORAL
  {
    id: 'ex_body_incline_pushup',
    name: 'Flexiones Inclinadas en Pared o Sofá',
    category: 'peso_corporal',
    targetMuscle: 'Pectoral, Tríceps y Core',
    suggestedSets: 3,
    suggestedRepsOrSeconds: '10 - 12 reps',
    restSeconds: 45,
    description: 'Apoya las manos en la pared o borde del sofá manteniendo el cuerpo recto como una tabla. Flexiona brazos hasta acercar el pecho.',
    tips: ['Cuerpo alineado como una plancha', 'No dejes caer la cadera'],
    requiresEquipment: 'Pared o sofá',
    difficulty: 'principiante',
  },
];

export const RECIPES_CATALOG: RecipeItem[] = [
  // 1. DESAYUNOS
  {
    id: 'rec_des_1',
    title: 'Huevos a la Mexicana con Tortillas de Maíz',
    mealType: 'breakfast',
    prepTimeMinutes: 10,
    isBudgetFriendly: true,
    ingredients: [
      '2 huevos enteros',
      '1 tomate picado',
      '1/4 de cebolla picada',
      '1 cucharadita de aceite común',
      '2 tortillas de maíz',
    ],
    instructions: [
      'Pica el tomate y la cebolla finamente.',
      'Sofríelos en sartén con una cucharadita de aceite durante 2 minutos.',
      'Bate los huevos, agrégalos al sartén con sal al gusto y revuelve.',
      'Acompaña con las 2 tortillas calientes y café o té sin azúcar.',
    ],
    approxCalories: 320,
    approxProteinGrams: 16,
  },
  {
    id: 'rec_des_2',
    title: 'Avena Cocida con Manzana y Canela',
    mealType: 'breakfast',
    prepTimeMinutes: 8,
    isBudgetFriendly: true,
    ingredients: [
      '4 cucharadas soperas de hojuelas de avena',
      '1 taza de agua o leche semidescremada',
      '1/2 manzana picada en cubitos',
      '1 pizca de canela en polvo',
      '1 huevo duro aparte',
    ],
    instructions: [
      'Hierve el agua o leche y agrega la avena.',
      'Cocina a fuego medio por 3-4 minutos moviendo constantemente.',
      'Sirve caliente, agrega la manzana en cubos y espolvorea canela.',
      'Come el huevo duro para asegurar tu aporte de proteína y saciedad.',
    ],
    approxCalories: 310,
    approxProteinGrams: 15,
  },

  // 2. COMIDAS / ALMUERZOS
  {
    id: 'rec_com_1',
    title: 'Pechuga a la Plancha con Arroz y Ensalada Fresca',
    mealType: 'lunch',
    prepTimeMinutes: 15,
    isBudgetFriendly: true,
    ingredients: [
      '130g de pechuga de pollo',
      '1/2 taza de arroz cocido',
      '1 taza de lechuga picada con pepino y limón',
      '1 cucharadita de aceite para dorar',
    ],
    instructions: [
      'Sazona el pollo con ajo, sal, pimienta y limón.',
      'Dora en sartén caliente 3-4 minutos por lado hasta que esté bien cocido.',
      'Sirve con el arroz al lado y la ensalada fresca aderezada con limón y sal.',
    ],
    approxCalories: 410,
    approxProteinGrams: 34,
  },
  {
    id: 'rec_com_2',
    title: 'Atún en Lata a la Mexicana con Papita Cocida',
    mealType: 'lunch',
    prepTimeMinutes: 10,
    isBudgetFriendly: true,
    ingredients: [
      '1 lata de atún en agua escurrido',
      '1 tomate picado, cilantro y cebolla',
      '1 papa mediana cocida',
      'Gotas de limón y sal',
    ],
    instructions: [
      'Cuece la papa en agua con sal o microondas por 5 minutos hasta que esté suave.',
      'Mezcla el atún escurrido con el tomate, cebolla, cilantro y limón.',
      'Pica la papa y combínala con el atún fresco.',
    ],
    approxCalories: 330,
    approxProteinGrams: 28,
  },

  // 3. CENAS
  {
    id: 'rec_cen_1',
    title: 'Quesadillas Ligeras con Champiñones',
    mealType: 'dinner',
    prepTimeMinutes: 8,
    isBudgetFriendly: true,
    ingredients: [
      '2 tortillas de maíz',
      '50g de queso panela o queso fresco desmoronado',
      '1/2 taza de champiñones picados',
    ],
    instructions: [
      'Dora los champiñones en sartén caliente sin aceite por 2 minutos con pizca de sal.',
      'Coloca el queso y los champiñones dentro de las tortillas.',
      'Calienta en el comal hasta que el queso se suavice.',
    ],
    approxCalories: 260,
    approxProteinGrams: 14,
  },
  {
    id: 'rec_cen_2',
    title: 'Sándwich Clásico Casero de Jamón y Queso Panela',
    mealType: 'dinner',
    prepTimeMinutes: 5,
    isBudgetFriendly: true,
    ingredients: [
      '2 rebanadas de pan de molde común o integral',
      '2 rebanadas de jamón de pavo',
      '1 rebanada de queso panela',
      'Hojas de lechuga, rodajas de jitomate y mostaza al gusto',
    ],
    instructions: [
      'Unta una capa fina de mostaza en el pan.',
      'Arma el sándwich con el jamón, queso, lechuga y jitomate.',
      'Tuesta ligeramente en sartén si te gusta crujiente.',
    ],
    approxCalories: 270,
    approxProteinGrams: 16,
  },

  // 4. SNACKS (CONTROL DE ANSIEDAD)
  {
    id: 'rec_snk_1',
    title: 'Pepino y Jícama con Limón y Chile Piquín',
    mealType: 'snack',
    prepTimeMinutes: 3,
    isBudgetFriendly: true,
    ingredients: [
      '1 taza de pepino y/o jícama en bastoncitos',
      'Jugo de 1 limón',
      'Sal y chile piquín en polvo sin azúcar',
    ],
    instructions: [
      'Corta el pepino y jícama.',
      'Baña con limón, sal y chile. Alto en agua, fibra y saciedad instantánea.',
    ],
    approxCalories: 45,
    approxProteinGrams: 1,
  },
  {
    id: 'rec_snk_2',
    title: 'Manzana con Puñadito de Cacahuates Naturales',
    mealType: 'snack',
    prepTimeMinutes: 2,
    isBudgetFriendly: true,
    ingredients: [
      '1 manzana pequeña de temporada',
      '15 cacahuates tostados sin sal (o 1 cucharadita de crema de cacahuate)',
    ],
    instructions: [
      'Rebana la manzana y acompaña con los cacahuates para una combinación saciante de fibra y grasa saludable.',
    ],
    approxCalories: 140,
    approxProteinGrams: 4,
  },
  {
    id: 'rec_snk_3',
    title: 'Gelatina Sin Azúcar con Yogur Natural',
    mealType: 'snack',
    prepTimeMinutes: 2,
    isBudgetFriendly: true,
    ingredients: [
      '1 vaso de gelatina light comercial (cualquier sabor)',
      '2 cucharadas de yogur natural sin azúcar',
    ],
    instructions: [
      'Coloca la porción de gelatina y corona con el yogur para un postre refrescante cero culpa.',
    ],
    approxCalories: 60,
    approxProteinGrams: 4,
  },
];
