import { RecipeItem } from '../types';

export const RECIPES_CATALOG: RecipeItem[] = [
  // 1. DESAYUNOS
  {
    id: 'rec_des_1',
    title: 'Huevos a la Mexicana con Tortillas de Maíz',
    mealType: 'breakfast',
    prepTimeMinutes: 10,
    isBudgetFriendly: true,
    ingredients: [
      '2 huevos enteros',
      '1 tomate picado',
      '1/4 de cebolla picada',
      '1 cucharadita de aceite común',
      '2 tortillas de maíz',
    ],
    instructions: [
      'Pica el tomate y la cebolla finamente.',
      'Sofríelos en sartén con una cucharadita de aceite durante 2 minutos.',
      'Bate los huevos, agrégalos al sartén con sal al gusto y revuelve.',
      'Acompaña con las 2 tortillas calientes y café o té sin azúcar.',
    ],
    approxCalories: 320,
    approxProteinGrams: 16,
  },
  {
    id: 'rec_des_2',
    title: 'Avena Cocida con Manzana, Canela y Huevo Duro',
    mealType: 'breakfast',
    prepTimeMinutes: 8,
    isBudgetFriendly: true,
    ingredients: [
      '4 cucharadas soperas de hojuelas de avena',
      '1 taza de agua o leche semidescremada',
      '1/2 manzana picada en cubitos',
      '1 pizca de canela en polvo',
      '1 huevo duro aparte',
    ],
    instructions: [
      'Hierve el agua o leche y agrega la avena.',
      'Cocina a fuego medio por 3-4 minutos moviendo constantemente.',
      'Sirve caliente, agrega la manzana en cubos y espolvorea canela.',
      'Come el huevo duro para asegurar tu aporte de proteína y saciedad.',
    ],
    approxCalories: 310,
    approxProteinGrams: 15,
  },
  {
    id: 'rec_des_3',
    title: 'Omelette Esponjoso de Espinacas y Queso Panela',
    mealType: 'breakfast',
    prepTimeMinutes: 10,
    isBudgetFriendly: true,
    ingredients: [
      '2 huevos enteros',
      '1 taza de espinacas frescas picadas',
      '40g de queso panela en cubos',
      '1 cucharadita de aceite',
      '1 tortilla de maíz o rebanada de pan integral',
    ],
    instructions: [
      'Bate los 2 huevos con sal y pimienta al gusto.',
      'Calienta el sartén con la cucharadita de aceite y vierte los huevos con la espinaca picada.',
      'Coloca el queso panela en el centro y dobla en forma de media luna.',
      'Cocina 1 minuto más y sirve con la tortilla de maíz caliente.',
    ],
    approxCalories: 310,
    approxProteinGrams: 18,
  },
  {
    id: 'rec_des_4',
    title: 'Pan Tostado con Dip de Huevo Cocido y Espinaca',
    mealType: 'breakfast',
    prepTimeMinutes: 8,
    isBudgetFriendly: true,
    ingredients: [
      '2 rebanadas de pan de molde integral',
      '2 huevos cocidos',
      '1 puñado de espinacas finamente picadas',
      '1/4 de aguacate',
      '1 cucharada de yogur natural sin azúcar',
    ],
    instructions: [
      'Tuesta las 2 rebanadas de pan integral hasta que estén crujientes.',
      'En un tazón, machaca los huevos cocidos con el aguacate, la espinaca y el yogur con sal y pimienta.',
      'Unta la mezcla generosamente sobre las rebanadas de pan tostado.',
    ],
    approxCalories: 290,
    approxProteinGrams: 15,
  },
  {
    id: 'rec_des_5',
    title: 'Sope Casero de Avena con Frijolitos y Huevo Revuelto',
    mealType: 'breakfast',
    prepTimeMinutes: 15,
    isBudgetFriendly: true,
    ingredients: [
      '4 cucharadas de avena molida (harina de avena)',
      '3-4 cucharadas de agua tibia',
      '2 cucharadas de frijoles molidos sin manteca',
      '1 huevo revuelto',
      'Salsa de tomate casera y 20g de queso fresco',
    ],
    instructions: [
      'Mezcla la avena molida con agua tibia y pizca de sal hasta formar una masa suave.',
      'Forma un sope con las manos y dóralo en comal por ambos lados hasta que esté cocido.',
      'Unta los frijoles calientes, agrega el huevo revuelto encima y corona con queso fresco y salsa.',
    ],
    approxCalories: 330,
    approxProteinGrams: 16,
  },
  {
    id: 'rec_des_6',
    title: 'Chilaquiles Ligeros al Comal con Huevo Estrellado',
    mealType: 'breakfast',
    prepTimeMinutes: 12,
    isBudgetFriendly: true,
    ingredients: [
      '2 tortillas de maíz cortadas en triángulos',
      '1/2 taza de salsa verde o roja hervida casera',
      '1 huevo estrellado a la plancha',
      '30g de queso fresco desmoronado',
      'Cebolla picada y cilantro al gusto',
    ],
    instructions: [
      'Dora los triángulos de tortilla en comal sin aceite hasta que queden como totopos crujientes.',
      'Calienta la salsa en una ollita y baña los totopos en el plato.',
      'Coloca el huevo estrellado encima y decora con queso fresco, cebolla y cilantro.',
    ],
    approxCalories: 320,
    approxProteinGrams: 15,
  },
  {
    id: 'rec_des_7',
    title: 'Pancitos Individuales de Avena Express al Microondas',
    mealType: 'breakfast',
    prepTimeMinutes: 6,
    isBudgetFriendly: true,
    ingredients: [
      '4 cucharadas de avena molida',
      '1 huevo entero',
      '1 cucharada de yogur natural sin azúcar',
      '1/4 cucharadita de polvo para hornear',
      'Canela en polvo al gusto',
    ],
    instructions: [
      'Mezcla todos los ingredientes en una taza o molde pequeño apto para microondas.',
      'Cocina en microondas por 1.5 a 2 minutos hasta que esponje.',
      'Desmolda, rebana a la mitad y acompaña con café o té caliente sin azúcar.',
    ],
    approxCalories: 280,
    approxProteinGrams: 14,
  },
  {
    id: 'rec_des_8',
    title: 'Huevos Rancheros Ligeros con Tostadas Horneadas',
    mealType: 'breakfast',
    prepTimeMinutes: 10,
    isBudgetFriendly: true,
    ingredients: [
      '2 huevos a la plancha',
      '2 tostadas de maíz horneadas sin grasa',
      '1/2 taza de salsa ranchera de tomate y chile asado',
      '2 cucharadas de frijoles de la olla enteros',
    ],
    instructions: [
      'Coloca las 2 tostadas horneadas con los frijoles machacados ligeramente.',
      'Monta un huevo a la plancha sobre cada tostada.',
      'Baña con la salsa ranchera caliente.',
    ],
    approxCalories: 315,
    approxProteinGrams: 16,
  },
  {
    id: 'rec_des_9',
    title: 'Tazón de Avena con Plátano, Cacahuates y Canela',
    mealType: 'breakfast',
    prepTimeMinutes: 7,
    isBudgetFriendly: true,
    ingredients: [
      '5 cucharadas de hojuelas de avena',
      '1 taza de agua tibia o infusión de canela',
      '1/2 plátano rebanado',
      '1 cucharada de cacahuates tostados sin sal',
      'Canela en polvo al gusto',
    ],
    instructions: [
      'Cocina la avena con el agua y una pizca de canela a fuego medio durante 3 minutos.',
      'Sirve caliente en un tazón.',
      'Agrega el plátano en rodajas y los cacahuates para un aporte crujiente y energético.',
    ],
    approxCalories: 290,
    approxProteinGrams: 11,
  },
  {
    id: 'rec_des_10',
    title: 'Tostadas de Frijol Negro con Aguacate y Pico de Gallo',
    mealType: 'breakfast',
    prepTimeMinutes: 6,
    isBudgetFriendly: true,
    ingredients: [
      '2 tostadas de maíz horneadas sin grasa',
      '1/2 taza de frijoles negros machacados',
      '1/4 de aguacate rebanado',
      'Pico de gallo fresco (jitomate, cebolla y cilantro)',
    ],
    instructions: [
      'Unta los frijoles negros calientes sobre las dos tostadas.',
      'Coloca rebanadas de aguacate encima.',
      'Corona con abundante pico de gallo y unas gotas de limón.',
    ],
    approxCalories: 280,
    approxProteinGrams: 10,
  },
  // Desayunos Institucionales NUTRIMSS 2024 (SMAE 5ª Edición)
  {
    id: 'rec_des_11',
    title: 'Sándwich de Queso Blanco con Manzana y Leche',
    mealType: 'breakfast',
    prepTimeMinutes: 6,
    isBudgetFriendly: true,
    ingredients: [
      '2 rebanadas de pan de caja integral',
      '70g de queso blanco o panela',
      '1/3 de pieza de aguacate',
      '1 jitomate en rodajas y 1 taza de lechuga',
      '1 manzana fresca',
      '1 taza de leche descremada',
    ],
    instructions: [
      'Coloca las rebanadas de queso blanco, jitomate, lechuga y aguacate en el pan.',
      'Acompaña con 1 manzana fresca de temporada y 1 vaso de leche descremada bien fría.',
    ],
    approxCalories: 340,
    approxProteinGrams: 18,
  },
  {
    id: 'rec_des_12',
    title: 'Huevo en Salsa Verde con Nopales, Papaya y Yogur',
    mealType: 'breakfast',
    prepTimeMinutes: 10,
    isBudgetFriendly: true,
    ingredients: [
      '2 huevos enteros',
      '1 taza de nopales picados cocidos',
      'Salsa verde casera al gusto',
      '2 tortillas de maíz',
      '1 cucharadita de aceite común',
      '1 taza de papaya picada',
      '1 taza de yogur natural sin azúcar',
    ],
    instructions: [
      'Revuelve o estrella los 2 huevos en sartén con la cucharadita de aceite y los nopales cocidos.',
      'Baña con salsa verde caliente al gusto.',
      'Acompaña con 2 tortillas de maíz calientes y disfruta la papaya fresca con yogur natural.',
    ],
    approxCalories: 330,
    approxProteinGrams: 18,
  },
  {
    id: 'rec_des_13',
    title: 'Quesadillas con Flor de Calabaza, Melón y Yogur',
    mealType: 'breakfast',
    prepTimeMinutes: 8,
    isBudgetFriendly: true,
    ingredients: [
      '2 tortillas de maíz',
      '80g de queso panela',
      '1 taza de flor de calabaza limpia',
      '1 cucharadita de aceite',
      '1 taza de melón picado',
      '1 taza de yogur natural sin azúcar',
    ],
    instructions: [
      'Saltea ligeramente la flor de calabaza con una pizca de sal.',
      'Rellena las tortillas con el queso panela y la flor de calabaza.',
      'Calienta en comal hasta dorar y acompaña con un tazón de melón picado y yogur.',
    ],
    approxCalories: 320,
    approxProteinGrams: 17,
  },
  {
    id: 'rec_des_14',
    title: 'Tacos de Queso Blanco con Pico de Gallo y Fresas',
    mealType: 'breakfast',
    prepTimeMinutes: 6,
    isBudgetFriendly: true,
    ingredients: [
      '2 tortillas de maíz',
      '70g de queso blanco o panela',
      '1/3 de pieza de aguacate',
      '1 taza de pico de gallo (jitomate, cebolla, cilantro y chile)',
      '1 taza de fresas rebanadas',
      '1 taza de yogur natural sin azúcar',
    ],
    instructions: [
      'Calienta las tortillas de maíz en comal.',
      'Rellena con el queso blanco, rebanadas de aguacate y abundante pico de gallo fresco.',
      'Degusta con un tazón de fresas rebanadas y yogur natural.',
    ],
    approxCalories: 330,
    approxProteinGrams: 16,
  },
  {
    id: 'rec_des_15',
    title: 'Enchiladas Ligeras de Pollo con Durazno y Yogur',
    mealType: 'breakfast',
    prepTimeMinutes: 12,
    isBudgetFriendly: true,
    ingredients: [
      '60g de pechuga de pollo cocida y deshebrada',
      '2 tortillas de maíz pasadas por comal',
      'Salsa verde o roja hervida al gusto',
      '1 taza de pico de gallo',
      '1 cucharadita de aceite',
      '2 piezas de durazno amarillo',
      '1 taza de yogur natural sin azúcar',
    ],
    instructions: [
      'Rellena las tortillas con la pechuga de pollo deshebrada y enrolla en el plato.',
      'Baña con la salsa verde o roja caliente y corona con pico de gallo fresco.',
      'Acompaña con 2 duraznos frescos y yogur natural.',
    ],
    approxCalories: 350,
    approxProteinGrams: 22,
  },
  {
    id: 'rec_des_16',
    title: 'Quesadillas de Champiñones con Pera y Leche',
    mealType: 'breakfast',
    prepTimeMinutes: 8,
    isBudgetFriendly: true,
    ingredients: [
      '2 tortillas de maíz',
      '1/2 taza de champiñones picados',
      '70g de queso blanco o panela',
      '1/3 de pieza de aguacate',
      '1 taza de pico de gallo',
      '1/2 pieza de pera de temporada',
      '1 taza de leche descremada',
    ],
    instructions: [
      'Saltea los champiñones al comal o sartén con pizca de sal.',
      'Arma las quesadillas con el queso y champiñones, dorándolas en comal.',
      'Agrega aguacate y pico de gallo fresco al gusto; acompaña con media pera y vaso de leche descremada.',
    ],
    approxCalories: 340,
    approxProteinGrams: 17,
  },
  {
    id: 'rec_des_17',
    title: 'Calabacitas a la Mexicana con Panela y Arándanos',
    mealType: 'breakfast',
    prepTimeMinutes: 10,
    isBudgetFriendly: true,
    ingredients: [
      '1/2 taza de calabacita picada',
      '1/2 taza de elote desgranado cocido',
      '1 taza de jitomate y cebolla picada',
      '80g de queso panela en cubitos',
      '1 tortilla de maíz',
      '1 cucharadita de aceite',
      '1/2 taza de arándanos secos',
      '1 taza de yogur natural sin azúcar',
    ],
    instructions: [
      'Sofríe la calabacita, elote, jitomate y cebolla en sartén con 1 cucharadita de aceite hasta que estén tiernos.',
      'Agrega el queso panela en cubos al final para que tome temperatura.',
      'Sirve con 1 tortilla caliente y disfruta tu tazón de yogur con arándanos secos.',
    ],
    approxCalories: 310,
    approxProteinGrams: 16,
  },
  {
    id: 'rec_des_18',
    title: 'Machaca a la Mexicana con Verduras al Vapor y Leche',
    mealType: 'breakfast',
    prepTimeMinutes: 10,
    isBudgetFriendly: true,
    ingredients: [
      '60g de machaca de res',
      'Jitomate y cebolla picados al gusto',
      '1 taza de calabacita y zanahoria hervidas',
      '2 tortillas de maíz',
      '1 cucharadita de aceite',
      '1 taza de fresas rebanadas',
      '1 taza de leche descremada',
    ],
    instructions: [
      'Sofríe el jitomate y cebolla con la cucharadita de aceite y saltea la machaca de res durante 3 minutos.',
      'Sirve acompañada de las verduras al vapor y 2 tortillas de maíz calientes.',
      'Complementa con las fresas rebanadas y el vaso de leche descremada.',
    ],
    approxCalories: 350,
    approxProteinGrams: 24,
  },
  {
    id: 'rec_des_19',
    title: 'Molletes Ligeros con Panela, Aguacate y Manzana',
    mealType: 'breakfast',
    prepTimeMinutes: 8,
    isBudgetFriendly: true,
    ingredients: [
      '2/3 de pieza de telera sin migajón (o bolillo/pan integral)',
      '1/3 de taza de frijoles machacados sin manteca',
      '80g de queso panela',
      '1 taza de pico de gallo fresco',
      '1/3 de pieza de aguacate',
      '1 manzana de temporada',
    ],
    instructions: [
      'Dora el pan en comal o sartén.',
      'Unta los frijoles calientes y coloca las rebanadas de queso panela encima.',
      'Corona con abundante pico de gallo y aguacate; degusta con 1 manzana fresca.',
    ],
    approxCalories: 350,
    approxProteinGrams: 18,
  },
  {
    id: 'rec_des_20',
    title: 'Chayote con Queso Panela, Melón y Yogur',
    mealType: 'breakfast',
    prepTimeMinutes: 10,
    isBudgetFriendly: true,
    ingredients: [
      '1/2 taza de chayote hervido en cubos',
      '80g de queso panela en rebanadas',
      '2 tortillas de maíz',
      '1/3 de pieza de aguacate',
      '1 taza de melón picado',
      '1 taza de yogur natural sin azúcar',
    ],
    instructions: [
      'Cuece el chayote al vapor con una pizca de sal.',
      'Sírvelo calientito junto con el queso panela, aguacate y 2 tortillas de maíz.',
      'Disfruta el melón fresco con yogur natural.',
    ],
    approxCalories: 320,
    approxProteinGrams: 16,
  },
  {
    id: 'rec_des_21',
    title: 'Huevo sobre Pan Tostado con Frijoles y Ejotes',
    mealType: 'breakfast',
    prepTimeMinutes: 8,
    isBudgetFriendly: true,
    ingredients: [
      '2 piezas de pan integral tostado',
      '1/2 taza de frijoles de la olla machacados',
      '2 huevos enteros a la plancha',
      '1/2 taza de ejotes cocidos',
      '1 cucharadita de aceite',
      'Salsa al gusto',
      '3 piezas de ciruela fresca',
    ],
    instructions: [
      'Unta los frijoles sobre las 2 rebanadas de pan tostado crujiente.',
      'Monta los huevos cocinados a la plancha con la cucharadita de aceite y los ejotes al vapor.',
      'Baña con salsa casera al gusto y come las ciruelas frescas de postre.',
    ],
    approxCalories: 340,
    approxProteinGrams: 18,
  },
  {
    id: 'rec_des_22',
    title: 'Chilaquiles Ligeros de Pollo con Papaya y Yogur',
    mealType: 'breakfast',
    prepTimeMinutes: 12,
    isBudgetFriendly: true,
    ingredients: [
      '2 tortillas de maíz horneadas o tostadas en comal troceadas',
      '60g de pechuga de pollo deshebrada',
      'Salsa verde o roja al gusto',
      '1 taza de verdura hervida (calabacita o chayote)',
      '1/3 de pieza de aguacate',
      '1 taza de papaya picada',
      '1 taza de yogur natural sin azúcar',
    ],
    instructions: [
      'Baña los totopos horneados con la salsa caliente.',
      'Agrega el pollo deshebrado, el aguacate en cubos y las verduras hervidas al lado.',
      'Acompaña con el tazón de papaya picada y yogur natural.',
    ],
    approxCalories: 350,
    approxProteinGrams: 23,
  },
  {
    id: 'rec_des_23',
    title: 'Caldo Tlalpeño Matutino con Uvas y Yogur',
    mealType: 'breakfast',
    prepTimeMinutes: 12,
    isBudgetFriendly: true,
    ingredients: [
      '60g de pechuga de pollo deshebrada',
      '1 taza de verduras mixtas (zanahoria, ejote, calabacita)',
      '1/4 de taza de arroz cocido',
      '1 tortilla de maíz',
      '1 cucharadita de aceite',
      '18 piezas de uvas frescas',
      '1 taza de yogur natural sin azúcar',
    ],
    instructions: [
      'Calienta el caldo de pollo con las verduras mixtas, el arroz y el pollo deshebrado con un toque de epazote y chipotle.',
      'Sirve caliente con 1 tortilla de maíz.',
      'Disfruta las uvas frescas con yogur natural.',
    ],
    approxCalories: 340,
    approxProteinGrams: 22,
  },
  {
    id: 'rec_des_24',
    title: 'Huevos Ahogados en Salsa Verde con Nopales',
    mealType: 'breakfast',
    prepTimeMinutes: 10,
    isBudgetFriendly: true,
    ingredients: [
      '2 huevos enteros',
      '1 taza de nopales picados cocidos',
      'Salsa verde casera hervida',
      '2 tortillas de maíz',
      '1 cucharadita de aceite',
      '1 taza de papaya picada',
      '1 taza de yogur natural sin azúcar',
    ],
    instructions: [
      'Hierve la salsa verde en una cazuelita con los nopales.',
      'Casca los 2 huevos directamente dentro de la salsa hirviendo y tapa a fuego bajo por 4 minutos hasta que cuajen.',
      'Sirve caliente con las tortillas y acompaña con papaya fresca y yogur.',
    ],
    approxCalories: 330,
    approxProteinGrams: 18,
  },
  {
    id: 'rec_des_25',
    title: 'Torta Casera de Pollo con Panela, Fresas y Yogur',
    mealType: 'breakfast',
    prepTimeMinutes: 7,
    isBudgetFriendly: true,
    ingredients: [
      '2/3 de pieza de telera sin migajón',
      '30g de pechuga de pollo deshebrada',
      '40g de queso panela en rebanadas',
      '1 jitomate y 1 taza de lechuga',
      '1/3 de pieza de aguacate',
      '1 taza de fresas rebanadas',
      '1 taza de yogur natural sin azúcar',
    ],
    instructions: [
      'Dora la telera en comal y arma la torta con el pollo deshebrado, queso panela, aguacate, jitomate y lechuga.',
      'Acompaña con el vasito de fresas frescas con yogur natural sin azúcar.',
    ],
    approxCalories: 340,
    approxProteinGrams: 20,
  },
  {
    id: 'rec_des_26',
    title: 'Flautas de Pollo al Comal con Arándanos y Yogur',
    mealType: 'breakfast',
    prepTimeMinutes: 10,
    isBudgetFriendly: true,
    ingredients: [
      '2 tortillas de maíz',
      '60g de pechuga de pollo deshebrada',
      '1 taza de verdura (lechuga, jitomate y cebolla)',
      '1 cucharadita de aceite',
      '1/2 taza de arándanos secos',
      '1 taza de yogur natural sin azúcar',
    ],
    instructions: [
      'Rellena las tortillas con el pollo, enrolla en flautas y dora en comal caliente con la cucharadita de aceite.',
      'Cubre con ensalada fresca de lechuga, jitomate y cebolla.',
      'Acompaña con el yogur natural y los arándanos secos.',
    ],
    approxCalories: 340,
    approxProteinGrams: 21,
  },
  {
    id: 'rec_des_27',
    title: 'Enfrijoladas de Pollo con Pico de Gallo y Mango',
    mealType: 'breakfast',
    prepTimeMinutes: 10,
    isBudgetFriendly: true,
    ingredients: [
      '2 tortillas de maíz',
      '60g de pechuga de pollo deshebrada',
      '1/2 taza de frijoles caldosos licuados con toque de epazote',
      '1 taza de pico de gallo',
      '1 cucharadita de aceite',
      '1/2 pieza de mango ataúlfo',
    ],
    instructions: [
      'Pasa las tortillas por comal y rellénalas con el pollo deshebrado.',
      'Baña con los frijoles caldosos licuados y calientes.',
      'Corona con abundante pico de gallo fresco y disfruta el mango de temporada.',
    ],
    approxCalories: 360,
    approxProteinGrams: 24,
  },
  {
    id: 'rec_des_28',
    title: 'Nopales con Huevo y Frijoles de la Olla',
    mealType: 'breakfast',
    prepTimeMinutes: 12,
    isBudgetFriendly: true,
    ingredients: [
      '1.5 tazas de nopales cocidos en cubos',
      '2 huevos frescos',
      '1/4 de cebolla y 1 diente de ajo picados',
      '1 cucharadita de aceite vegetal',
      '1/2 taza de frijoles de la olla',
      '2 tortillas de maíz',
      'Sal y pimienta al gusto',
    ],
    instructions: [
      'Cuece los nopales en agua y escúrrelos.',
      'Sofríe el ajo y la cebolla en una sartén con el aceite vegetal.',
      'Agrega los nopales, sazona y vierte los huevos previamente batidos.',
      'Revuelve hasta que el huevo esté bien cocido.',
      'Sirve acompañado con los frijoles de la olla calientes y las 2 tortillas de maíz.',
    ],
    approxCalories: 360,
    approxProteinGrams: 19,
  },
  {
    id: 'rec_des_29',
    title: 'Machaca con Verduras y Huevo',
    mealType: 'breakfast',
    prepTimeMinutes: 15,
    isBudgetFriendly: true,
    ingredients: [
      '60g de carne machaca de res',
      '1 huevo fresco',
      '2 jitomates medianos picados',
      '1/2 cebolla picada',
      '1 chile verde o poblano picado',
      '1/2 papa picada en cuadritos',
      '1 cucharadita de aceite vegetal',
      '2 tortillas de maíz',
      'Sal al gusto',
    ],
    instructions: [
      'Sofríe los cuadritos de papa en sartén con el aceite hasta que estén dorados y suaves.',
      'Añade la carne machaca, el ajo y la cebolla; fríe por 2 minutos a fuego medio.',
      'Agrega el jitomate y el chile verde picado, cocina hasta sazonar.',
      'Vierte el huevo batido con una pizca de sal y revuelve bien hasta cocer.',
      'Sirve caliente acompañado de las 2 tortillas de maíz.',
    ],
    approxCalories: 370,
    approxProteinGrams: 22,
  },
  {
    id: 'rec_des_30',
    title: 'Guayín de Huevo Relleno de Frijoles en Salsa',
    mealType: 'breakfast',
    prepTimeMinutes: 12,
    isBudgetFriendly: true,
    ingredients: [
      '2 huevos frescos',
      '1/3 de taza de frijoles refritos caseros',
      '2 jitomates medianos para la salsa',
      '1/4 de cebolla y 1 diente de ajo',
      '1 chile verde',
      '1 cucharadita de aceite vegetal',
      '2 tortillas de maíz',
      'Sal al gusto',
    ],
    instructions: [
      'Bate los huevos y fríelos en una sartén amplia formando una tortilla delgada de huevo.',
      'Unta los frijoles refritos en el centro de la tortilla de huevo y enróllala en forma de taco.',
      'Para la salsa: cuece jitomates, cebolla, ajo y chile; licúa con un chorrito de agua y sazona en sartén con sal.',
      'Baña el guayín con la salsa de jitomate caliente y sirve acompañado de tortillas de maíz.',
    ],
    approxCalories: 340,
    approxProteinGrams: 18,
  },

  // 2. COMIDAS / ALMUERZOS
  {
    id: 'rec_com_1',
    title: 'Pechuga a la Plancha con Arroz y Ensalada Fresca',
    mealType: 'lunch',
    prepTimeMinutes: 15,
    isBudgetFriendly: true,
    ingredients: [
      '130g de pechuga de pollo',
      '1/2 taza de arroz cocido',
      '1 taza de lechuga picada con pepino y limón',
      '1 cucharadita de aceite para dorar',
    ],
    instructions: [
      'Sazona el pollo con ajo, sal, pimienta y limón.',
      'Dora en sartén caliente 3-4 minutos por lado hasta que esté bien cocido.',
      'Sirve con el arroz al lado y la ensalada fresca aderezada con limón y sal.',
    ],
    approxCalories: 410,
    approxProteinGrams: 34,
  },
  {
    id: 'rec_com_2',
    title: 'Atún en Lata a la Mexicana con Papita Cocida',
    mealType: 'lunch',
    prepTimeMinutes: 10,
    isBudgetFriendly: true,
    ingredients: [
      '1 lata de atún en agua escurrido',
      '1 tomate picado, cilantro y cebolla',
      '1 papa mediana cocida',
      'Gotas de limón y sal',
    ],
    instructions: [
      'Cuece la papa en agua con sal o microondas por 5 minutos hasta que esté suave.',
      'Mezcla el atún escurrido con el tomate, cebolla, cilantro y limón.',
      'Pica la papa y combínala con el atún fresco.',
    ],
    approxCalories: 330,
    approxProteinGrams: 28,
  },
  {
    id: 'rec_com_3',
    title: 'Calabacitas a la Bolognesa Casera con Carne Magra',
    mealType: 'lunch',
    prepTimeMinutes: 15,
    isBudgetFriendly: true,
    ingredients: [
      '120g de carne molida magra de res o pollo',
      '2 calabacitas medianas en cubos',
      '2 jitomates licuados con ajo, cebolla y orégano',
      '1 cucharadita de aceite común',
    ],
    instructions: [
      'Sofríe la carne molida en sartén con la cucharadita de aceite hasta que cambie de color.',
      'Agrega las calabacitas picadas y vierte el puré de jitomate natural con sal y orégano.',
      'Tapa y cocina a fuego medio por 8 minutos hasta que las calabacitas estén tiernas y jugosas.',
    ],
    approxCalories: 380,
    approxProteinGrams: 32,
  },
  {
    id: 'rec_com_4',
    title: 'Atún en Salsa Cremosa de Chipotle con Tostadas y Aguacate',
    mealType: 'lunch',
    prepTimeMinutes: 10,
    isBudgetFriendly: true,
    ingredients: [
      '1 lata de atún en agua escurrida',
      '1 jitomate licuado con 1/2 chipotle y 1 cda de yogur natural',
      '1/4 de cebolla en plumitas',
      '2 tostadas de maíz horneadas',
      '1/4 de aguacate y lechuga picada',
    ],
    instructions: [
      'Acitrona la cebolla en sartén con gotitas de agua o aceite.',
      'Agrega el atún y vierte la salsa licuada de jitomate con chipotle y yogur.',
      'Cocina por 3 minutos hasta que espese. Sirve sobre las tostadas con lechuga y rebanadas de aguacate.',
    ],
    approxCalories: 340,
    approxProteinGrams: 28,
  },
  {
    id: 'rec_com_5',
    title: 'Tostadas de Tinga de Pollo Ligera',
    mealType: 'lunch',
    prepTimeMinutes: 15,
    isBudgetFriendly: true,
    ingredients: [
      '120g de pechuga de pollo cocida y deshebrada',
      '2 jitomates y 1/2 chile chipotle licuados',
      '1/4 de cebolla rebanada',
      '2 tostadas de maíz horneadas',
      'Lechuga picada y 30g de queso panela desmoronado',
    ],
    instructions: [
      'Sofríe la cebolla en sartén, agrega la salsa de jitomate con chipotle y sazona con orégano y sal.',
      'Incorpora el pollo deshebrado y deja hervir por 5 minutos.',
      'Sirve sobre las tostadas horneadas con lechuga fresca y queso panela.',
    ],
    approxCalories: 390,
    approxProteinGrams: 34,
  },
  {
    id: 'rec_com_6',
    title: 'Pescadillas / Tacos de Atún al Comal con Ensalada de Col',
    mealType: 'lunch',
    prepTimeMinutes: 12,
    isBudgetFriendly: true,
    ingredients: [
      '1 lata de atún guisado a la mexicana (jitomate, cebolla, cilantro)',
      '2 tortillas de maíz calientes',
      '1 taza de col rallada con zanahoria y limón',
    ],
    instructions: [
      'Rellena las tortillas con el atún guisado y dobla en forma de quesadilla/taco.',
      'Dora en comal caliente a fuego medio-bajo sin aceite hasta que queden crujientes y doraditas.',
      'Acompaña con la ensalada de col fresca aderezada con limón y sal.',
    ],
    approxCalories: 360,
    approxProteinGrams: 30,
  },
  {
    id: 'rec_com_7',
    title: 'Cochinita Pibil Ligera con Frijoles de la Olla y Ensalada',
    mealType: 'lunch',
    prepTimeMinutes: 15,
    isBudgetFriendly: true,
    ingredients: [
      '120g de carne magra de cerdo o pechuga cocida en achiote y naranja',
      '1/2 taza de frijoles de la olla enteros',
      'Cebolla morada curtida con limón y orégano',
      '1 taza de ensalada verde fresca',
    ],
    instructions: [
      'Deshebra la carne sazonada en achiote con toque de orégano y naranja agria.',
      'Sirve con 1/2 taza de frijoles de la olla calientes y la ensalada verde.',
      'Corona con cebollita morada curtida.',
    ],
    approxCalories: 400,
    approxProteinGrams: 33,
  },
  {
    id: 'rec_com_8',
    title: 'Fajitas de Pollo con Pimientos, Calabacita y Tortillas',
    mealType: 'lunch',
    prepTimeMinutes: 15,
    isBudgetFriendly: true,
    ingredients: [
      '130g de pechuga de pollo en tiras',
      '1/2 pimiento y 1 calabacita en julianas',
      '1/4 de cebolla',
      '2 tortillas de maíz',
      '1 cucharadita de aceite para saltear',
    ],
    instructions: [
      'Saltea las fajitas de pollo con la cebolla, el pimiento y la calabacita con ajo en polvo y sal.',
      'Cocina tapado por 6 minutos hasta que los vegetales estén al dente y el pollo dorado.',
      'Arma tus taquitos con las 2 tortillas calientes.',
    ],
    approxCalories: 370,
    approxProteinGrams: 33,
  },
  {
    id: 'rec_com_9',
    title: 'Sopa de Lentejas Caseras con Verduras y Tortillas',
    mealType: 'lunch',
    prepTimeMinutes: 18,
    isBudgetFriendly: true,
    ingredients: [
      '1 taza y media de lentejas cocidas en su caldo',
      '1 zanahoria y 1 calabacita picadas en cubitos',
      '1 jitomate licuado con ajo y cebolla',
      '2 tortillas de maíz calientes',
    ],
    instructions: [
      'Sofríe el recaudo de jitomate con una pizca de orégano.',
      'Agrega las lentejas con su caldo, la zanahoria y la calabacita.',
      'Hierve 8 minutos hasta que los vegetales estén suaves.',
      'Sirve caliente acompañado de las tortillas y limón al gusto.',
    ],
    approxCalories: 350,
    approxProteinGrams: 20,
  },
  {
    id: 'rec_com_10',
    title: 'Tacos de Champiñones al Ajillo con Frijoles de la Olla',
    mealType: 'lunch',
    prepTimeMinutes: 12,
    isBudgetFriendly: true,
    ingredients: [
      '1 taza y media de champiñones rebanados',
      '1 diente de ajo picado y 1 chile guajillo en aros',
      '1 cucharadita de aceite',
      '2 tortillas de maíz',
      '1/2 taza de frijoles de la olla calientes',
    ],
    instructions: [
      'Saltea el ajo y chile guajillo en sartén con la cucharadita de aceite por 30 segundos.',
      'Agrega los champiñones con sal al gusto y cocina a fuego alto por 4 minutos.',
      'Sirve en tacos sobre las tortillas calientes con los frijoles de la olla.',
    ],
    approxCalories: 320,
    approxProteinGrams: 14,
  },
  // Comidas Institucionales NUTRIMSS 2024 (SMAE 5ª Edición)
  {
    id: 'rec_com_11',
    title: 'Alambre de Res con Sopa de Fideo con Brócoli y Frijoles',
    mealType: 'lunch',
    prepTimeMinutes: 18,
    isBudgetFriendly: true,
    ingredients: [
      '60g de carne de res magra en fajitas',
      '1 taza de verduras mixtas (pimiento, cebolla, calabacita)',
      '1/2 taza de sopa de fideo cocido con 1/2 taza de brócoli',
      '1/2 taza de frijoles caldosos',
      '2 tortillas de maíz',
      '2 cucharaditas de aceite común',
    ],
    instructions: [
      'Prepara la sopa de fideo con caldillo de jitomate y brócoli cocido al gusto.',
      'Saltea la carne de res con las verduras mixtas en sartén caliente con el aceite.',
      'Sirve acompañado de 1/2 taza de frijoles caldosos y las 2 tortillas de maíz calientes.',
    ],
    approxCalories: 430,
    approxProteinGrams: 28,
  },
  {
    id: 'rec_com_12',
    title: 'Pescado Empapelado con Sopa de Verduras, Arroz y Alubias',
    mealType: 'lunch',
    prepTimeMinutes: 20,
    isBudgetFriendly: true,
    ingredients: [
      '80g de filete de pescado blanco (tilapia, cazón o merluza)',
      '1/2 taza de verduras mixtas para empapelar (calabacita, zanahoria, jitomate)',
      '1 taza de sopa de verduras mixtas en caldo claro',
      '1/4 de taza de arroz rojo cocido',
      '1/2 taza de alubias caldosas',
      '2 tortillas de maíz',
      '2 cucharaditas de aceite',
    ],
    instructions: [
      'Coloca el filete sobre papel aluminio con las verduras en juliana, gotitas de limón, aceite, sal y hierbas finas; sella y cocina en comal 10 minutos.',
      'Sirve con la sopa de verduras caliente, el arroz rojo, las alubias y 2 tortillas.',
    ],
    approxCalories: 420,
    approxProteinGrams: 30,
  },
  {
    id: 'rec_com_13',
    title: 'Tacos de Carne Asada con Sopa de Moñito y Frijoles',
    mealType: 'lunch',
    prepTimeMinutes: 16,
    isBudgetFriendly: true,
    ingredients: [
      '60g de bistec de res asado al comal',
      '1/2 taza de pasta de moñito cocida con 1 taza de verduras en caldo',
      '1 taza de pico de gallo fresco',
      '1/3 de pieza de aguacate',
      '1/2 taza de frijoles caldosos',
      '2 tortillas de maíz',
      '1 cucharadita de aceite',
    ],
    instructions: [
      'Prepara la sopa de pasta de moñito con caldillo de jitomate y verduras al gusto.',
      'Asa el bistec en comal con sal y pimienta.',
      'Arma 2 tacos con aguacate y abundante pico de gallo, acompañando con los frijoles caldosos.',
    ],
    approxCalories: 440,
    approxProteinGrams: 27,
  },
  {
    id: 'rec_com_14',
    title: 'Pollo en Salsa Verde con Nopales y Sopa Poblana',
    mealType: 'lunch',
    prepTimeMinutes: 18,
    isBudgetFriendly: true,
    ingredients: [
      '60g de pieza o pechuga de pollo sin piel',
      '1 taza de nopales picados cocidos',
      'Salsa verde casera al gusto',
      'Sopa poblana: 1/2 taza de rajas de poblano, 1/2 taza de champiñones y 1/2 taza de elote en caldo',
      '1/2 taza de frijoles caldosos',
      '2 tortillas de maíz',
      '2 cucharaditas de aceite',
    ],
    instructions: [
      'Hierve los ingredientes de la sopa poblana en caldo sazonado con cebolla, ajo y epazote.',
      'Guisar el pollo con los nopales y la salsa verde caliente.',
      'Sirve con 2 tortillas de maíz y frijoles caldosos.',
    ],
    approxCalories: 420,
    approxProteinGrams: 29,
  },
  {
    id: 'rec_com_15',
    title: 'Carne de Cerdo en Salsa Morita con Consomé de Garbanzo',
    mealType: 'lunch',
    prepTimeMinutes: 20,
    isBudgetFriendly: true,
    ingredients: [
      '70g de maciza de cerdo magra en trozos',
      'Salsa morita con especias al gusto',
      'Consomé con 1 taza de verduras mixtas, 1/2 taza de garbanzo cocido y 1/4 taza de arroz',
      '2 tortillas de maíz',
      '2 cucharaditas de aceite',
    ],
    instructions: [
      'Cuece y dora la maciza de cerdo con salsa morita.',
      'Prepara el consomé caliente con las verduras, garbanzos y arroz.',
      'Sirve acompañado de 2 tortillas de maíz calientes.',
    ],
    approxCalories: 440,
    approxProteinGrams: 30,
  },
  {
    id: 'rec_com_16',
    title: 'Fajitas de Pollo con Pimientos, Frijoles y Sopa de Espinacas',
    mealType: 'lunch',
    prepTimeMinutes: 15,
    isBudgetFriendly: true,
    ingredients: [
      '60g de pechuga de pollo en tiras',
      '1 taza de pimiento rojo y cebolla en julianas',
      '1/2 taza de pasta cocida con 1/2 taza de espinaca en caldo claro',
      '1/2 taza de frijoles caldosos',
      '2 tortillas de maíz',
      '1 cucharadita de aceite',
    ],
    instructions: [
      'Hierve la pasta con la espinaca y recaudo ligero.',
      'Saltea las fajitas de pollo con pimiento y cebolla con la cucharadita de aceite.',
      'Acompaña con 2 tortillas de maíz y frijoles caldosos de la olla.',
    ],
    approxCalories: 410,
    approxProteinGrams: 28,
  },
  {
    id: 'rec_com_17',
    title: 'Picadillo Casero de Res con Sopa de Lentejas y Acelgas',
    mealType: 'lunch',
    prepTimeMinutes: 20,
    isBudgetFriendly: true,
    ingredients: [
      '60g de pulpa de res molida magra',
      '1 taza de verduras picadas (zanahoria, chayote, calabacita, jitomate)',
      '1/2 taza de lentejas cocidas con 1/2 taza de acelga en caldo',
      '3 tortillas de maíz',
      '1 cucharadita de aceite',
    ],
    instructions: [
      'Sofríe la carne molida con las verduras picadas y recaudo de jitomate hasta que esté cocido.',
      'Calienta la sopa de lentejas con acelga fresca picada.',
      'Disfruta con 3 tortillas de maíz calientes.',
    ],
    approxCalories: 430,
    approxProteinGrams: 29,
  },
  {
    id: 'rec_com_18',
    title: 'Pollo con Verdolagas en Salsa Verde y Sopa de Alubias',
    mealType: 'lunch',
    prepTimeMinutes: 18,
    isBudgetFriendly: true,
    ingredients: [
      '60g de pollo sin piel cocido',
      '1 taza de verdolagas limpias',
      'Salsa verde al gusto',
      '1/2 taza de alubias caldosas',
      '1/4 de taza de arroz rojo',
      '2 tortillas de maíz',
      '1 cucharadita de aceite',
    ],
    instructions: [
      'Guisar el pollo con las verdolagas en la salsa verde por 8 minutos a fuego medio.',
      'Sirve caliente con la sopa de alubias caldosas, el arroz rojo y las 2 tortillas de maíz.',
    ],
    approxCalories: 410,
    approxProteinGrams: 28,
  },
  {
    id: 'rec_com_19',
    title: 'Bistec a la Mexicana con Arroz de Verduras y Aguacate',
    mealType: 'lunch',
    prepTimeMinutes: 15,
    isBudgetFriendly: true,
    ingredients: [
      '60g de bistec de res en tiritas',
      '1 taza de pico de gallo para guisar',
      '1/4 de taza de arroz con 1/2 taza de zanahoria y chícharos',
      '1/3 de pieza de aguacate',
      '2 tortillas de maíz',
      '1 cucharadita de aceite',
    ],
    instructions: [
      'Saltea el bistec con el jitomate, cebolla y chile serrano hasta dorar.',
      'Sirve con la guarnición de arroz y verduras, rebanadas de aguacate y 2 tortillas de maíz.',
    ],
    approxCalories: 420,
    approxProteinGrams: 27,
  },
  {
    id: 'rec_com_20',
    title: 'Fideo Seco al Frijol y Morita con Pescado a la Plancha',
    mealType: 'lunch',
    prepTimeMinutes: 16,
    isBudgetFriendly: true,
    ingredients: [
      '80g de filete de pescado a la plancha',
      '1 taza de verduras mixtas al vapor',
      '1/2 taza de fideo seco guisado en 1/2 taza de caldo de frijol con chile morita',
      '1/3 de pieza de aguacate',
      '2 tortillas de maíz',
      '1 cucharadita de aceite',
    ],
    instructions: [
      'Dora el fideo y cocínalo con salsa licuada de frijoles caldosos y chile morita.',
      'Dora el filete de pescado a la plancha sazonado con ajo y limón.',
      'Sirve con verduras al vapor, aguacate y 2 tortillas.',
    ],
    approxCalories: 410,
    approxProteinGrams: 30,
  },
  {
    id: 'rec_com_21',
    title: 'Pollo a la Parrilla con Ensalada Abundante y Arroz',
    mealType: 'lunch',
    prepTimeMinutes: 15,
    isBudgetFriendly: true,
    ingredients: [
      '60g de pechuga de pollo a la plancha',
      '1 taza y media de lechugas mixtas con 1/4 de taza de zanahoria rallada',
      '1/4 de taza de arroz cocido',
      '2 tortillas de maíz',
      '2 cucharaditas de aceite',
    ],
    instructions: [
      'Marina el pollo con limón, sal y orégano; asa en sartén caliente.',
      'Acompaña con el arroz cocido, la ensalada fresca aderezada con limón y 2 tortillas calientes.',
    ],
    approxCalories: 390,
    approxProteinGrams: 28,
  },
  {
    id: 'rec_com_22',
    title: 'Cerdo Magro en Salsa Pasilla con Nopales y Sopa de Verduras',
    mealType: 'lunch',
    prepTimeMinutes: 18,
    isBudgetFriendly: true,
    ingredients: [
      '60g de carne de cerdo magra',
      '1 taza de nopales cocidos en salsa pasilla',
      '1 taza de verduras mixtas en sopa clara',
      '1/4 de taza de arroz rojo',
      '1/2 taza de frijoles caldosos',
      '1/3 de pieza de aguacate',
      '2 tortillas de maíz',
      '1 cucharadita de aceite',
    ],
    instructions: [
      'Cocina el cerdo con los nopales en salsa pasilla casera.',
      'Sirve con la sopa de verduras, arroz rojo, frijoles caldosos, aguacate y 2 tortillas.',
    ],
    approxCalories: 420,
    approxProteinGrams: 28,
  },
  {
    id: 'rec_com_23',
    title: 'Ceviche de Pescado con Pico de Gallo, Aguacate y Tostadas',
    mealType: 'lunch',
    prepTimeMinutes: 12,
    isBudgetFriendly: true,
    ingredients: [
      '80g de filete de pescado picado en cubos',
      '1 taza de pico de gallo (jitomate, cebolla, cilantro y pepino)',
      'Jugo de 2 limones y sal al gusto',
      '2/3 de pieza de aguacate',
      '6 tostadas de maíz horneadas sin grasa',
    ],
    instructions: [
      'Cura el pescado picado con jugo de limón por 10 minutos.',
      'Mezcla con el pico de gallo y sazona con sal y orégano.',
      'Monta sobre las tostadas horneadas con rebanadas de aguacate.',
    ],
    approxCalories: 370,
    approxProteinGrams: 28,
  },
  {
    id: 'rec_com_24',
    title: 'Caldo de Hongos y Setas con Pollo, Garbanzo y Epazote',
    mealType: 'lunch',
    prepTimeMinutes: 16,
    isBudgetFriendly: true,
    ingredients: [
      '60g de pierna o pechuga de pollo sin piel deshebrada',
      '1/2 taza de hongos o setas cocidas',
      '1/2 taza de garbanzo cocido',
      'Caldo sazonado con jitomate, chile guajillo, epazote, ajo y cebolla',
      '3 tortillas de maíz',
      '2 cucharaditas de aceite',
    ],
    instructions: [
      'Hierve el caldo con los garbanzos, setas, pollo y chile guajillo con una rama de epazote.',
      'Sirve bien caliente en tazón hondo acompañado de 3 tortillas de maíz.',
    ],
    approxCalories: 400,
    approxProteinGrams: 29,
  },
  {
    id: 'rec_com_25',
    title: 'Calabacitas Rellenas de Queso Panela con Caldo de Haba',
    mealType: 'lunch',
    prepTimeMinutes: 18,
    isBudgetFriendly: true,
    ingredients: [
      '2 calabacitas medianas cocidas y ahuecadas',
      '80g de queso panela',
      'Caldo de haba con 1/2 taza de haba seca cocida, jitomate y nopales',
      '1/4 de taza de arroz rojo',
      '2 tortillas de maíz',
      '1 cucharadita de aceite',
    ],
    instructions: [
      'Prepara el caldo de haba con jitomate, cebolla, cilantro y nopales picados.',
      'Rellena las calabacitas con el queso panela y dora en sartén tapado.',
      'Sirve con el arroz rojo, caldo de haba y 2 tortillas de maíz.',
    ],
    approxCalories: 410,
    approxProteinGrams: 24,
  },
  {
    id: 'rec_com_26',
    title: 'Caldo de Res con Verduras Mixtas y Sopa de Lentejas',
    mealType: 'lunch',
    prepTimeMinutes: 20,
    isBudgetFriendly: true,
    ingredients: [
      '50g de maciza de res magra cocida',
      '1 taza de verduras mixtas (calabacita, elote, zanahoria, col)',
      '1/2 taza de lentejas cocidas con acelga en caldo',
      '3 tortillas de maíz',
      '1 cucharadita de aceite',
    ],
    instructions: [
      'Sirve el caldo de res con verduras tiernas y sazón de cilantro y hierbabuena.',
      'Acompaña con la sopa de lentejas caldosa y 3 tortillas de maíz con limón.',
    ],
    approxCalories: 430,
    approxProteinGrams: 27,
  },
  {
    id: 'rec_com_27',
    title: 'Estofado Casero de Pollo con Papa, Zanahoria y Frijoles',
    mealType: 'lunch',
    prepTimeMinutes: 18,
    isBudgetFriendly: true,
    ingredients: [
      '60g de pollo sin piel (pierna o pechuga)',
      '1/2 pieza de papa cocida en cubos',
      '1/4 de taza de zanahoria en rodajas',
      'Pimiento rojo al gusto en caldillo de jitomate',
      '1/2 taza de frijoles caldosos',
      '2 tortillas de maíz',
      '2 cucharaditas de aceite',
    ],
    instructions: [
      'Estofa el pollo en caldillo de jitomate sazonado con laurel, orégano, papa y zanahoria.',
      'Sirve caliente con los frijoles caldosos y 2 tortillas de maíz.',
    ],
    approxCalories: 410,
    approxProteinGrams: 28,
  },
  {
    id: 'rec_com_28',
    title: 'Espagueti Casero con Champiñones, Pollo y Pomodoro',
    mealType: 'lunch',
    prepTimeMinutes: 15,
    isBudgetFriendly: true,
    ingredients: [
      '1 taza de espagueti cocido al dente',
      '1/2 taza de champiñones rebanados',
      '30g de pechuga de pollo deshebrada',
      '40g de queso panela rallado',
      'Salsa de 2 jitomates licuados con orégano y ajo',
      '2 cucharaditas de aceite',
    ],
    instructions: [
      'Saltea los champiñones y el pollo con el puré de jitomate natural y aceite.',
      'Mezcla con el espagueti caliente y espolvorea el queso panela rallado encima.',
    ],
    approxCalories: 390,
    approxProteinGrams: 22,
  },
  {
    id: 'rec_com_29',
    title: 'Carne de Cerdo en Adobo con Sopa de Frijol y Acelgas',
    mealType: 'lunch',
    prepTimeMinutes: 20,
    isBudgetFriendly: true,
    ingredients: [
      '60g de maciza de cerdo',
      'Salsa de adobo de chiles guajillo y ancho con especias',
      '1/2 taza de frijoles cocidos con 1/2 taza de acelga picada en caldo',
      '3 tortillas de maíz',
      '2 cucharaditas de aceite',
    ],
    instructions: [
      'Guisar la carne de cerdo en el adobo casero hasta que espese y esté suave.',
      'Calienta la sopa de frijoles con acelgas y sirve con 3 tortillas de maíz calientes.',
    ],
    approxCalories: 430,
    approxProteinGrams: 28,
  },
  {
    id: 'rec_com_30',
    title: 'Salpicón de Res con Tostadas Horneadas, Arroz y Frijoles',
    mealType: 'lunch',
    prepTimeMinutes: 14,
    isBudgetFriendly: true,
    ingredients: [
      '60g de carne de res cocida y deshebrada',
      '1 taza de lechuga, jitomate y cebolla en julianas con vinagre y orégano',
      '1/4 de taza de arroz con 1/2 taza de zanahoria y chícharos',
      '1/3 de taza de frijoles machacados',
      '1/3 de pieza de aguacate',
      '4 tostadas de maíz horneadas',
      '1 cucharadita de aceite',
    ],
    instructions: [
      'Mezcla la carne deshebrada con las verduras, vinagre blanco, orégano, sal y pimienta.',
      'Unta los frijoles sobre las tostadas, monta el salpicón con aguacate y acompaña con el arroz.',
    ],
    approxCalories: 410,
    approxProteinGrams: 29,
  },
  {
    id: 'rec_com_31',
    title: 'Sopa Estilo Oriental de Pollo con Champiñones y Cacahuates',
    mealType: 'lunch',
    prepTimeMinutes: 16,
    isBudgetFriendly: true,
    ingredients: [
      '60g de pechuga de pollo deshebrada',
      '2 tazas de champiñones y cebollitas cambray',
      '14 piezas de cacahuates naturales tostados',
      '1/2 taza de frijoles cocidos',
      '3 tortillas de maíz',
      '1 cucharadita de aceite, ajo y chile de árbol al gusto',
    ],
    instructions: [
      'Saltea las cebollitas y champiñones con ajo y chile de árbol.',
      'Agrega caldo claro, pollo deshebrado y corona con cacahuates tostados crujientes.',
      'Acompaña con frijoles y 3 tortillas de maíz.',
    ],
    approxCalories: 420,
    approxProteinGrams: 29,
  },
  {
    id: 'rec_com_32',
    title: 'Albóndigas de Pollo en Caldillo Rojo con Verduras y Papa',
    mealType: 'lunch',
    prepTimeMinutes: 20,
    isBudgetFriendly: true,
    ingredients: [
      '60g de pechuga de pollo molida',
      '1/2 pieza de papa en cubos',
      '1 taza de zanahoria, calabacita y chayote en cubos',
      'Salsa roja de jitomate con ajo y comino',
      '1/2 taza de frijoles caldosos',
      '2 tortillas de maíz',
      '2 cucharaditas de aceite',
    ],
    instructions: [
      'Forma las albóndigas con la pechuga molida sazonada.',
      'Cocina en el caldillo de jitomate hirviendo con las verduras y la papa por 15 minutos.',
      'Sirve caliente con frijoles caldosos y 2 tortillas de maíz.',
    ],
    approxCalories: 410,
    approxProteinGrams: 28,
  },
  {
    id: 'rec_com_33',
    title: 'Alambre de Pollo con Pimientos, Arroz y Sopa de Lentejas',
    mealType: 'lunch',
    prepTimeMinutes: 16,
    isBudgetFriendly: true,
    ingredients: [
      '60g de fajitas de pechuga de pollo',
      '1 taza de pimientos y cebolla picada',
      '1/4 de taza de arroz blanco cocido',
      '1/2 taza de sopa de lentejas con acelgas',
      '2 tortillas de maíz',
      '1 cucharadita de aceite',
    ],
    instructions: [
      'Saltea el pollo con los pimientos y cebolla hasta dorar.',
      'Sirve con el arroz blanco, la sopa de lentejas caliente y 2 tortillas de maíz.',
    ],
    approxCalories: 410,
    approxProteinGrams: 29,
  },
  {
    id: 'rec_com_34',
    title: 'Bistec Encebollado con Ensalada Mixta y Aguacate',
    mealType: 'lunch',
    prepTimeMinutes: 14,
    isBudgetFriendly: true,
    ingredients: [
      '60g de bistec de res',
      '1/2 cebolla rebanada caramelizada al sartén',
      '1 taza de ensalada mixta de verduras frescas con limón',
      '1/3 de pieza de aguacate',
      '3 tortillas de maíz',
      '1 cucharadita de aceite',
    ],
    instructions: [
      'Dora la cebolla en sartén con el aceite y agrega el bistec sazonado hasta el término deseado.',
      'Sirve con la ensalada mixta, rebanadas de aguacate y 3 tortillas de maíz.',
    ],
    approxCalories: 420,
    approxProteinGrams: 27,
  },
  {
    id: 'rec_com_35',
    title: 'Trucha al Comal con Ejotes al Vapor, Aceitunas y Arroz',
    mealType: 'lunch',
    prepTimeMinutes: 15,
    isBudgetFriendly: true,
    ingredients: [
      '60g de filete de trucha o pescado fresco',
      '1/2 taza de ejote cocido al vapor',
      '5 piezas de aceitunas sin hueso',
      '1/4 de taza de arroz blanco',
      '1/3 de pieza de aguacate',
      '1/2 taza de frijoles caldosos',
      '2 tortillas de maíz',
    ],
    instructions: [
      'Asa la trucha al comal sazonada con ajo y limón.',
      'Sirve con ejotes al vapor, aceitunas rebanadas, arroz blanco, frijoles caldosos y tortillas.',
    ],
    approxCalories: 400,
    approxProteinGrams: 27,
  },
  {
    id: 'rec_com_36',
    title: 'Chuleta de Cerdo Magra en Salsa Verde con Nopales',
    mealType: 'lunch',
    prepTimeMinutes: 16,
    isBudgetFriendly: true,
    ingredients: [
      '1 pieza de chuleta de cerdo magra sin grasa (no ahumada)',
      '1 taza de nopales guisados',
      'Salsa verde casera al gusto',
      '1/2 taza de frijoles caldosos',
      '3 tortillas de maíz',
      '2 cucharaditas de aceite',
    ],
    instructions: [
      'Sella la chuleta en sartén y añade la salsa verde con los nopales.',
      'Deja hervir 6 minutos a fuego medio y sirve con frijoles caldosos y 3 tortillas calientes.',
    ],
    approxCalories: 430,
    approxProteinGrams: 30,
  },
  {
    id: 'rec_com_37',
    title: 'Pozole Ligero de Pollo con Tostadas Horneadas y Frijoles',
    mealType: 'lunch',
    prepTimeMinutes: 18,
    isBudgetFriendly: true,
    ingredients: [
      '60g de pechuga de pollo deshebrada',
      '1/3 de taza de maíz pozolero cocido en caldo sazonado con orégano',
      '1 taza de lechuga y rábanos picados',
      '1/3 de pieza de aguacate',
      '4 tostadas de maíz horneadas con 1/3 taza de frijoles machacados',
    ],
    instructions: [
      'Sirve el caldo de pozole caliente con el maíz y pechuga de pollo deshebrada.',
      'Agrega abundante lechuga, rábanos y orégano.',
      'Acompaña con tostadas horneadas untadas con frijol y aguacate.',
    ],
    approxCalories: 390,
    approxProteinGrams: 28,
  },
  {
    id: 'rec_com_38',
    title: 'Nopales Rellenos de Atún y Queso en Salsa Pasilla',
    mealType: 'lunch',
    prepTimeMinutes: 20,
    isBudgetFriendly: true,
    ingredients: [
      '2 nopales medianos asados',
      '1 lata de atún en agua (drenado)',
      '40g de queso panela o fresco',
      'Pico de gallo (jitomate, cebolla, chile serrano, cilantro)',
      'Salsa pasilla casera (tomate verde, chile pasilla, ajo y cebolla)',
      '1/3 de taza de frijoles cocidos',
      '1 cucharadita de aceite vegetal',
      '1 tortilla de maíz',
    ],
    instructions: [
      'Asa los nopales en comal con unas gotas de aceite y ábrelos por la mitad.',
      'Mezcla el atún drenado, el queso panela y el pico de gallo para formar el relleno.',
      'Rellena los nopales asados.',
      'Licúa los tomates asados con el chile pasilla hidratado, ajo y cebolla para la salsa.',
      'Baña los nopales con la salsa pasilla caliente y sirve con frijoles cocidos y tortilla.',
    ],
    approxCalories: 380,
    approxProteinGrams: 24,
  },
  {
    id: 'rec_com_39',
    title: 'Tostadas de Pollo Deshebrado con Verduras al Vapor',
    mealType: 'lunch',
    prepTimeMinutes: 15,
    isBudgetFriendly: true,
    ingredients: [
      '2 tostadas de maíz horneadas',
      '90g de pechuga de pollo deshebrada cocida',
      '1/3 de taza de frijoles refritos caseros (sin manteca)',
      '1 taza de verduras al vapor (brócoli, zanahoria, pimiento y champiñón)',
      'Tiras de lechuga fresca',
      '1 cucharadita de aceite de oliva',
      'Sal y pimienta al gusto',
    ],
    instructions: [
      'Unta los frijoles refritos sobre las tostadas horneadas.',
      'Mezcla el pollo deshebrado con las verduras al vapor aderezadas con aceite de oliva y sal.',
      'Coloca la mezcla sobre las tostadas y decora con lechuga fresca al gusto.',
    ],
    approxCalories: 370,
    approxProteinGrams: 23,
  },
  {
    id: 'rec_com_40',
    title: 'Tacos de Pescado a la Plancha con Pico de Gallo y Repollo',
    mealType: 'lunch',
    prepTimeMinutes: 15,
    isBudgetFriendly: true,
    ingredients: [
      '100g de filete de pescado fresco en tiras',
      '2 tortillas de maíz',
      '1 taza de repollo/col rebanado y zanahoria rallada',
      'Pico de gallo (jitomate, cebolla blanca, chile, cilantro, limón)',
      '1 cucharadita de aceite vegetal',
      'Sal y pimienta al gusto',
    ],
    instructions: [
      'Sazona las tiras de pescado con sal, pimienta y gotas de limón.',
      'Dóralas en sartén con una cucharadita de aceite a fuego medio hasta cocinar bien.',
      'Calienta las tortillas de maíz y arma los tacos.',
      'Acompaña con la ensalada de repollo, zanahoria y el pico de gallo fresco.',
    ],
    approxCalories: 360,
    approxProteinGrams: 24,
  },
  {
    id: 'rec_com_41',
    title: 'Albóndigas de Pescado en Caldillo de Verduras',
    mealType: 'lunch',
    prepTimeMinutes: 20,
    isBudgetFriendly: true,
    ingredients: [
      '100g de filete de pescado molido',
      '1 huevo (para amalgamar)',
      'Caldillo de jitomate, cebolla, chile poblano, ajo y orégano',
      '1/2 taza de verduras (zanahoria, chayote, calabacita y chícharos)',
      '1 cucharadita de aceite vegetal',
      '2 tortillas de maíz',
      'Sal y pimienta al gusto',
    ],
    instructions: [
      'Mezcla el pescado molido con huevo, cebolla picada, orégano, sal y pimienta; forma albóndigas pequeñas.',
      'Sofreíe el ajo, cebolla, jitomate y chile poblano en el aceite, añade agua y deja hervir.',
      'Agrega las verduras según su dureza (zanahoria primero, calabacita al final) y añade las albóndigas.',
      'Cocina a fuego medio hasta que las albóndigas estén cocidas y sirve con tortillas.',
    ],
    approxCalories: 380,
    approxProteinGrams: 25,
  },
  {
    id: 'rec_com_42',
    title: 'Pacholas Hidrocálidas de Res Magra con Ensalada',
    mealType: 'lunch',
    prepTimeMinutes: 15,
    isBudgetFriendly: true,
    ingredients: [
      '120g de carne molida magra de res',
      '1 chile ancho rehidratado y desvenado',
      '1 diente de ajo picado y pizca de comino',
      '1 cucharadita de aceite vegetal',
      '1 taza de ensalada fresca (lechuga, jitomate y pepino)',
      '2 tortillas de maíz',
      'Sal y pimienta al gusto',
    ],
    instructions: [
      'Muele o mezcla el chile ancho rehidratado con el ajo, comino, sal y la carne molida de res.',
      'Forma bistecs delgados (pacholas) presionando entre plásticos ligeros.',
      'Asa las pacholas en sartén caliente con la cucharadita de aceite por 3 minutos por lado.',
      'Sirve acompañado de la ensalada fresca y las tortillas de maíz calientes.',
    ],
    approxCalories: 350,
    approxProteinGrams: 28,
  },
  {
    id: 'rec_com_43',
    title: 'Pollo en Salsa de Guayaba Natural y Pimiento',
    mealType: 'lunch',
    prepTimeMinutes: 15,
    isBudgetFriendly: true,
    ingredients: [
      '120g de filete de pechuga de pollo',
      '2 guayabas maduras licuadas y coladas',
      '1/2 pimiento rojo picado',
      '1/4 de cebolla y 1 diente de ajo finamente picados',
      '1 cucharadita de mantequilla o aceite de oliva',
      'Hojas de lechuga fresca para acompañar',
      '1/2 taza de arroz blanco cocido o frijoles de la olla',
      'Sal y pimienta al gusto',
    ],
    instructions: [
      'Sazona el pollo con sal, pimienta y ajo.',
      'Sofreíe la cebolla, el ajo y el pimiento rojo en la mantequilla o aceite de oliva.',
      'Agrega las piezas de pollo y vierte la salsa de guayaba natural colada.',
      'Tapa y cocina a fuego medio durante 8 a 10 minutos hasta reducir la salsa.',
      'Sirve decorado con lechuga fresca y acompañado de arroz blanco o frijoles.',
    ],
    approxCalories: 340,
    approxProteinGrams: 27,
  },
  {
    id: 'rec_com_44',
    title: 'Ceviche Fresco de Pescado a la Limeña',
    mealType: 'lunch',
    prepTimeMinutes: 15,
    isBudgetFriendly: true,
    ingredients: [
      '120g de filete de pescado blanco fresco en cubos',
      'Jugo de 4 limones frescos',
      '1/2 jitomate picado en cubos',
      '1/4 de cebolla picada',
      '1/2 pepino picado sin semillas',
      '1 chile jalapeño picado y cilantro fresco',
      '1/4 de aguacate rebanado',
      '2 tostadas de maíz horneadas',
      'Sal y pimienta al gusto',
    ],
    instructions: [
      'Corta el pescado en cubitos y cúbrelo con el jugo de limón, sal y pimienta; deja reposar.',
      'Incorpora el jitomate, pepino, cebolla, chile y cilantro al pescado curtido.',
      'Mezcla cuidadosamente y rectifica la sazón.',
      'Sirve sobre las tostadas de maíz horneadas y decora con las rebanadas de aguacate.',
    ],
    approxCalories: 330,
    approxProteinGrams: 25,
  },

  // 3. CENAS
  {
    id: 'rec_cen_1',
    title: 'Quesadillas Ligeras de Maíz con Champiñones y Panela',
    mealType: 'dinner',
    prepTimeMinutes: 8,
    isBudgetFriendly: true,
    ingredients: [
      '2 tortillas de maíz',
      '50g de queso panela o queso fresco desmoronado',
      '1/2 taza de champiñones picados',
    ],
    instructions: [
      'Dora los champiñones en sartén caliente sin aceite por 2 minutos con pizca de sal.',
      'Coloca el queso y los champiñones dentro de las tortillas.',
      'Calienta en el comal hasta que el queso se suavice.',
    ],
    approxCalories: 260,
    approxProteinGrams: 14,
  },
  {
    id: 'rec_cen_2',
    title: 'Sándwich Clásico Casero de Jamón de Pavo y Queso Panela',
    mealType: 'dinner',
    prepTimeMinutes: 5,
    isBudgetFriendly: true,
    ingredients: [
      '2 rebanadas de pan de molde común o integral',
      '2 rebanadas de jamón de pavo',
      '1 rebanada de queso panela',
      'Hojas de lechuga, rodajas de jitomate y mostaza al gusto',
    ],
    instructions: [
      'Unta una capa fina de mostaza en el pan.',
      'Arma el sándwich con el jamón, queso, lechuga y jitomate.',
      'Tuesta ligeramente en sartén si te gusta crujiente.',
    ],
    approxCalories: 270,
    approxProteinGrams: 16,
  },
  {
    id: 'rec_cen_3',
    title: 'Crepa Ligera de Avena con Yogur Natural y Fresas',
    mealType: 'dinner',
    prepTimeMinutes: 10,
    isBudgetFriendly: true,
    ingredients: [
      '3 cucharadas de avena molida licuada con 1 huevo y 3 cdas de agua',
      '3 cucharadas de yogur natural sin azúcar',
      '1/2 taza de fresas rebanadas',
      'Canela en polvo al gusto',
    ],
    instructions: [
      'Vierte la mezcla líquida en sartén antiadherente caliente para formar una crepa delgada.',
      'Cocina 2 minutos por lado a fuego medio.',
      'Rellena con el yogur natural, las fresas frescas y espolvorea canela.',
    ],
    approxCalories: 260,
    approxProteinGrams: 14,
  },
  {
    id: 'rec_cen_4',
    title: 'Mug Cake / Panqué Express de Plátano y Avena',
    mealType: 'dinner',
    prepTimeMinutes: 5,
    isBudgetFriendly: true,
    ingredients: [
      '1/2 plátano maduro machacado',
      '1 huevo entero',
      '3 cucharadas de avena molida',
      '1/4 cucharadita de polvo para hornear',
      'Canela en polvo',
    ],
    instructions: [
      'Machaca el plátano en una taza y bate con el huevo, la avena molida, polvo de hornear y canela.',
      'Lleva al microondas por 1.5 a 2 minutos hasta que esté firme y esponjoso.',
      'Disfruta tibio como una cena ligera y reconfortante.',
    ],
    approxCalories: 270,
    approxProteinGrams: 12,
  },
  {
    id: 'rec_cen_5',
    title: 'Tacos Ligeros de Champiñones al Ajillo con Queso Panela',
    mealType: 'dinner',
    prepTimeMinutes: 8,
    isBudgetFriendly: true,
    ingredients: [
      '2 tortillas de maíz',
      '1 taza de champiñones rebanados',
      '1 diente de ajo picado',
      '40g de queso panela en tiras',
    ],
    instructions: [
      'Saltea los champiñones con el ajo picado y una pizca de sal en sartén sin grasa.',
      'Calienta las tortillas en comal, agrega el queso panela y los champiñones salteados.',
    ],
    approxCalories: 250,
    approxProteinGrams: 13,
  },
  {
    id: 'rec_cen_6',
    title: 'Sopa Reconfortante de Verduras con Pollo Deshebrado',
    mealType: 'dinner',
    prepTimeMinutes: 10,
    isBudgetFriendly: true,
    ingredients: [
      '80g de pechuga de pollo deshebrada',
      '1 taza de caldo claro de verduras con calabacita y chayote',
      '1/4 de aguacate picado',
      'Gotas de limón y cilantro',
    ],
    instructions: [
      'Calienta el caldo con las verduras picadas y el pollo deshebrado.',
      'Sirve caliente en un plato hondo con el aguacate picado y jugo de limón.',
    ],
    approxCalories: 240,
    approxProteinGrams: 22,
  },
  {
    id: 'rec_cen_7',
    title: 'Tostadas Ligeras de Requesón con Ensalada de Nopales',
    mealType: 'dinner',
    prepTimeMinutes: 7,
    isBudgetFriendly: true,
    ingredients: [
      '2 tostadas de maíz horneadas',
      '60g de requesón o queso fresco',
      '1 taza de nopales cocidos o asados con jitomate, cebolla y orégano',
    ],
    instructions: [
      'Unta el requesón sobre las tostadas horneadas.',
      'Corona con la ensalada fresca de nopales sazonada con limón y orégano.',
    ],
    approxCalories: 230,
    approxProteinGrams: 15,
  },
  {
    id: 'rec_cen_8',
    title: 'Ensalada Fresca de Atún con Huevo Cocido y Limón',
    mealType: 'dinner',
    prepTimeMinutes: 6,
    isBudgetFriendly: true,
    ingredients: [
      '1/2 lata de atún en agua escurrida',
      '1 huevo cocido picado en cubitos',
      '1 taza de lechuga, pepino y jitomate picado',
      'Jugo de limón y pizca de sal',
    ],
    instructions: [
      'Mezcla la lechuga, pepino y jitomate en un tazón.',
      'Agrega el atún y el huevo cocido picado.',
      'Adereza con limón y sal para una cena fresca y saciante.',
    ],
    approxCalories: 245,
    approxProteinGrams: 23,
  },
  {
    id: 'rec_cen_9',
    title: 'Ensalada Completa de Garbanzos con Nopales y Limón',
    mealType: 'dinner',
    prepTimeMinutes: 7,
    isBudgetFriendly: true,
    ingredients: [
      '1 taza de garbanzos cocidos escurridos',
      '1 taza de nopales cocidos en cubos',
      '1 jitomate picado y cilantro fresco',
      '1/4 de aguacate en cubos',
      'Jugo de limón y sal al gusto',
    ],
    instructions: [
      'Mezcla en un tazón los garbanzos, nopales, jitomate y cilantro.',
      'Agrega el aguacate en cubos.',
      'Adereza con abundante jugo de limón, sal y orégano molido.',
    ],
    approxCalories: 260,
    approxProteinGrams: 13,
  },
  {
    id: 'rec_cen_10',
    title: 'Sopa Ligera de Frijol de la Olla con Nopales Asados',
    mealType: 'dinner',
    prepTimeMinutes: 8,
    isBudgetFriendly: true,
    ingredients: [
      '1 taza de frijoles de la olla calientes con caldo',
      '1 nopal asado al comal rebanado en tiras',
      '1 tostada de maíz horneada troceada',
      'Cilantro picado y cebollita al gusto',
    ],
    instructions: [
      'Sirve los frijoles bien calientes en un tazón hondo.',
      'Agrega las tiras de nopal asado.',
      'Espolvorea la tostada troceada encima para dar textura crujiente.',
    ],
    approxCalories: 220,
    approxProteinGrams: 11,
  },
  // Cenas Institucionales NUTRIMSS 2024 (SMAE 5ª Edición)
  {
    id: 'rec_cen_11',
    title: 'Ceviche de Atún en Tostadas Horneadas con Piña',
    mealType: 'dinner',
    prepTimeMinutes: 7,
    isBudgetFriendly: true,
    ingredients: [
      '30g de atún en agua escurrido',
      '1 taza de pico de gallo con jugo de limón al gusto',
      '1/3 de pieza de aguacate',
      '4 tostadas de maíz horneadas sin grasa',
      '3/4 de taza de piña picada fresca',
    ],
    instructions: [
      'Mezcla el atún con el pico de gallo, limón y sal al gusto.',
      'Sirve sobre las 4 tostadas horneadas con rebanadas de aguacate encima.',
      'Disfruta con la piña fresca picada.',
    ],
    approxCalories: 260,
    approxProteinGrams: 19,
  },
  {
    id: 'rec_cen_12',
    title: 'Tostadas de Queso Panela con Pico de Gallo y Papaya',
    mealType: 'dinner',
    prepTimeMinutes: 6,
    isBudgetFriendly: true,
    ingredients: [
      '40g de queso panela',
      '1/3 de pieza de aguacate',
      '1 taza de pico de gallo fresco',
      '2 tostadas de maíz horneadas',
      '1 taza de papaya picada',
      '3 cucharadas de granola baja en grasa',
    ],
    instructions: [
      'Coloca las rebanadas de queso panela y aguacate sobre las tostadas horneadas.',
      'Cubre con abundante pico de gallo fresco.',
      'Acompaña con el tazón de papaya picada y granola.',
    ],
    approxCalories: 260,
    approxProteinGrams: 14,
  },
  {
    id: 'rec_cen_13',
    title: 'Nopales Asados al Comal con Panela, Guacamole y Mandarina',
    mealType: 'dinner',
    prepTimeMinutes: 8,
    isBudgetFriendly: true,
    ingredients: [
      '2 piezas de nopal tierno asado al comal',
      '40g de queso panela',
      '2 cucharadas de guacamole casero',
      '2 tortillas de maíz',
      '2 piezas de mandarina',
    ],
    instructions: [
      'Asa los nopales en comal con sal y gratina el queso panela encima.',
      'Sirve con 2 tortillas de maíz calientes y guacamole.',
      'Degusta con 2 mandarinas frescas.',
    ],
    approxCalories: 250,
    approxProteinGrams: 14,
  },
  {
    id: 'rec_cen_14',
    title: 'Omelette Ligero de Claras con Verduras Mixtas y Fresas',
    mealType: 'dinner',
    prepTimeMinutes: 8,
    isBudgetFriendly: true,
    ingredients: [
      '2 claras de huevo',
      '1 taza de verduras mixtas cocidas (champiñón, calabacita, espinaca)',
      '2 tortillas de maíz',
      '1 cucharadita de aceite',
      '1 taza de fresas rebanadas',
    ],
    instructions: [
      'Bate las claras y viértelas en sartén caliente con la cucharadita de aceite.',
      'Rellena con las verduras mixtas y dobla.',
      'Sirve caliente con las tortillas y acompaña con las fresas rebanadas.',
    ],
    approxCalories: 240,
    approxProteinGrams: 16,
  },
  {
    id: 'rec_cen_15',
    title: 'Pan Tostado Integral con Panela, Aguacate y Melón',
    mealType: 'dinner',
    prepTimeMinutes: 6,
    isBudgetFriendly: true,
    ingredients: [
      '2 rebanadas de pan integral tostado',
      '40g de queso panela',
      '1/3 de pieza de aguacate',
      '1 jitomate en rodajas sazonado con orégano y limón',
      '1 taza de melón picado',
    ],
    instructions: [
      'Monta sobre el pan tostado el aguacate machacado, el queso panela y las rodajas de jitomate.',
      'Espolvorea orégano molido y disfruta con el melón picado.',
    ],
    approxCalories: 260,
    approxProteinGrams: 14,
  },
  {
    id: 'rec_cen_16',
    title: 'Sopes Ligeros de Pollo con Ensalada de Nopales y Melón',
    mealType: 'dinner',
    prepTimeMinutes: 10,
    isBudgetFriendly: true,
    ingredients: [
      '2 piezas de sope de maíz al comal',
      '30g de pechuga de pollo deshebrada',
      '1/3 de pieza de aguacate',
      '1 taza de ensalada de nopales cocidos con jitomate y cilantro',
      '1 taza de melón picado',
    ],
    instructions: [
      'Calienta los sopes en comal sin aceite.',
      'Agrega el pollo deshebrado, rebanadas de aguacate y la ensalada de nopales fresca encima.',
      'Acompaña con el melón picado.',
    ],
    approxCalories: 270,
    approxProteinGrams: 17,
  },
  {
    id: 'rec_cen_17',
    title: 'Jitomates Rellenos de Atún, Elote y Aceitunas con Tostadas',
    mealType: 'dinner',
    prepTimeMinutes: 8,
    isBudgetFriendly: true,
    ingredients: [
      '2 piezas de jitomate bola medianos ahuecados',
      '30g de atún en agua escurrido',
      '1/2 taza de elote desgranado cocido',
      '3 piezas de aceitunas picadas y cebolla al gusto',
      '2 tostadas de maíz horneadas',
      '1 taza de sandía picada',
    ],
    instructions: [
      'Mezcla el atún con el elote, la cebolla picada y aceitunas con unas gotas de limón.',
      'Rellena los 2 jitomates y acompáñalos con las tostadas horneadas y sandía fresca.',
    ],
    approxCalories: 260,
    approxProteinGrams: 20,
  },
  {
    id: 'rec_cen_18',
    title: 'Sándwich Ligero de Queso con Espinacas al Vapor y Manzana',
    mealType: 'dinner',
    prepTimeMinutes: 6,
    isBudgetFriendly: true,
    ingredients: [
      '2 rebanadas de pan de caja integral',
      '35g de queso blanco o panela',
      '1/2 taza de espinaca cocida',
      '1/3 de pieza de aguacate',
      '1 manzana fresca',
      '1 taza de leche descremada',
    ],
    instructions: [
      'Arma el sándwich con el queso, espinaca cocida y aguacate; calienta en comal si prefieres.',
      'Acompaña con 1 manzana fresca y 1 vaso de leche descremada.',
    ],
    approxCalories: 270,
    approxProteinGrams: 16,
  },
  {
    id: 'rec_cen_19',
    title: 'Quesadilla de Huitlacoche con Queso Blanco y Toronja',
    mealType: 'dinner',
    prepTimeMinutes: 8,
    isBudgetFriendly: true,
    ingredients: [
      '2 tortillas de maíz',
      '1/2 taza de huitlacoche cocido con cebolla y epazote',
      '35g de queso blanco o panela',
      '1/3 de pieza de aguacate',
      '1 pieza de toronja fresca en gajos',
    ],
    instructions: [
      'Rellena las tortillas con el huitlacoche guisado y el queso blanco.',
      'Calienta en comal hasta que el queso se ablande, añade aguacate y sirve con toronja.',
    ],
    approxCalories: 260,
    approxProteinGrams: 13,
  },
  {
    id: 'rec_cen_20',
    title: 'Tostadas de Picadillo de Res con Ensalada y Naranja',
    mealType: 'dinner',
    prepTimeMinutes: 10,
    isBudgetFriendly: true,
    ingredients: [
      '30g de pulpa de res molida magra guisada con verduras',
      '1/2 taza de verduras picadas (calabaza, chayote, zanahoria)',
      '1 taza de jitomate y cebolla',
      '4 tostadas de maíz horneadas',
      '1 cucharadita de aceite',
      '2 piezas de naranja',
    ],
    instructions: [
      'Calienta el picadillo con las verduritas.',
      'Sirve sobre las tostadas horneadas con jitomate y cebolla picada.',
      'Degusta con 2 naranjas frescas de temporada.',
    ],
    approxCalories: 270,
    approxProteinGrams: 18,
  },
  {
    id: 'rec_cen_21',
    title: 'Tacos Dorados al Comal de Panela con Ensalada Verde',
    mealType: 'dinner',
    prepTimeMinutes: 8,
    isBudgetFriendly: true,
    ingredients: [
      '2 tortillas de maíz',
      '40g de queso panela en tiras',
      '1 taza de lechuga, jitomate y cebolla picada',
      '1 cucharadita de aceite para el comal',
      '1 pieza de toronja fresca',
    ],
    instructions: [
      'Enrolla el queso panela en las tortillas y dora en comal caliente con mínimo aceite hasta que estén crujientes.',
      'Cubre con abundante ensalada verde fresca y come con gajos de toronja.',
    ],
    approxCalories: 250,
    approxProteinGrams: 14,
  },
  {
    id: 'rec_cen_22',
    title: 'Huarache de Nopal con Panela, Aguacate y Té con Galletas',
    mealType: 'dinner',
    prepTimeMinutes: 7,
    isBudgetFriendly: true,
    ingredients: [
      '2 nopales enteros asados al comal',
      '40g de queso panela en rebanadas',
      '1/3 de pieza de aguacate',
      '2 piezas de naranja',
      'Té caliente sin azúcar con 10 galletas marías simples',
    ],
    instructions: [
      'Asa los 2 nopales en el comal con sal y coloca el queso panela y aguacate encima como huarache.',
      'Disfruta con las naranjas y un reconfortante té caliente con galletas marías.',
    ],
    approxCalories: 260,
    approxProteinGrams: 13,
  },
  {
    id: 'rec_cen_23',
    title: 'Chile Poblano Relleno de Atún a la Mexicana con Higos',
    mealType: 'dinner',
    prepTimeMinutes: 10,
    isBudgetFriendly: true,
    ingredients: [
      '1 pieza de chile poblano asado y desvenado',
      '1/3 de lata de atún en agua escurrido',
      'Cebolla y jitomate picado para saltear',
      '1/3 de pieza de aguacate',
      '2 tortillas de maíz',
      '2 piezas de higos frescos',
    ],
    instructions: [
      'Saltea el atún con el jitomate y cebolla.',
      'Rellena el chile poblano y acompáñalo con 2 tortillas calientes, aguacate e higos frescos.',
    ],
    approxCalories: 260,
    approxProteinGrams: 20,
  },
  {
    id: 'rec_cen_24',
    title: 'Chayotes al Horno con Panela, Pan Tostado y Durazno',
    mealType: 'dinner',
    prepTimeMinutes: 10,
    isBudgetFriendly: true,
    ingredients: [
      '1 taza de chayotes cocidos en rebanadas',
      '40g de queso panela',
      '1/3 de pieza de aguacate',
      '1 rebanada de pan tostado integral',
      '2 piezas de durazno amarillo',
      'Té caliente sin azúcar con 5 galletas marías',
    ],
    instructions: [
      'Gratina las rebanadas de chayote con el queso panela en horno o sartén tapado.',
      'Sirve con pan tostado integral y aguacate; finaliza con duraznos y té caliente.',
    ],
    approxCalories: 240,
    approxProteinGrams: 13,
  },
  {
    id: 'rec_cen_25',
    title: 'Queso Panela Asado con Calabacitas y Uvas Frescas',
    mealType: 'dinner',
    prepTimeMinutes: 7,
    isBudgetFriendly: true,
    ingredients: [
      '40g de queso panela en rebanadas gruesas',
      '1 taza de calabacita picada al vapor',
      '1/3 de pieza de aguacate',
      '2 tortillas de maíz',
      '18 piezas de uvas frescas',
    ],
    instructions: [
      'Dora el queso panela y las calabacitas en el comal hasta que tomen color.',
      'Sirve en taquitos con las 2 tortillas de maíz y aguacate; disfruta las uvas de postre.',
    ],
    approxCalories: 260,
    approxProteinGrams: 15,
  },
  {
    id: 'rec_cen_26',
    title: 'Coliflor Rellena de Panela en Salsa Roja con Arroz',
    mealType: 'dinner',
    prepTimeMinutes: 10,
    isBudgetFriendly: true,
    ingredients: [
      '1 taza de ramilletes de coliflor cocida',
      '40g de queso panela',
      'Salsa roja de jitomate hervida',
      '1/4 de taza de arroz blanco cocido',
      '1 tortilla de maíz',
      '1 cucharadita de aceite',
      '1 pieza de toronja fresca',
    ],
    instructions: [
      'Coloca el queso panela entre la coliflor y baña con la salsa de jitomate caliente en sartén.',
      'Sirve con el arroz blanco, 1 tortilla caliente y gajos de toronja fresca.',
    ],
    approxCalories: 250,
    approxProteinGrams: 14,
  },
  {
    id: 'rec_cen_27',
    title: 'Telera Ligera con Aguacate, Panela y Germen de Alfalfa',
    mealType: 'dinner',
    prepTimeMinutes: 6,
    isBudgetFriendly: true,
    ingredients: [
      '2/3 de pieza de telera sin migajón (o pan integral)',
      '40g de queso panela',
      '1/3 de pieza de aguacate',
      '1 jitomate en rodajas',
      'Germen de alfalfa fresco al gusto',
      '1 manzana de temporada',
    ],
    instructions: [
      'Dora el pan y rellénalo con el aguacate, queso panela, jitomate y abundante germen de alfalfa crujiente.',
      'Acompaña con 1 manzana fresca.',
    ],
    approxCalories: 270,
    approxProteinGrams: 15,
  },
  {
    id: 'rec_cen_28',
    title: 'Pan Tostado con Huevo, Calabacita Asada y Mandarina',
    mealType: 'dinner',
    prepTimeMinutes: 8,
    isBudgetFriendly: true,
    ingredients: [
      '2 rebanadas de pan tostado integral',
      '1 huevo a la plancha',
      '1 taza de calabacita asada en rodajas',
      '1/3 de pieza de aguacate',
      'Salsa mexicana casera al gusto',
      '2 piezas de mandarina',
    ],
    instructions: [
      'Monta sobre el pan tostado las calabacitas asadas, el huevo a la plancha y el aguacate.',
      'Baña con salsa mexicana y degusta con 2 mandarinas de temporada.',
    ],
    approxCalories: 260,
    approxProteinGrams: 15,
  },
  {
    id: 'rec_cen_29',
    title: 'Guisado de Calabacitas con Queso Panela y Frijoles de la Olla',
    mealType: 'dinner',
    prepTimeMinutes: 15,
    isBudgetFriendly: true,
    ingredients: [
      '1.5 calabacitas medianas en cubos',
      '1 jitomate picado',
      '1/4 de cebolla y 1 diente de ajo picados',
      '50g de queso panela o fresco en cubos',
      '1/2 taza de frijoles de la olla',
      '1 cucharadita de aceite vegetal',
      '2 tortillas de maíz',
      'Sal al gusto',
    ],
    instructions: [
      'Sofríe el ajo y la cebolla en sartén con el aceite.',
      'Agrega las calabacitas y el jitomate picado; sazona y tapa a fuego lento.',
      'Una vez tiernas las calabazas, incorpora el queso panela desmoronado.',
      'Sirve bien caliente junto con los frijoles de la olla y las 2 tortillas de maíz.',
    ],
    approxCalories: 340,
    approxProteinGrams: 18,
  },
  {
    id: 'rec_cen_30',
    title: 'Sopa Reconfortante de Verduras, Garbanzo y Queso Fresco',
    mealType: 'dinner',
    prepTimeMinutes: 20,
    isBudgetFriendly: true,
    ingredients: [
      '1/2 papa mediana en cubos',
      '1/3 de taza de garbanzos cocidos',
      '1 taza de verduras variadas (zanahoria, chayote, calabacita y chile poblano)',
      '50g de queso fresco en cubos',
      'Suficiente agua, jitomate, cebolla, ajo, cilantro y orégano',
      '1 cucharadita de aceite',
      'Sal y pimienta al gusto',
    ],
    instructions: [
      'Sofríe la cebolla, ajo, jitomate y chile poblano con el aceite en una olla.',
      'Agrega agua potabilizada y lleva a ebullición.',
      'Añade la papa, zanahoria, chayote y calabacita junto con los garbanzos cocidos.',
      'Sazona con sal, pimienta, orégano y cilantro picado.',
      'Sirve el caldo caliente y agrega los cubos de queso fresco al momento.',
    ],
    approxCalories: 350,
    approxProteinGrams: 17,
  },
  {
    id: 'rec_cen_31',
    title: 'Indios Vestidos (Nopales Rellenos de Panela en Caldillo)',
    mealType: 'dinner',
    prepTimeMinutes: 15,
    isBudgetFriendly: true,
    ingredients: [
      '2 pencas de nopal cocidas enteras',
      '60g de queso panela o queso fresco en láminas',
      '2 jitomates maduros',
      '1/4 de cebolla y 1 diente de ajo',
      '1 huevo batido (opcional para capeado ligero)',
      '1 cucharadita de aceite vegetal',
      'Sal, pimienta y orégano al gusto',
    ],
    instructions: [
      'Cuece los nopales enteros en agua con sal y escúrrelos.',
      'Rellena las pencas con el queso panela y dobla a la mitad como quesadillas.',
      'Licúa los jitomates con la cebolla, el ajo, orégano y un chorrito de agua.',
      'Fríe la salsa de jitomate en sartén con el aceite y sazona bien.',
      'Coloca los nopales en la salsa caliente durante 3 minutos y sirve inmediatamente.',
    ],
    approxCalories: 310,
    approxProteinGrams: 18,
  },
  {
    id: 'rec_cen_32',
    title: 'Calabacitas con Caprese Mexicana',
    mealType: 'dinner',
    prepTimeMinutes: 15,
    isBudgetFriendly: true,
    ingredients: [
      '2 calabacitas medianas cocidas al vapor',
      '60g de queso panela en cubitos',
      '1 jitomate picado en cubos',
      '1/4 de chile verde o serrano picado',
      '2 cucharadas de cilantro picado',
      '1 cucharadita de aceite de oliva',
      'Gotas de vinagre balsámico o limón',
      'Sal y pimienta al gusto',
    ],
    instructions: [
      'Parte las calabacitas a lo largo y cuece al vapor sin que queden demasiado suaves.',
      'En un tazón, mezcla el queso panela, el jitomate, el chile, el cilantro, el aceite de oliva, el vinagre, la sal y pimienta.',
      'Rellena las calabacitas al vapor con la mezcla fresca y sirve caliente o tibio.',
    ],
    approxCalories: 280,
    approxProteinGrams: 15,
  },

  // 4. SNACKS (CONTROL DE ANSIEDAD)
  {
    id: 'rec_snk_1',
    title: 'Pepino y Jícama con Limón y Chile Piquín',
    mealType: 'snack',
    prepTimeMinutes: 3,
    isBudgetFriendly: true,
    ingredients: [
      '1 taza de pepino y/o jícama en bastoncitos',
      'Jugo de 1 limón',
      'Sal y chile piquín en polvo sin azúcar',
    ],
    instructions: [
      'Corta el pepino y jícama.',
      'Baña con limón, sal y chile. Alto en agua, fibra y saciedad instantánea.',
    ],
    approxCalories: 45,
    approxProteinGrams: 1,
  },
  {
    id: 'rec_snk_2',
    title: 'Manzana Verde con Puñadito de Cacahuates Tostados',
    mealType: 'snack',
    prepTimeMinutes: 2,
    isBudgetFriendly: true,
    ingredients: [
      '1 manzana pequeña de temporada',
      '15 cacahuates tostados sin sal (o 1 cucharadita de crema de cacahuate)',
    ],
    instructions: [
      'Rebana la manzana y acompaña con los cacahuates para una combinación saciante de fibra y grasa saludable.',
    ],
    approxCalories: 140,
    approxProteinGrams: 4,
  },
  {
    id: 'rec_snk_3',
    title: 'Mini Carlota Saludable Express en Vaso',
    mealType: 'snack',
    prepTimeMinutes: 3,
    isBudgetFriendly: true,
    ingredients: [
      '3 cucharadas de yogur natural o griego sin azúcar',
      'Gotas de jugo de limón y pizca de canela',
      '2 galletas Marías simples troceadas',
      '2 fresas rebanadas',
    ],
    instructions: [
      'Mezcla el yogur con las gotas de limón y canela.',
      'En un vasito intercala una capa de galleta troceada, yogur y decora con fresas.',
    ],
    approxCalories: 115,
    approxProteinGrams: 7,
  },
  {
    id: 'rec_snk_4',
    title: 'Huevo Cocido con Gotitas de Salsa Botanera y Sal',
    mealType: 'snack',
    prepTimeMinutes: 2,
    isBudgetFriendly: true,
    ingredients: [
      '1 huevo cocido entero',
      'Pizca de sal y gotas de limón/salsa casera',
    ],
    instructions: [
      'Pela el huevo cocido, parte a la mitad y sazona con sal, limón y gotitas de salsa picante.',
    ],
    approxCalories: 75,
    approxProteinGrams: 6,
  },
  {
    id: 'rec_snk_5',
    title: 'Bocaditos de Plátano con Canela y Crema de Cacahuate',
    mealType: 'snack',
    prepTimeMinutes: 2,
    isBudgetFriendly: true,
    ingredients: [
      '1/2 plátano en rodajas',
      '1 cucharadita de crema de cacahuate natural sin azúcar',
      'Canela en polvo',
    ],
    instructions: [
      'Coloca las rodajas de plátano, unta una pizca de crema de cacahuate y espolvorea canela.',
    ],
    approxCalories: 120,
    approxProteinGrams: 3,
  },
  {
    id: 'rec_snk_6',
    title: 'Palomitas de Maíz Caseras al Natural con Limón y Chile',
    mealType: 'snack',
    prepTimeMinutes: 5,
    isBudgetFriendly: true,
    ingredients: [
      '1.5 tazas de palomitas de maíz naturales hechas en olla con 3 gotas de aceite',
      'Jugo de limón y chile en polvo sin azúcar',
    ],
    instructions: [
      'Prepara el maíz palomero en olla tapada con mínimo aceite.',
      'Sirve caliente con jugo de limón y chile piquín para una botana con alto volumen y saciedad.',
    ],
    approxCalories: 70,
    approxProteinGrams: 2,
  },
  {
    id: 'rec_snk_7',
    title: 'Vasito de Yogur Griego Natural con Fresas',
    mealType: 'snack',
    prepTimeMinutes: 2,
    isBudgetFriendly: true,
    ingredients: [
      '1/2 taza de yogur griego sin azúcar',
      '1/4 taza de fresas frescas picadas',
      'Canela en polvo',
    ],
    instructions: [
      'Sirve el yogur griego frío en un vaso, agrega las fresas frescas y espolvorea canela.',
    ],
    approxCalories: 95,
    approxProteinGrams: 10,
  },
  // Colaciones Saludables NUTRIMSS 2024 (SMAE 5ª Edición)
  {
    id: 'rec_snk_8',
    title: 'Guayabas Frescas con Cacahuates Naturales',
    mealType: 'snack',
    prepTimeMinutes: 2,
    isBudgetFriendly: true,
    ingredients: [
      '3 piezas de guayaba chica fresca',
      '14 piezas de cacahuates naturales sin sal',
    ],
    instructions: [
      'Lava y rebana las guayabas.',
      'Acompaña con los cacahuates naturales para un aporte saciante de vitamina C, fibra y grasas monoinsaturadas.',
    ],
    approxCalories: 110,
    approxProteinGrams: 4,
  },
  {
    id: 'rec_snk_9',
    title: 'Papaya Fresca Picada con Yogur Natural',
    mealType: 'snack',
    prepTimeMinutes: 2,
    isBudgetFriendly: true,
    ingredients: [
      '1 taza de papaya picada en cubos',
      '1/2 taza de yogur natural sin azúcar añadida',
    ],
    instructions: [
      'Sirve la papaya fresca en un tazón.',
      'Vierte el yogur natural encima para mejorar la digestión y saciedad.',
    ],
    approxCalories: 95,
    approxProteinGrams: 6,
  },
  {
    id: 'rec_snk_10',
    title: 'Gajos de Naranja y Toronja con Chile Piquín',
    mealType: 'snack',
    prepTimeMinutes: 3,
    isBudgetFriendly: true,
    ingredients: [
      '1 pieza de naranja o toronja fresca en gajos',
      'Jugo de 1/2 limón y chile piquín sin sal ni azúcar',
    ],
    instructions: [
      'Pela y separa los gajos de la fruta cítrica.',
      'Espolvorea chile piquín al gusto con unas gotas de limón.',
    ],
    approxCalories: 60,
    approxProteinGrams: 1,
  },
  {
    id: 'rec_snk_11',
    title: 'Uvas Frescas con Almendras Tostadas',
    mealType: 'snack',
    prepTimeMinutes: 2,
    isBudgetFriendly: true,
    ingredients: [
      '18 piezas de uvas frescas (rojas o verdes)',
      '10 piezas de almendras enteras sin sal',
    ],
    instructions: [
      'Lava las uvas y disfrútalas con el puñado de almendras para energía rápida y control de apetito.',
    ],
    approxCalories: 130,
    approxProteinGrams: 3,
  },
  {
    id: 'rec_snk_12',
    title: 'Melón Picado con Semillas de Girasol',
    mealType: 'snack',
    prepTimeMinutes: 2,
    isBudgetFriendly: true,
    ingredients: [
      '1 taza de melón picado',
      '2 cucharaditas de semillas de girasol o calabaza tostadas',
    ],
    instructions: [
      'Pica el melón en cubos y espolvorea las semillas crujientes por encima.',
    ],
    approxCalories: 90,
    approxProteinGrams: 3,
  },
  {
    id: 'rec_snk_13',
    title: 'Plátano Dominico con Cacahuates Tostados',
    mealType: 'snack',
    prepTimeMinutes: 1,
    isBudgetFriendly: true,
    ingredients: [
      '2 piezas de plátano dominico (o 1/2 plátano tabasco)',
      '10 piezas de cacahuates tostados sin sal',
    ],
    instructions: [
      'Pela los plátanos y acompáñalos de los cacahuates para energía limpia previa o posterior a tu rutina física.',
    ],
    approxCalories: 120,
    approxProteinGrams: 3,
  },
  {
    id: 'rec_snk_14',
    title: 'Tuna Fresca con Gotitas de Limón y Sal',
    mealType: 'snack',
    prepTimeMinutes: 2,
    isBudgetFriendly: true,
    ingredients: [
      '2 piezas de tuna verde o roja fría',
      'Gotas de jugo de limón y pizca de sal',
    ],
    instructions: [
      'Pela las tunas frías, corta en rebanadas y agrega unas gotas de limón fresco.',
    ],
    approxCalories: 60,
    approxProteinGrams: 1,
  },
  {
    id: 'rec_snk_15',
    title: 'Ceviche de Plátano Verde con Tostadas',
    mealType: 'snack',
    prepTimeMinutes: 12,
    isBudgetFriendly: true,
    ingredients: [
      '1 plátano verde cocido picado en cubitos',
      '1 jitomate picado en cubos',
      '1/4 de cebolla blanca picada',
      '2 cucharadas de cilantro fresco picado',
      'Jugo de 2 limones frescos',
      '1 chile verde picado',
      '2 tostadas de maíz horneadas sin grasa',
      'Pizca de sal de mar',
    ],
    instructions: [
      'Cuece el plátano verde entero con cáscara en agua hirviendo hasta que esté suave; pela y pica en cubitos.',
      'En un tazón, combina el plátano cocido con el jitomate, cebolla, cilantro, chile y el jugo de limón.',
      'Mezcla bien con una pizca de sal y sirve fresco sobre las 2 tostadas horneadas.',
    ],
    approxCalories: 180,
    approxProteinGrams: 4,
  },
];

import { DietaryPreference } from '../types';

/**
 * Filtra recetas del catálogo según la preferencia alimentaria del usuario.
 * Garantiza opciones 100% vegetarianas, veganas o pescetarianas sin perder variedad económica.
 */
export function filterRecipesByDiet(recipes: RecipeItem[], preference?: DietaryPreference): RecipeItem[] {
  if (!preference || preference === 'balanced') return recipes;

  return recipes.filter((r) => {
    const text = (r.title + ' ' + r.ingredients.join(' ')).toLowerCase();
    const hasMeat = text.includes('pollo') || text.includes('pechuga') || /\b(res|carne|pavo|cerdo|cochinita|jamón|salchicha)\b/.test(text);
    const hasFish = text.includes('atún') || text.includes('pescado') || text.includes('salmón') || text.includes('marisco') || text.includes('camarón');
    const hasEggDairy = text.includes('huevo') || text.includes('queso') || text.includes('leche') || text.includes('yogur') || text.includes('requesón') || text.includes('panela');

    if (preference === 'pescatarian') {
      return !hasMeat; // Plantas, pescado, mariscos, huevos y lácteos
    }
    if (preference === 'vegetarian') {
      return !hasMeat && !hasFish; // Plantas, huevos y lácteos
    }
    if (preference === 'vegan') {
      return !hasMeat && !hasFish && !hasEggDairy; // 100% plantas
    }
    return true;
  });
}

