import { ExerciseAnimationType, PlannedExerciseItem } from '../types';

export interface ExtendedExerciseItem extends PlannedExerciseItem {}

const VERIFIED_LOCAL_MEDIA = { officialGif: 'verified', localFallback: 'exact_gif' } as const;

export const EXERCISES_CATALOG: ExtendedExerciseItem[] = [

  // ============================================================
  // NIVEL 1: PRINCIPIANTE — Sin impacto, articulaciones seguras
  // Para personas sedentarias, sobrepeso alto o inicio absoluto
  // ============================================================

  {
    id: 'ex_begin_wall_squat',
    name: 'Sentadilla Asistida en Pared',
    category: 'peso_corporal',
    targetMuscle: 'Cuádriceps y Glúteos',
    suggestedSets: 2,
    suggestedRepsOrSeconds: '8 - 10 reps lentas',
    restSeconds: 60,
    description: 'Apoya la espalda baja en la pared y baja poco a poco doblando las rodillas hasta 90°. Sube empujando con los talones.',
    tips: ['Rodillas no pasan la punta de los pies', 'Espalda siempre pegada a la pared', 'Sube lento en 3 segundos'],
    requiresEquipment: 'Pared lisa',
    difficulty: 'principiante',
    animationType: 'squat_goblet',
    levelNumeric: 1,
    exerciseDbId: 'b63ZzGe',
  },
  {
    id: 'ex_begin_glute_bridge',
    name: 'Puente de Glúteo Básico en el Suelo',
    category: 'peso_corporal',
    targetMuscle: 'Glúteos e Isquiotibiales',
    suggestedSets: 2,
    suggestedRepsOrSeconds: '12 reps',
    restSeconds: 45,
    description: 'Acostado boca arriba, pies apoyados en el suelo separados al ancho de caderas. Empuja con los talones y eleva la pelvis apretando los glúteos.',
    tips: ['Aprieta los glúteos 2 segundos arriba', 'No arquees la espalda baja', 'Bajar suave sin golpear el suelo'],
    requiresEquipment: 'Colchoneta o suelo alfombrado',
    difficulty: 'principiante',
    animationType: 'bridge_glute',
    levelNumeric: 1,
    exerciseDbId: 'u0cNiij',
  },
  {
    id: 'ex_begin_band_bridge',
    name: 'Puente de Glúteo en Banco',
    category: 'peso_corporal',
    targetMuscle: 'Glúteos e Isquiotibiales',
    suggestedSets: 2,
    suggestedRepsOrSeconds: '10 - 12 reps',
    restSeconds: 45,
    description: 'Siéntate en el borde de un banco o silla estable, apoya la espalda alta y los pies en el suelo. Eleva la cadera hasta formar una línea entre rodillas y hombros.',
    tips: ['Usa solo un banco o silla que no se deslice', 'Aprieta los glúteos arriba sin arquear la espalda'],
    requiresEquipment: 'Banco o silla estable',
    difficulty: 'principiante',
    animationType: 'bridge_glute',
    levelNumeric: 1,
    exerciseDbId: 'aWedzZX',
  },
  {
    id: 'ex_begin_step_jack',
    name: 'Paso Lateral sin Salto',
    category: 'cardio',
    targetMuscle: 'Cardio General y Calentamiento',
    suggestedSets: 2,
    suggestedRepsOrSeconds: '20 - 30 segundos',
    restSeconds: 30,
    description: 'Da un paso controlado hacia delante y regresa al centro, alternando piernas y coordinando el braceo sin saltar.',
    tips: ['Mantén un ritmo cómodo', 'Activa suavemente el abdomen', 'Respiración fluida todo el tiempo'],
    requiresEquipment: 'Ninguno',
    difficulty: 'principiante',
    animationType: 'step_jack',
    levelNumeric: 1,
    exerciseDbId: 'fNGumX0',
    media: VERIFIED_LOCAL_MEDIA,
  },
  {
    id: 'ex_begin_wall_pushup',
    name: 'Flexión Inclinada',
    category: 'peso_corporal',
    targetMuscle: 'Pectoral, Tríceps y Hombros',
    suggestedSets: 2,
    suggestedRepsOrSeconds: '10 - 12 reps',
    restSeconds: 45,
    description: 'Apoya las manos sobre una superficie elevada y firme. Mantén el cuerpo recto y flexiona los codos para acercar el pecho a la superficie.',
    tips: ['Cuerpo como una tabla — cadera no sobresale', 'Codos a 45° (no 90°) para proteger hombros'],
    requiresEquipment: 'Mesa o banco firme',
    difficulty: 'principiante',
    animationType: 'pushup_incline',
    levelNumeric: 1,
    exerciseDbId: 'B1EVP9F',
  },
  {
    id: 'ex_begin_clamshell',
    name: 'Abducción Lateral de Cadera de Pie',
    category: 'peso_corporal',
    targetMuscle: 'Abductores y Glúteos',
    suggestedSets: 2,
    suggestedRepsOrSeconds: '12 reps por lado',
    restSeconds: 30,
    description: 'De pie, transfiere el peso a una pierna y eleva la otra recta hacia el lado sin inclinar el torso. Alterna lados.',
    tips: ['Mantén la pelvis nivelada', 'Sujétate a una pared si pierdes equilibrio', 'Sube y baja lento'],
    requiresEquipment: 'Pared opcional para apoyo',
    difficulty: 'principiante',
    animationType: 'monster_walk',
    levelNumeric: 1,
    exerciseDbId: '7WaDzyL',
  },
  {
    id: 'ex_begin_band_row',
    name: 'Remo Unilateral Sentado con Liga y Giro',
    category: 'ligas',
    targetMuscle: 'Espalda Media y Bíceps',
    suggestedSets: 2,
    suggestedRepsOrSeconds: '10 reps por lado',
    restSeconds: 45,
    description: 'Siéntate en una silla con espalda recta. Tira de la liga con un brazo hacia el torso mientras giras suavemente hacia ese lado; cambia de lado.',
    tips: ['Pecho erguido al jalar', 'El giro es suave y acompaña al brazo', 'Pausa 1 segundo apretando la espalda'],
    requiresEquipment: 'Liga elástica y silla estable',
    difficulty: 'principiante',
    animationType: 'row_band',
    levelNumeric: 1,
    exerciseDbId: 'DKBwJrL',
  },
  {
    id: 'ex_begin_wall_pushup_supported', name: 'Flexión en Pared', category: 'peso_corporal', targetMuscle: 'Pectoral, Tríceps y Hombros', suggestedSets: 2, suggestedRepsOrSeconds: '8 - 10 reps', restSeconds: 45,
    description: 'Con las manos en la pared a la altura del pecho, acerca el torso y empuja para volver.', tips: ['Cuerpo alineado', 'Codos a 45°'], requiresEquipment: 'Pared', difficulty: 'principiante', animationType: 'pushup_incline', levelNumeric: 1, exerciseDbId: 'LEH9jxP',
  },
  {
    id: 'ex_begin_ski_step', name: 'Ski Step sin Salto', category: 'cardio', targetMuscle: 'Cardio y Piernas', suggestedSets: 2, suggestedRepsOrSeconds: '30 segundos', restSeconds: 30,
    description: 'Alterna pasos diagonales llevando brazos y piernas en direcciones opuestas, sin despegar ambos pies del suelo.', tips: ['Ritmo cómodo', 'Rodillas suaves'], requiresEquipment: 'Ninguno', difficulty: 'principiante', animationType: 'step_jack', levelNumeric: 1, exerciseDbId: '5MRH8H2',
  },
  {
    id: 'ex_begin_bridge_march', name: 'Marcha en Puente de Glúteo', category: 'peso_corporal', targetMuscle: 'Glúteos y Core', suggestedSets: 2, suggestedRepsOrSeconds: '8 reps por lado', restSeconds: 45,
    description: 'Desde un puente de glúteo, alterna levantar un pie sin dejar caer la pelvis.', tips: ['Pelvis estable', 'Detén si hay calambre lumbar'], requiresEquipment: 'Colchoneta', difficulty: 'principiante', animationType: 'bridge_glute', levelNumeric: 1, exerciseDbId: 'GibBPPg',
  },

  // ============================================================
  // NIVEL 2: INTERMEDIO — Uso de mancuernas y carga moderada
  // Para personas con 3-6 semanas de hábito o actividad ligera
  // ============================================================

  {
    id: 'ex_int_goblet_squat',
    name: 'Sentadilla Goblet con Mancuerna',
    category: 'mancuernas',
    targetMuscle: 'Cuádriceps, Glúteos y Core',
    suggestedSets: 3,
    suggestedRepsOrSeconds: '10 - 12 reps',
    restSeconds: 60,
    description: 'Sostén una mancuerna pegada al pecho con ambas manos. Desciende como si fueras a sentarte en una silla sin despegar los talones.',
    tips: ['Pecho erguido todo el tiempo', 'Rodillas apuntando en dirección de los pies', 'Talones en el suelo en todo momento'],
    requiresEquipment: '1 mancuerna (4-8 kg)',
    difficulty: 'intermedio',
    animationType: 'squat_goblet',
    levelNumeric: 2,
    exerciseDbId: 'yn8yg1r',
  },
  {
    id: 'ex_int_db_curl',
    name: 'Curl de Bíceps con Mancuernas Alterno',
    category: 'mancuernas',
    targetMuscle: 'Bíceps y Antebrazo',
    suggestedSets: 3,
    suggestedRepsOrSeconds: '10 reps por brazo',
    restSeconds: 45,
    description: 'De pie con mancuernas a los costados, palmas hacia arriba. Flexiona un brazo a la vez llevando la mancuerna al hombro con codo pegado al torso.',
    tips: ['No balancea el cuerpo para ayudarte', 'Gira ligeramente la palma hacia arriba al subir (supinación)', 'Baja lento en 2-3 segundos'],
    requiresEquipment: '2 mancuernas (3-6 kg)',
    difficulty: 'intermedio',
    animationType: 'curl_biceps',
    levelNumeric: 2,
    exerciseDbId: 'BU15nH4',
  },
  {
    id: 'ex_int_db_row',
    name: 'Remo a una Mano en Silla',
    category: 'mancuernas',
    targetMuscle: 'Dorsal Ancho y Espalda Media',
    suggestedSets: 3,
    suggestedRepsOrSeconds: '10 reps por lado',
    restSeconds: 45,
    description: 'Apoya la mano y rodilla contraria en una silla resistente. Con la espalda neutral a 45°, jala la mancuerna hacia la cadera conduciendo con el codo.',
    tips: ['No gires la cadera para jalar', 'El codo roza la caja torácica al subir', 'Baja completamente para estirar la espalda'],
    requiresEquipment: '1 mancuerna (4-10 kg) + silla',
    difficulty: 'intermedio',
    animationType: 'row_dumbbell',
    levelNumeric: 2,
    exerciseDbId: 'C0MA9bC',
  },
  {
    id: 'ex_int_shoulder_press',
    name: 'Press de Hombros Sentado',
    category: 'mancuernas',
    targetMuscle: 'Deltoides (Hombros)',
    suggestedSets: 3,
    suggestedRepsOrSeconds: '10 - 12 reps',
    restSeconds: 60,
    description: 'Sentado con la espalda recta, mancuernas a la altura de las orejas. Empuja hacia arriba en arco controlado hasta casi juntar las manos arriba.',
    tips: ['No arquees la zona lumbar', 'Baja lento en 3 segundos', 'Muñecas neutras, no dobladas'],
    requiresEquipment: '2 mancuernas (3-6 kg) + silla',
    difficulty: 'intermedio',
    animationType: 'shoulder_press',
    levelNumeric: 2,
    exerciseDbId: 'f1jf47L',
  },
  {
    id: 'ex_int_monster_walk',
    name: 'Monster Walk — Pasos Laterales en Semi-Sentadilla',
    category: 'bandas_pierna',
    targetMuscle: 'Glúteo Medio y Abductores',
    suggestedSets: 3,
    suggestedRepsOrSeconds: '10 pasos a cada lado',
    restSeconds: 60,
    description: 'Coloca la banda sobre rodillas o tobillos. Adopta postura de media sentadilla y da pasos laterales controlados manteniendo tensión continua.',
    tips: ['Nunca juntes los pies del todo para mantener tensión', 'Pecho erguido y cadera levemente hacia atrás', 'Peso en talones y parte media del pie'],
    requiresEquipment: 'Banda elástica mini band',
    difficulty: 'intermedio',
    animationType: 'monster_walk',
    levelNumeric: 2,
    exerciseDbId: 'O95afRA',
  },
  {
    id: 'ex_int_lateral_raise',
    name: 'Elevaciones Laterales con Mancuernas',
    category: 'mancuernas',
    targetMuscle: 'Deltoides Lateral (Hombro)',
    suggestedSets: 3,
    suggestedRepsOrSeconds: '12 - 15 reps',
    restSeconds: 45,
    description: 'De pie con una mancuerna en cada mano, eleva los brazos lateralmente con codos ligeramente flexionados hasta la horizontal.',
    tips: ['No subas más allá de la altura del hombro', 'Movimiento lento al bajar para más tensión muscular', 'Usa carga ligera y controlada'],
    requiresEquipment: '2 mancuernas ligeras',
    difficulty: 'intermedio',
    animationType: 'lateral_raise',
    levelNumeric: 2,
    exerciseDbId: 'DsgkuIt',
    media: VERIFIED_LOCAL_MEDIA,
  },
  {
    id: 'ex_int_rdl',
    name: 'Peso Muerto Rumano con Mancuernas',
    category: 'mancuernas',
    targetMuscle: 'Femorales, Glúteos y Espalda Baja',
    suggestedSets: 3,
    suggestedRepsOrSeconds: '10 - 12 reps',
    restSeconds: 60,
    description: 'De pie con mancuernas al frente de los muslos. Desliza las mancuernas por las piernas bajando con la espalda recta hasta sentir tensión en la parte trasera de los muslos.',
    tips: ['Espalda recta (NO redondes la columna)', 'Rodillas ligeramente dobladas', 'Empuja la cadera hacia atrás, no hacia abajo'],
    requiresEquipment: '2 mancuernas (4-10 kg)',
    difficulty: 'intermedio',
    animationType: 'deadlift_rdl',
    levelNumeric: 2,
    exerciseDbId: 'rR0LJzx',
  },
  {
    id: 'ex_int_cardio_hknees',
    name: 'High Knees con Apoyo en Pared',
    category: 'cardio',
    targetMuscle: 'Cardio, Core y Hip Flexors',
    suggestedSets: 3,
    suggestedRepsOrSeconds: '45 segundos',
    restSeconds: 30,
    description: 'Frente a una pared, apoya las manos, alterna las rodillas hacia el pecho a ritmo rápido y mantén estable el tronco.',
    tips: ['Mantén el abdomen activo', 'No arquees la espalda', 'Reduce el ritmo si pierdes el control'],
    requiresEquipment: 'Pared',
    difficulty: 'intermedio',
    animationType: 'step_jack',
    levelNumeric: 2,
    exerciseDbId: 'ealLwvX',
  },
  {
    id: 'ex_int_band_row', name: 'Remo Sentado con Liga de Resistencia', category: 'ligas', targetMuscle: 'Espalda Media y Bíceps', suggestedSets: 3, suggestedRepsOrSeconds: '10 - 12 reps', restSeconds: 45,
    description: 'Sentado con espalda recta, tira de la liga hacia el torso y junta los omóplatos.', tips: ['No encorves la espalda', 'Regresa lento'], requiresEquipment: 'Liga de resistencia y silla', difficulty: 'intermedio', animationType: 'row_band', levelNumeric: 2, exerciseDbId: 'Nu7jqFE',
  },
  {
    id: 'ex_int_band_curl', name: 'Curl de Bíceps Sentado con Liga', category: 'ligas', targetMuscle: 'Bíceps y Antebrazo', suggestedSets: 3, suggestedRepsOrSeconds: '10 - 12 reps', restSeconds: 45,
    description: 'Sentado, flexiona los codos contra la liga sin mover la parte superior de los brazos.', tips: ['Codos pegados', 'Baja controlado'], requiresEquipment: 'Liga de resistencia y silla', difficulty: 'intermedio', animationType: 'curl_biceps', levelNumeric: 2, exerciseDbId: 'XFc3vpY',
  },
  {
    id: 'ex_int_band_press', name: 'Press de Hombros Sentado con Liga', category: 'ligas', targetMuscle: 'Deltoides y Tríceps', suggestedSets: 3, suggestedRepsOrSeconds: '10 reps', restSeconds: 60,
    description: 'Sentado, lleva la liga desde hombros hasta extender los brazos por encima de la cabeza.', tips: ['No arquees la espalda', 'Muñecas neutras'], requiresEquipment: 'Liga de resistencia y silla', difficulty: 'intermedio', animationType: 'shoulder_press', levelNumeric: 2, exerciseDbId: 'S93zLTG',
  },

  // ============================================================
  // NIVEL 3: AVANZADO — Combinaciones, tempo y HIIT casero
  // Para personas con hábito establecido de 6+ semanas
  // ============================================================

  {
    id: 'ex_adv_jump_squat',
    name: 'Sentadilla con Salto Controlado',
    category: 'peso_corporal',
    targetMuscle: 'Cuádriceps, Glúteos y Potencia Cardiovascular',
    suggestedSets: 4,
    suggestedRepsOrSeconds: '10 reps explosivas',
    restSeconds: 60,
    description: 'Sentadilla completa. En la subida, explota empujando con los pies para saltar y aterriza suave doblando rodillas inmediatamente.',
    tips: ['Aterriza suave para proteger rodillas', 'Cadera hacia atrás al bajar', 'Si tienes problemas de rodilla, omite este ejercicio'],
    requiresEquipment: 'Ninguno (suelo con espacio)',
    difficulty: 'avanzado',
    animationType: 'squat_goblet',
    levelNumeric: 3,
    exerciseDbId: 'LIlE5Tn',
  },
  {
    id: 'ex_adv_db_band_squat',
    name: 'Sentadilla con Mancuernas',
    category: 'mancuernas',
    targetMuscle: 'Cuádriceps, Glúteos e Isquiotibiales',
    suggestedSets: 4,
    suggestedRepsOrSeconds: '10 - 12 reps',
    restSeconds: 60,
    description: 'Sostén una mancuerna en cada mano a los costados. Baja controlado como si te sentaras y empuja con los talones para volver arriba.',
    tips: ['Pecho erguido y core activo', 'Rodillas siguen la dirección de los pies', 'Controla el descenso'],
    requiresEquipment: '2 mancuernas',
    difficulty: 'avanzado',
    animationType: 'squat_goblet',
    levelNumeric: 3,
    exerciseDbId: 'HsvHqgf',
  },
  {
    id: 'ex_adv_pushup_floor',
    name: 'Flexión Completa en Suelo',
    category: 'peso_corporal',
    targetMuscle: 'Pectoral, Tríceps, Deltoides y Core',
    suggestedSets: 4,
    suggestedRepsOrSeconds: '12 - 15 reps',
    restSeconds: 45,
    description: 'En posición de plancha alta, baja el pecho hasta casi tocar el suelo con control total y empuja de vuelta a la posición inicial.',
    tips: ['Cuerpo como una tabla rígida', 'Codos a 45° respecto al torso', 'Exhala al empujar, inhala al bajar'],
    requiresEquipment: 'Suelo firme',
    difficulty: 'avanzado',
    animationType: 'pushup_incline',
    levelNumeric: 3,
    exerciseDbId: 'I4hDWkc',
  },
  {
    id: 'ex_adv_mountain_climber',
    name: 'Escaladores (Mountain Climbers)',
    category: 'cardio',
    targetMuscle: 'Core, Hip Flexors y Cardio HIIT',
    suggestedSets: 3,
    suggestedRepsOrSeconds: '30 - 45 segundos',
    restSeconds: 30,
    description: 'En posición de plancha alta, alterna cada rodilla hacia el pecho de forma explosiva manteniendo la cadera baja y el core rígido.',
    tips: ['Cadera ABAJO — no la eleves', 'Core activado en todo momento', 'Respiración controlada, no apnea'],
    requiresEquipment: 'Ninguno',
    difficulty: 'avanzado',
    animationType: 'mountain_climber',
    levelNumeric: 3,
    exerciseDbId: 'RJgzwny',
    media: VERIFIED_LOCAL_MEDIA,
  },
  {
    id: 'ex_adv_shadow_box',
    name: 'Burpee con Mancuernas',
    category: 'mancuernas',
    targetMuscle: 'Cardio, Piernas, Hombros y Core',
    suggestedSets: 3,
    suggestedRepsOrSeconds: '6 - 8 reps',
    restSeconds: 60,
    description: 'Con una mancuerna en cada mano, baja a sentadilla, colócalas en el suelo, lleva los pies atrás, haz una flexión y vuelve a ponerte de pie para presionar arriba.',
    tips: ['Usa mancuernas estables y poco peso', 'Mantén espalda neutra al bajar', 'Haz la flexión con rodillas apoyadas si es necesario'],
    requiresEquipment: '2 mancuernas ligeras',
    difficulty: 'avanzado',
    animationType: 'mountain_climber',
    levelNumeric: 3,
    exerciseDbId: '0JtKWum',
  },
  {
    id: 'ex_adv_kickback',
    name: 'Patada de Tríceps con Mancuerna',
    category: 'mancuernas',
    targetMuscle: 'Tríceps y Hombros',
    suggestedSets: 3,
    suggestedRepsOrSeconds: '12 reps por brazo',
    restSeconds: 45,
    description: 'Inclina el torso con espalda neutra, lleva el codo a 90° junto al cuerpo y extiende el antebrazo hacia atrás. Cambia de brazo.',
    tips: ['El codo no se separa del torso', 'No redondees la espalda', 'Controla el regreso'],
    requiresEquipment: '1 mancuerna',
    difficulty: 'avanzado',
    animationType: 'curl_biceps',
    levelNumeric: 3,
    exerciseDbId: 'bQy2Eni',
    media: VERIFIED_LOCAL_MEDIA,
  },
  {
    id: 'ex_adv_pushup_side_plank', name: 'Flexión a Plancha Lateral', category: 'peso_corporal', targetMuscle: 'Pectoral, Core y Hombros', suggestedSets: 3, suggestedRepsOrSeconds: '8 reps por lado', restSeconds: 60,
    description: 'Haz una flexión y gira a plancha lateral elevando un brazo; alterna el lado en cada repetición.', tips: ['Cadera alineada', 'Apoya rodillas si no controlas la flexión'], requiresEquipment: 'Suelo firme', difficulty: 'avanzado', animationType: 'pushup_incline', levelNumeric: 3, exerciseDbId: 'KhHJ338',
  },
  {
    id: 'ex_adv_dumbbell_stepup', name: 'Subida a Escalón con Mancuernas', category: 'mancuernas', targetMuscle: 'Glúteos y Cuádriceps', suggestedSets: 3, suggestedRepsOrSeconds: '10 reps por lado', restSeconds: 60,
    description: 'Sube a un escalón bajo y estable con una mancuerna en cada mano; baja con control y alterna.', tips: ['Escalón firme', 'Rodilla sigue al pie'], requiresEquipment: '2 mancuernas y escalón estable', difficulty: 'avanzado', animationType: 'squat_goblet', levelNumeric: 3, exerciseDbId: 'aXtJhlg',
  },
  {
    id: 'ex_adv_power_plank', name: 'Plancha Power Point', category: 'peso_corporal', targetMuscle: 'Core y Hombros', suggestedSets: 3, suggestedRepsOrSeconds: '30 segundos', restSeconds: 45,
    description: 'Mantén una plancha firme y alterna extensiones controladas según la animación, sin elevar la cadera.', tips: ['Core activo', 'Cuello neutral'], requiresEquipment: 'Colchoneta', difficulty: 'avanzado', animationType: 'mountain_climber', levelNumeric: 3, exerciseDbId: 'hCjGsRQ',
  },
  // FASE 1 — ampliación curada: ocho ejercicios por nivel.
  { id: 'ex_begin_calf_raise', name: 'Elevación de Talones de Pie', category: 'peso_corporal', targetMuscle: 'Pantorrillas', suggestedSets: 2, suggestedRepsOrSeconds: '12 reps', restSeconds: 30, description: 'Eleva los talones de forma controlada y baja despacio manteniendo apoyo en ambos pies.', tips: ['Sujétate a una pared si lo necesitas'], requiresEquipment: 'Pared opcional', difficulty: 'principiante', animationType: 'squat_goblet', levelNumeric: 1, exerciseDbId: 'bJYHBIN' },
  { id: 'ex_int_dead_bug', name: 'Dead Bug', category: 'peso_corporal', targetMuscle: 'Core', suggestedSets: 3, suggestedRepsOrSeconds: '8 reps por lado', restSeconds: 30, description: 'Boca arriba, extiende brazo y pierna opuestos sin despegar la espalda baja del suelo.', tips: ['Movimiento lento', 'Exhala al extender'], requiresEquipment: 'Colchoneta', difficulty: 'intermedio', animationType: 'bridge_glute', levelNumeric: 2, exerciseDbId: 'iny3m5y', media: VERIFIED_LOCAL_MEDIA },
  { id: 'ex_begin_frog_crunch', name: 'Crunch Mariposa', category: 'peso_corporal', targetMuscle: 'Abdomen', suggestedSets: 2, suggestedRepsOrSeconds: '10 reps', restSeconds: 30, description: 'Con plantas de los pies juntas, eleva hombros hacia las rodillas sin jalar el cuello.', tips: ['Mira al techo', 'Activa el abdomen'], requiresEquipment: 'Colchoneta', difficulty: 'principiante', animationType: 'bridge_glute', levelNumeric: 1, exerciseDbId: 'FFRP97T' },
  { id: 'ex_int_reverse_crunch', name: 'Crunch Inverso', category: 'peso_corporal', targetMuscle: 'Abdomen', suggestedSets: 3, suggestedRepsOrSeconds: '8 - 10 reps', restSeconds: 30, description: 'Lleva rodillas hacia el pecho elevando suavemente la pelvis y baja con control.', tips: ['No balancees el cuerpo'], requiresEquipment: 'Colchoneta', difficulty: 'intermedio', animationType: 'bridge_glute', levelNumeric: 2, exerciseDbId: 'nCU1Ekp', media: VERIFIED_LOCAL_MEDIA },
  { id: 'ex_begin_squat_reach', name: 'Sentadilla con Alcance Arriba', category: 'peso_corporal', targetMuscle: 'Cuádriceps y Hombros', suggestedSets: 2, suggestedRepsOrSeconds: '10 reps', restSeconds: 45, description: 'Baja a sentadilla cómoda y extiende brazos arriba al ponerte de pie.', tips: ['Talones apoyados', 'Sin dolor de rodilla'], requiresEquipment: 'Ninguno', difficulty: 'principiante', animationType: 'squat_goblet', levelNumeric: 1, exerciseDbId: 'QChZi3x' },
  { id: 'ex_begin_split_squat', name: 'Sentadilla Dividida Asistida', category: 'peso_corporal', targetMuscle: 'Cuádriceps y Glúteos', suggestedSets: 2, suggestedRepsOrSeconds: '8 reps por lado', restSeconds: 45, description: 'Con una mano en la pared, baja en una zancada corta y vertical; alterna lados.', tips: ['Paso corto', 'Rodilla alineada al pie'], requiresEquipment: 'Pared opcional', difficulty: 'principiante', animationType: 'squat_goblet', levelNumeric: 1, exerciseDbId: '9E25EOx' },
  { id: 'ex_begin_oblique_crunch', name: 'Crunch Oblicuo', category: 'peso_corporal', targetMuscle: 'Oblicuos', suggestedSets: 2, suggestedRepsOrSeconds: '10 reps por lado', restSeconds: 30, description: 'Eleva hombro hacia la cadera contraria con un giro corto y controlado.', tips: ['No jales el cuello'], requiresEquipment: 'Colchoneta', difficulty: 'principiante', animationType: 'bridge_glute', levelNumeric: 1, exerciseDbId: 'cJgSTmh' },
  { id: 'ex_begin_wall_pushup_static', name: 'Flexión en Pared con Pausa', category: 'peso_corporal', targetMuscle: 'Pectoral y Tríceps', suggestedSets: 2, suggestedRepsOrSeconds: '8 reps', restSeconds: 45, description: 'Realiza una flexión en pared y mantén un segundo cerca de la pared antes de empujar.', tips: ['Cuerpo alineado', 'Codos a 45°'], requiresEquipment: 'Pared', difficulty: 'principiante', animationType: 'pushup_incline', levelNumeric: 1, exerciseDbId: 'qBl14UC' },
  { id: 'ex_begin_hammer_curl', name: 'Curl Martillo con Mancuernas', category: 'mancuernas', targetMuscle: 'Bíceps', suggestedSets: 2, suggestedRepsOrSeconds: '8 - 10 reps', restSeconds: 45, description: 'Con palmas enfrentadas, flexiona las mancuernas sin mover los codos.', tips: ['Evita balancearte'], requiresEquipment: '2 mancuernas ligeras', difficulty: 'principiante', animationType: 'curl_biceps', levelNumeric: 1, exerciseDbId: '2NpxjC1', media: VERIFIED_LOCAL_MEDIA },
  { id: 'ex_begin_front_raise', name: 'Elevación Frontal con Mancuernas', category: 'mancuernas', targetMuscle: 'Hombros', suggestedSets: 2, suggestedRepsOrSeconds: '8 - 10 reps', restSeconds: 45, description: 'Eleva las mancuernas al frente hasta la altura de hombros y baja lento.', tips: ['Carga ligera', 'Core firme'], requiresEquipment: '2 mancuernas ligeras', difficulty: 'principiante', animationType: 'lateral_raise', levelNumeric: 1, exerciseDbId: '3eGE2JC', media: VERIFIED_LOCAL_MEDIA },
  { id: 'ex_int_rear_fly', name: 'Apertura Posterior con Mancuernas', category: 'mancuernas', targetMuscle: 'Hombros Posteriores y Espalda Alta', suggestedSets: 3, suggestedRepsOrSeconds: '10 reps', restSeconds: 45, description: 'Inclina el torso con espalda neutra y abre los brazos hacia los lados.', tips: ['Cuello relajado', 'Sin impulso'], requiresEquipment: '2 mancuernas ligeras', difficulty: 'intermedio', animationType: 'row_dumbbell', levelNumeric: 2, exerciseDbId: '8DiFDVA' },
  { id: 'ex_int_triceps_extension', name: 'Extensión de Tríceps Inclinado', category: 'mancuernas', targetMuscle: 'Tríceps', suggestedSets: 3, suggestedRepsOrSeconds: '10 reps', restSeconds: 45, description: 'Inclina el torso, fija los codos y extiende ambos antebrazos hacia atrás.', tips: ['Espalda neutra'], requiresEquipment: '2 mancuernas', difficulty: 'intermedio', animationType: 'curl_biceps', levelNumeric: 2, exerciseDbId: '3T12T87' },
  { id: 'ex_int_db_calf_raise', name: 'Elevación de Talones con Mancuernas', category: 'mancuernas', targetMuscle: 'Pantorrillas', suggestedSets: 3, suggestedRepsOrSeconds: '12 reps', restSeconds: 45, description: 'Sostén mancuernas a los lados, sube a puntas y baja despacio.', tips: ['Apóyate si pierdes equilibrio'], requiresEquipment: '2 mancuernas', difficulty: 'intermedio', animationType: 'squat_goblet', levelNumeric: 2, exerciseDbId: 'dPmaUaU' },
  { id: 'ex_int_forward_lunge', name: 'Zancada Frontal con Mancuerna', category: 'mancuernas', targetMuscle: 'Glúteos y Piernas', suggestedSets: 3, suggestedRepsOrSeconds: '8 reps por lado', restSeconds: 60, description: 'Da un paso al frente y baja verticalmente sosteniendo una mancuerna del lado contrario.', tips: ['Paso estable', 'Rodilla no colapsa'], requiresEquipment: '1 mancuerna', difficulty: 'intermedio', animationType: 'squat_goblet', levelNumeric: 2, exerciseDbId: 'ecl28tP' },
  { id: 'ex_int_arnold_press', name: 'Press Arnold con Mancuernas', category: 'mancuernas', targetMuscle: 'Hombros', suggestedSets: 3, suggestedRepsOrSeconds: '8 - 10 reps', restSeconds: 60, description: 'Desde palmas hacia ti a la altura de hombros, rota y presiona arriba con control.', tips: ['No arquees la zona lumbar'], requiresEquipment: '2 mancuernas', difficulty: 'intermedio', animationType: 'shoulder_press', levelNumeric: 2, exerciseDbId: 'eOrFCnx' },
  { id: 'ex_int_upright_row', name: 'Remo Vertical con Mancuernas', category: 'mancuernas', targetMuscle: 'Hombros y Trapecio', suggestedSets: 3, suggestedRepsOrSeconds: '10 reps', restSeconds: 45, description: 'Lleva mancuernas cerca del torso hasta el pecho sin elevarlas demasiado.', tips: ['Usa rango cómodo para hombros'], requiresEquipment: '2 mancuernas ligeras', difficulty: 'intermedio', animationType: 'row_dumbbell', levelNumeric: 2, exerciseDbId: 'ainizkb' },
  { id: 'ex_adv_stiff_deadlift', name: 'Peso Muerto Piernas Semirrígidas', category: 'mancuernas', targetMuscle: 'Glúteos e Isquiotibiales', suggestedSets: 4, suggestedRepsOrSeconds: '8 - 10 reps', restSeconds: 60, description: 'Desciende mancuernas con cadera atrás y rodillas apenas flexionadas; vuelve apretando glúteos.', tips: ['Espalda neutra'], requiresEquipment: '2 mancuernas', difficulty: 'avanzado', animationType: 'deadlift_rdl', levelNumeric: 3, exerciseDbId: '2Ty4idJ' },
  { id: 'ex_adv_push_press', name: 'Push Press con Mancuernas', category: 'mancuernas', targetMuscle: 'Hombros, Tríceps y Piernas', suggestedSets: 4, suggestedRepsOrSeconds: '8 reps', restSeconds: 60, description: 'Impúlsate con una flexión corta de piernas para presionar mancuernas arriba.', tips: ['Core firme', 'No bloquees la espalda'], requiresEquipment: '2 mancuernas', difficulty: 'avanzado', animationType: 'shoulder_press', levelNumeric: 3, exerciseDbId: 'FS63wTN' },
  { id: 'ex_adv_single_leg_deadlift', name: 'Peso Muerto a Una Pierna con Mancuerna', category: 'mancuernas', targetMuscle: 'Glúteos, Isquiotibiales y Core', suggestedSets: 3, suggestedRepsOrSeconds: '8 reps por lado', restSeconds: 60, description: 'Inclina el torso y lleva una pierna atrás manteniendo caderas cuadradas; vuelve controlado.', tips: ['Empieza sin carga si pierdes equilibrio'], requiresEquipment: '1 mancuerna', difficulty: 'avanzado', animationType: 'deadlift_rdl', levelNumeric: 3, exerciseDbId: 'gKozT8X' },
  { id: 'ex_adv_curl_lunge', name: 'Zancada con Curl de Mancuernas', category: 'mancuernas', targetMuscle: 'Piernas y Bíceps', suggestedSets: 3, suggestedRepsOrSeconds: '8 reps por lado', restSeconds: 60, description: 'Realiza una zancada mientras haces curl de bíceps; alterna lados con control.', tips: ['Domina ambos movimientos por separado primero'], requiresEquipment: '2 mancuernas', difficulty: 'avanzado', animationType: 'curl_biceps', levelNumeric: 3, exerciseDbId: '1VpF8db' },
  { id: 'ex_adv_superman_pushup', name: 'Flexión Superman', category: 'peso_corporal', targetMuscle: 'Pectoral, Hombros y Core', suggestedSets: 3, suggestedRepsOrSeconds: '6 - 8 reps', restSeconds: 60, description: 'Desde una flexión, extiende los brazos al frente de forma controlada y regresa para empujar.', tips: ['No intentes si no dominas la flexión completa'], requiresEquipment: 'Suelo firme', difficulty: 'avanzado', animationType: 'pushup_incline', levelNumeric: 3, exerciseDbId: '4GqRrAk' },
  { id: 'ex_adv_athletic_side_plank', name: 'Flexión a Plancha Lateral Atlética', category: 'peso_corporal', targetMuscle: 'Pectoral y Core', suggestedSets: 3, suggestedRepsOrSeconds: '8 reps por lado', restSeconds: 60, description: 'Haz una flexión y rota a plancha lateral con control, alternando el lado.', tips: ['Cadera alineada'], requiresEquipment: 'Suelo firme', difficulty: 'avanzado', animationType: 'pushup_incline', levelNumeric: 3, exerciseDbId: 'kk39rUy' },
  { id: 'ex_int_high_knee_march', name: 'Marcha con Rodilla Alta', category: 'cardio', targetMuscle: 'Cardio', suggestedSets: 3, suggestedRepsOrSeconds: '30 segundos', restSeconds: 30, description: 'Eleva rodillas alternadas sin salto, manteniendo el tronco estable.', tips: ['Siempre un pie apoyado', 'Reduce el ritmo si pierdes control'], requiresEquipment: 'Ninguno', difficulty: 'intermedio', animationType: 'step_jack', levelNumeric: 2, exerciseDbId: 'J9zIWig', media: VERIFIED_LOCAL_MEDIA },
  { id: 'ex_adv_cuban_press', name: 'Press Cubano con Mancuernas', category: 'mancuernas', targetMuscle: 'Hombros y Espalda Alta', suggestedSets: 3, suggestedRepsOrSeconds: '8 reps', restSeconds: 60, description: 'Eleva codos, rota antebrazos y presiona suave arriba con carga muy ligera.', tips: ['Prioriza técnica y movilidad'], requiresEquipment: '2 mancuernas ligeras', difficulty: 'avanzado', animationType: 'shoulder_press', levelNumeric: 3, exerciseDbId: 'BqgCRif' },
  // FASE 2 — variantes de progresión por rango, tempo, carga y estabilidad.
  { id: 'ex_begin_tuck_crunch', name: 'Crunch Rodillas al Pecho', category: 'peso_corporal', targetMuscle: 'Abdomen', suggestedSets: 2, suggestedRepsOrSeconds: '10 reps', restSeconds: 30, description: 'Acerca rodillas y hombros en un recorrido corto y controlado.', tips: ['No jales el cuello'], requiresEquipment: 'Colchoneta', difficulty: 'principiante', animationType: 'bridge_glute', levelNumeric: 1, exerciseDbId: 'BMMolZ3' },
  { id: 'ex_begin_knee_touch_crunch', name: 'Crunch Toque de Rodillas', category: 'peso_corporal', targetMuscle: 'Abdomen', suggestedSets: 2, suggestedRepsOrSeconds: '10 reps', restSeconds: 30, description: 'Eleva hombros y alcanza las rodillas con las manos sin perder control.', tips: ['Exhala al subir'], requiresEquipment: 'Colchoneta', difficulty: 'principiante', animationType: 'bridge_glute', levelNumeric: 1, exerciseDbId: 'dTg95eZ' },
  { id: 'ex_begin_step_reach', name: 'Paso Atrás con Alcance Arriba', category: 'peso_corporal', targetMuscle: 'Core y Piernas', suggestedSets: 2, suggestedRepsOrSeconds: '8 reps por lado', restSeconds: 45, description: 'Da un paso atrás y alcanza arriba con el brazo contrario, volviendo con equilibrio.', tips: ['Paso corto y controlado'], requiresEquipment: 'Ninguno', difficulty: 'principiante', animationType: 'step_jack', levelNumeric: 1, exerciseDbId: 'ErqK3UL' },
  { id: 'ex_begin_scapula_pushup', name: 'Flexión Escapular', category: 'peso_corporal', targetMuscle: 'Serrato y Hombros', suggestedSets: 2, suggestedRepsOrSeconds: '10 reps', restSeconds: 30, description: 'En plancha inclinada o de rodillas, separa y junta omóplatos sin flexionar codos.', tips: ['Mantén el cuello largo'], requiresEquipment: 'Pared o colchoneta', difficulty: 'principiante', animationType: 'pushup_incline', levelNumeric: 1, exerciseDbId: 'jV65tKx' },
  { id: 'ex_begin_single_calf_raise', name: 'Elevación de Talón a Una Pierna Asistida', category: 'peso_corporal', targetMuscle: 'Pantorrillas', suggestedSets: 2, suggestedRepsOrSeconds: '8 reps por lado', restSeconds: 30, description: 'Con una mano en la pared, eleva el talón de una pierna y baja lento.', tips: ['Usa apoyo continuo'], requiresEquipment: 'Pared', difficulty: 'principiante', animationType: 'squat_goblet', levelNumeric: 1, exerciseDbId: '0jp9Rlz' },
  { id: 'ex_begin_potty_squat', name: 'Sentadilla Profunda Asistida', category: 'peso_corporal', targetMuscle: 'Core y Caderas', suggestedSets: 2, suggestedRepsOrSeconds: '20 segundos', restSeconds: 30, description: 'Sostén una sentadilla profunda cómoda sujetándote a un apoyo estable.', tips: ['No fuerces el rango'], requiresEquipment: 'Apoyo estable', difficulty: 'principiante', animationType: 'squat_goblet', levelNumeric: 1, exerciseDbId: '75Bgtjy' },
  { id: 'ex_begin_reverse_curl', name: 'Curl Inverso con Mancuernas', category: 'mancuernas', targetMuscle: 'Bíceps', suggestedSets: 2, suggestedRepsOrSeconds: '8 - 10 reps', restSeconds: 45, description: 'Con palmas hacia abajo, flexiona los codos sin balancear el torso.', tips: ['Muñecas neutras'], requiresEquipment: '2 mancuernas ligeras', difficulty: 'principiante', animationType: 'curl_biceps', levelNumeric: 1, exerciseDbId: '0IgNjSM', media: VERIFIED_LOCAL_MEDIA },
  { id: 'ex_int_bent_row', name: 'Remo Inclinado con Dos Mancuernas', category: 'mancuernas', targetMuscle: 'Espalda Alta y Bíceps', suggestedSets: 3, suggestedRepsOrSeconds: '10 reps', restSeconds: 45, description: 'Inclina el torso con espalda neutra y jala ambas mancuernas hacia las costillas.', tips: ['No redondees la espalda'], requiresEquipment: '2 mancuernas', difficulty: 'intermedio', animationType: 'row_dumbbell', levelNumeric: 2, exerciseDbId: 'BJ0Hz5L' },
  { id: 'ex_int_overhead_press', name: 'Press de Pie con Mancuernas', category: 'mancuernas', targetMuscle: 'Hombros y Tríceps', suggestedSets: 3, suggestedRepsOrSeconds: '10 reps', restSeconds: 60, description: 'Presiona las mancuernas sobre la cabeza desde los hombros y baja controlado.', tips: ['Aprieta abdomen y glúteos'], requiresEquipment: '2 mancuernas', difficulty: 'intermedio', animationType: 'shoulder_press', levelNumeric: 2, exerciseDbId: 'A6wtbuL' },
  { id: 'ex_int_reverse_fly', name: 'Apertura Inversa con Mancuernas', category: 'mancuernas', targetMuscle: 'Hombros Posteriores', suggestedSets: 3, suggestedRepsOrSeconds: '12 reps', restSeconds: 45, description: 'Con torso inclinado, abre brazos a los lados y vuelve lento.', tips: ['Carga ligera'], requiresEquipment: '2 mancuernas ligeras', difficulty: 'intermedio', animationType: 'row_dumbbell', levelNumeric: 2, exerciseDbId: 'EAs3xL9' },
  { id: 'ex_int_single_arm_press', name: 'Press a Una Mano con Mancuerna', category: 'mancuernas', targetMuscle: 'Hombros y Core', suggestedSets: 3, suggestedRepsOrSeconds: '8 reps por lado', restSeconds: 60, description: 'Presiona una mancuerna por encima de la cabeza manteniendo el torso estable.', tips: ['No te inclines al lado'], requiresEquipment: '1 mancuerna', difficulty: 'intermedio', animationType: 'shoulder_press', levelNumeric: 2, exerciseDbId: '1TkiAFK' },
  { id: 'ex_int_hammer_single', name: 'Curl Martillo a Una Mano', category: 'mancuernas', targetMuscle: 'Bíceps y Antebrazos', suggestedSets: 3, suggestedRepsOrSeconds: '10 reps por lado', restSeconds: 45, description: 'Con palma hacia dentro, realiza el curl de un brazo manteniendo el codo pegado.', tips: ['Baja en tres segundos'], requiresEquipment: '1 mancuerna', difficulty: 'intermedio', animationType: 'curl_biceps', levelNumeric: 2, exerciseDbId: '2sQGZ5b' },
  { id: 'ex_adv_stiff_deadlift_v2', name: 'Peso Muerto Semirrígido con Tempo', category: 'mancuernas', targetMuscle: 'Glúteos e Isquiotibiales', suggestedSets: 4, suggestedRepsOrSeconds: '10 reps', restSeconds: 60, description: 'Baja tres segundos con cadera atrás, pausa abajo y vuelve apretando glúteos.', tips: ['Espalda neutra siempre'], requiresEquipment: '2 mancuernas', difficulty: 'avanzado', animationType: 'deadlift_rdl', levelNumeric: 3, exerciseDbId: '5eLRITT' },
  { id: 'ex_adv_upright_row_single', name: 'Remo Vertical Unilateral', category: 'mancuernas', targetMuscle: 'Hombros y Trapecio', suggestedSets: 3, suggestedRepsOrSeconds: '10 reps por lado', restSeconds: 45, description: 'Lleva una mancuerna junto al torso hasta el pecho manteniendo hombro cómodo.', tips: ['No subas el codo más que el hombro'], requiresEquipment: '1 mancuerna', difficulty: 'avanzado', animationType: 'row_dumbbell', levelNumeric: 3, exerciseDbId: '6cKQC5E' },
  { id: 'ex_adv_rear_fly_tempo', name: 'Apertura Posterior con Tempo', category: 'mancuernas', targetMuscle: 'Hombros Posteriores y Espalda Alta', suggestedSets: 4, suggestedRepsOrSeconds: '10 reps', restSeconds: 60, description: 'Abre brazos desde torso inclinado y controla tres segundos al regresar.', tips: ['Carga ligera, técnica estricta'], requiresEquipment: '2 mancuernas', difficulty: 'avanzado', animationType: 'row_dumbbell', levelNumeric: 3, exerciseDbId: '8DiFDVA' },
  { id: 'ex_adv_bent_row_tempo', name: 'Remo Inclinado con Pausa', category: 'mancuernas', targetMuscle: 'Espalda Alta y Bíceps', suggestedSets: 4, suggestedRepsOrSeconds: '10 reps', restSeconds: 60, description: 'Jala ambas mancuernas, pausa un segundo al juntar omóplatos y baja lento.', tips: ['Mantén columna neutra'], requiresEquipment: '2 mancuernas', difficulty: 'avanzado', animationType: 'row_dumbbell', levelNumeric: 3, exerciseDbId: 'BJ0Hz5L' },
  { id: 'ex_adv_single_arm_hammer', name: 'Curl Martillo Unilateral con Pausa', category: 'mancuernas', targetMuscle: 'Bíceps y Antebrazos', suggestedSets: 4, suggestedRepsOrSeconds: '10 reps por lado', restSeconds: 45, description: 'Haz curl martillo a una mano con pausa arriba y descenso de tres segundos.', tips: ['Torso inmóvil'], requiresEquipment: '1 mancuerna', difficulty: 'avanzado', animationType: 'curl_biceps', levelNumeric: 3, exerciseDbId: '2sQGZ5b' },
  { id: 'ex_adv_single_arm_press_v2', name: 'Press Unilateral Estable', category: 'mancuernas', targetMuscle: 'Hombros, Tríceps y Core', suggestedSets: 4, suggestedRepsOrSeconds: '8 reps por lado', restSeconds: 60, description: 'Presiona una mancuerna de pie sin inclinar el torso; pausa arriba antes de bajar.', tips: ['Activa abdomen'], requiresEquipment: '1 mancuerna', difficulty: 'avanzado', animationType: 'shoulder_press', levelNumeric: 3, exerciseDbId: '1TkiAFK' },
  // FASE 3 — cobertura de bandas, ligas, cardio funcional y core.
  { id: 'ex_begin_wall_march', name: 'Marcha Sentada en Pared', category: 'peso_corporal', targetMuscle: 'Glúteos y Piernas', suggestedSets: 2, suggestedRepsOrSeconds: '20 segundos', restSeconds: 30, description: 'Apoya la espalda en pared, baja a media sentadilla y alterna elevar los pies.', tips: ['Rango cómodo para rodillas'], requiresEquipment: 'Pared', difficulty: 'principiante', animationType: 'step_jack', levelNumeric: 1, exerciseDbId: 'sVQCCeG' },
  { id: 'ex_begin_band_hip_abduction', name: 'Abducción de Cadera Sentada con Liga', category: 'ligas', targetMuscle: 'Abductores y Glúteos', suggestedSets: 2, suggestedRepsOrSeconds: '12 reps', restSeconds: 30, description: 'Sentado, abre rodillas contra una liga ligera y vuelve con control.', tips: ['Espalda recta'], requiresEquipment: 'Liga de resistencia y silla', difficulty: 'principiante', animationType: 'monster_walk', levelNumeric: 1, exerciseDbId: 'Qj0HRAZ' },
  { id: 'ex_begin_band_leg_extension', name: 'Extensión de Pierna con Liga', category: 'ligas', targetMuscle: 'Cuádriceps', suggestedSets: 2, suggestedRepsOrSeconds: '10 reps por lado', restSeconds: 30, description: 'Con liga anclada de forma segura al tobillo, extiende la pierna de manera controlada.', tips: ['Anclaje firme', 'Sin dolor de rodilla'], requiresEquipment: 'Liga y anclaje seguro', difficulty: 'principiante', animationType: 'step_jack', levelNumeric: 1, exerciseDbId: 'Y1MsI1l' },
  { id: 'ex_begin_kneeling_plank_tap', name: 'Plancha de Rodillas con Toque de Hombro', category: 'peso_corporal', targetMuscle: 'Core y Hombros', suggestedSets: 2, suggestedRepsOrSeconds: '8 toques por lado', restSeconds: 30, description: 'Desde plancha de rodillas, toca el hombro contrario sin rotar caderas.', tips: ['Core activo'], requiresEquipment: 'Colchoneta', difficulty: 'principiante', animationType: 'mountain_climber', levelNumeric: 1, exerciseDbId: 'h1ezqSu' },
  { id: 'ex_begin_band_hip_lift', name: 'Elevación de Cadera con Banda', category: 'bandas_pierna', targetMuscle: 'Glúteos', suggestedSets: 2, suggestedRepsOrSeconds: '10 reps', restSeconds: 45, description: 'Eleva la cadera desde el suelo manteniendo tensión constante en la banda.', tips: ['No arquees zona lumbar'], requiresEquipment: 'Banda elástica y colchoneta', difficulty: 'principiante', animationType: 'bridge_glute', levelNumeric: 1, exerciseDbId: 'E4R8Hz1' },
  { id: 'ex_begin_band_calf_raise', name: 'Elevación de Talones con Banda', category: 'bandas_pierna', targetMuscle: 'Pantorrillas', suggestedSets: 2, suggestedRepsOrSeconds: '12 reps', restSeconds: 30, description: 'Con banda bajo los pies, eleva talones y baja lento manteniendo equilibrio.', tips: ['Sujétate si es necesario'], requiresEquipment: 'Banda elástica', difficulty: 'principiante', animationType: 'squat_goblet', levelNumeric: 1, exerciseDbId: 'jl6uxZV' },
  { id: 'ex_int_band_low_row', name: 'Remo Bajo Unilateral con Banda', category: 'bandas_pierna', targetMuscle: 'Espalda Alta y Bíceps', suggestedSets: 3, suggestedRepsOrSeconds: '10 reps por lado', restSeconds: 45, description: 'Tira de la banda desde un anclaje bajo hacia la cadera y aprieta omóplato.', tips: ['Pecho erguido'], requiresEquipment: 'Banda y anclaje bajo seguro', difficulty: 'intermedio', animationType: 'row_band', levelNumeric: 2, exerciseDbId: 'km0sQC0' },
  { id: 'ex_int_band_rear_row', name: 'Remo Posterior con Banda', category: 'bandas_pierna', targetMuscle: 'Hombros Posteriores', suggestedSets: 3, suggestedRepsOrSeconds: '12 reps', restSeconds: 45, description: 'Tira de la banda hacia la cara con codos abiertos y controlados.', tips: ['No eleves hombros'], requiresEquipment: 'Banda y anclaje seguro', difficulty: 'intermedio', animationType: 'row_band', levelNumeric: 2, exerciseDbId: 'tc5dYrf' },
  { id: 'ex_int_band_squat_row', name: 'Sentadilla con Remo de Banda', category: 'bandas_pierna', targetMuscle: 'Glúteos y Espalda', suggestedSets: 3, suggestedRepsOrSeconds: '10 reps', restSeconds: 60, description: 'Combina una sentadilla controlada con un remo al ponerte de pie.', tips: ['Domina ambos movimientos antes'], requiresEquipment: 'Banda elástica', difficulty: 'intermedio', animationType: 'monster_walk', levelNumeric: 2, exerciseDbId: 'w1NOByi' },
  { id: 'ex_int_front_plank_twist', name: 'Plancha Frontal con Giro', category: 'peso_corporal', targetMuscle: 'Core y Oblicuos', suggestedSets: 3, suggestedRepsOrSeconds: '20 segundos', restSeconds: 45, description: 'Desde plancha frontal, rota el torso de forma controlada sin perder alineación.', tips: ['Cadera estable'], requiresEquipment: 'Colchoneta', difficulty: 'intermedio', animationType: 'mountain_climber', levelNumeric: 2, exerciseDbId: 'CosupLu' },
  { id: 'ex_int_side_plank_adduction', name: 'Plancha Lateral con Aducción', category: 'peso_corporal', targetMuscle: 'Aductores y Core', suggestedSets: 3, suggestedRepsOrSeconds: '8 reps por lado', restSeconds: 45, description: 'En plancha lateral, eleva la pierna inferior con control.', tips: ['Apoya rodilla si es necesario'], requiresEquipment: 'Colchoneta', difficulty: 'intermedio', animationType: 'mountain_climber', levelNumeric: 2, exerciseDbId: 'VO2qeJg' },
  { id: 'ex_int_band_pallof', name: 'Press Pallof con Banda', category: 'bandas_pierna', targetMuscle: 'Core y Oblicuos', suggestedSets: 3, suggestedRepsOrSeconds: '10 reps por lado', restSeconds: 45, description: 'Aleja la banda del pecho resistiendo la rotación del torso.', tips: ['Caderas mirando al frente'], requiresEquipment: 'Banda y anclaje lateral seguro', difficulty: 'intermedio', animationType: 'row_band', levelNumeric: 2, exerciseDbId: '9pa4H5m' },
  { id: 'ex_adv_band_lateral_row', name: 'Remo Bajo Lateral con Banda', category: 'bandas_pierna', targetMuscle: 'Espalda Alta y Core', suggestedSets: 4, suggestedRepsOrSeconds: '10 reps por lado', restSeconds: 60, description: 'Realiza remo unilateral con una ligera variante lateral manteniendo el torso estable.', tips: ['No gires el tronco'], requiresEquipment: 'Banda y anclaje seguro', difficulty: 'avanzado', animationType: 'row_band', levelNumeric: 3, exerciseDbId: 'pgIdT6i' },
  { id: 'ex_adv_band_pulldown', name: 'Jalón Bajo Mano con Banda', category: 'bandas_pierna', targetMuscle: 'Dorsales y Bíceps', suggestedSets: 4, suggestedRepsOrSeconds: '10 reps', restSeconds: 60, description: 'Desde rodillas, tira de la banda anclada arriba hacia el pecho con control.', tips: ['Anclaje de puerta certificado'], requiresEquipment: 'Banda y anclaje alto seguro', difficulty: 'avanzado', animationType: 'row_band', levelNumeric: 3, exerciseDbId: '0I5fUyn' },
  { id: 'ex_adv_band_twist_crunch', name: 'Crunch con Giro y Banda', category: 'bandas_pierna', targetMuscle: 'Oblicuos', suggestedSets: 3, suggestedRepsOrSeconds: '12 reps por lado', restSeconds: 45, description: 'En rodillas, gira el torso contra la banda manteniendo caderas estables.', tips: ['Giro desde costillas, no lumbar'], requiresEquipment: 'Banda y anclaje lateral seguro', difficulty: 'avanzado', animationType: 'row_band', levelNumeric: 3, exerciseDbId: '225x2Vd' },
  { id: 'ex_adv_band_vup', name: 'V-Up con Banda', category: 'bandas_pierna', targetMuscle: 'Abdomen', suggestedSets: 3, suggestedRepsOrSeconds: '10 reps', restSeconds: 60, description: 'Eleva piernas y torso contra la resistencia de la banda de forma controlada.', tips: ['Evita si hay dolor lumbar'], requiresEquipment: 'Banda elástica y colchoneta', difficulty: 'avanzado', animationType: 'band_vup', levelNumeric: 3, exerciseDbId: 'H6ETwO9' },
  { id: 'ex_adv_band_split_squat', name: 'Sentadilla Dividida con Banda', category: 'bandas_pierna', targetMuscle: 'Cuádriceps y Glúteos', suggestedSets: 4, suggestedRepsOrSeconds: '8 reps por lado', restSeconds: 60, description: 'Realiza sentadilla dividida unilateral contra banda, manteniendo equilibrio.', tips: ['Empieza con banda ligera'], requiresEquipment: 'Banda elástica', difficulty: 'avanzado', animationType: 'squat_goblet', levelNumeric: 3, exerciseDbId: 'arsYEd3' },
  { id: 'ex_adv_band_deadlift', name: 'Peso Muerto Semirrígido con Banda', category: 'bandas_pierna', targetMuscle: 'Glúteos e Isquiotibiales', suggestedSets: 4, suggestedRepsOrSeconds: '10 reps', restSeconds: 60, description: 'Pisa la banda y lleva cadera atrás manteniendo columna neutra; vuelve con glúteos.', tips: ['Controla el regreso'], requiresEquipment: 'Banda elástica', difficulty: 'avanzado', animationType: 'deadlift_rdl', levelNumeric: 3, exerciseDbId: 'kuMiR2T' },
  // Variantes de equipo para ampliar la rotación por grupo muscular.
  { id: 'ex_int_band_chest_press', name: 'Press de Pecho Sentado con Liga', category: 'ligas', targetMuscle: 'Pectoral, Hombros y Tríceps', suggestedSets: 3, suggestedRepsOrSeconds: '10 - 12 reps', restSeconds: 45, description: 'Sentado en silla estable, empuja las asas de la liga al frente desde el pecho.', tips: ['Mantén espalda apoyada', 'No bloquees los codos'], requiresEquipment: 'Liga de resistencia y silla estable', difficulty: 'intermedio', animationType: 'band_chest_press', levelNumeric: 2, exerciseDbId: '4x5Okof' },
  { id: 'ex_begin_dumbbell_shrug', name: 'Encogimiento de Trapecio con Mancuernas', category: 'mancuernas', targetMuscle: 'Trapecio', suggestedSets: 2, suggestedRepsOrSeconds: '10 reps', restSeconds: 45, description: 'Con mancuernas a los lados, eleva los hombros hacia las orejas y baja lento.', tips: ['No ruedes los hombros', 'Cuello largo y relajado'], requiresEquipment: '2 mancuernas ligeras', difficulty: 'principiante', animationType: 'dumbbell_shrug', levelNumeric: 1, exerciseDbId: 'NJzBsGJ', media: VERIFIED_LOCAL_MEDIA },
  { id: 'ex_adv_band_vup_rotation', name: 'V-Up Alterno con Banda', category: 'bandas_pierna', targetMuscle: 'Abdomen y Oblicuos', suggestedSets: 3, suggestedRepsOrSeconds: '10 reps por lado', restSeconds: 45, description: 'Desde el suelo, eleva torso y una pierna alternando lados con control.', tips: ['No fuerces la zona lumbar', 'Reduce el rango si pierdes control'], requiresEquipment: 'Banda elástica y colchoneta', difficulty: 'avanzado', animationType: 'band_vup', levelNumeric: 3, exerciseDbId: 'ztAa1RK' },
  // Lote MEDIA-003: GIF oficial descargado y empacado localmente; sin máquinas.
  { id: 'ex_begin_db_biceps_curl', name: 'Curl de Bíceps de Pie', category: 'mancuernas', targetMuscle: 'Bíceps', suggestedSets: 2, suggestedRepsOrSeconds: '8 - 10 reps', restSeconds: 45, description: 'De pie, flexiona los codos con mancuernas ligeras sin balancear el torso.', tips: ['Codos junto al cuerpo', 'Baja lento'], requiresEquipment: '2 mancuernas ligeras', difficulty: 'principiante', animationType: 'curl_biceps', levelNumeric: 1, exerciseDbId: '3s4NnTh', media: VERIFIED_LOCAL_MEDIA },
  { id: 'ex_begin_one_arm_triceps_extension', name: 'Extensión de Tríceps a una Mano', category: 'mancuernas', targetMuscle: 'Tríceps', suggestedSets: 2, suggestedRepsOrSeconds: '8 - 10 reps por lado', restSeconds: 45, description: 'Con una mancuerna ligera, extiende el codo de forma controlada y cambia de lado.', tips: ['No arquees la espalda', 'Mantén el hombro estable'], requiresEquipment: '1 mancuerna ligera', difficulty: 'principiante', animationType: 'curl_biceps', levelNumeric: 1, exerciseDbId: 'BCUR88E', media: VERIFIED_LOCAL_MEDIA },
  { id: 'ex_begin_standing_triceps_extension', name: 'Extensión de Tríceps de Pie', category: 'mancuernas', targetMuscle: 'Tríceps', suggestedSets: 2, suggestedRepsOrSeconds: '8 - 10 reps', restSeconds: 45, description: 'Sostén una mancuerna ligera y extiende los codos con un rango cómodo.', tips: ['Activa abdomen', 'Detente ante dolor de hombro'], requiresEquipment: '1 mancuerna ligera', difficulty: 'principiante', animationType: 'curl_biceps', levelNumeric: 1, exerciseDbId: 'PdmaD0N', media: VERIFIED_LOCAL_MEDIA },
  { id: 'ex_begin_kneeling_triceps_extension', name: 'Extensión de Tríceps de Rodillas', category: 'peso_corporal', targetMuscle: 'Tríceps', suggestedSets: 2, suggestedRepsOrSeconds: '8 reps', restSeconds: 45, description: 'Desde rodillas, flexiona y extiende los codos con control; usa una pared si necesitas regresión.', tips: ['Cuello neutro', 'No bloquees los codos'], requiresEquipment: 'Colchoneta o pared para regresión', difficulty: 'principiante', animationType: 'pushup_incline', levelNumeric: 1, exerciseDbId: 's0HKO2I', media: VERIFIED_LOCAL_MEDIA },
  { id: 'ex_adv_zottman_curl', name: 'Curl Zottman con Mancuernas', category: 'mancuernas', targetMuscle: 'Bíceps', suggestedSets: 3, suggestedRepsOrSeconds: '8 - 10 reps', restSeconds: 45, description: 'Sube con palma hacia arriba y gira las palmas hacia abajo para descender lento.', tips: ['Controla el giro', 'Usa carga moderada'], requiresEquipment: '2 mancuernas', difficulty: 'avanzado', animationType: 'curl_biceps', levelNumeric: 3, exerciseDbId: 'kXaIn5A', media: VERIFIED_LOCAL_MEDIA },
  { id: 'ex_adv_cross_hammer_curl', name: 'Curl Martillo Cruzado', category: 'mancuernas', targetMuscle: 'Bíceps', suggestedSets: 3, suggestedRepsOrSeconds: '10 reps por lado', restSeconds: 45, description: 'Lleva cada mancuerna hacia el hombro contrario sin girar el tronco.', tips: ['Evita impulso', 'Baja en dos segundos'], requiresEquipment: '2 mancuernas', difficulty: 'avanzado', animationType: 'curl_biceps', levelNumeric: 3, exerciseDbId: 'Qyk5J3p', media: VERIFIED_LOCAL_MEDIA },
  { id: 'ex_adv_single_reverse_curl', name: 'Curl Inverso Unilateral', category: 'mancuernas', targetMuscle: 'Bíceps', suggestedSets: 3, suggestedRepsOrSeconds: '10 reps por lado', restSeconds: 45, description: 'Con palma hacia abajo, flexiona un brazo a la vez sin mover el hombro.', tips: ['Muñeca neutra', 'Carga moderada'], requiresEquipment: '1 mancuerna', difficulty: 'avanzado', animationType: 'curl_biceps', levelNumeric: 3, exerciseDbId: 'DU5Kkj2', media: VERIFIED_LOCAL_MEDIA },
  { id: 'ex_adv_standing_triceps_kickback', name: 'Patada de Tríceps de Pie', category: 'mancuernas', targetMuscle: 'Tríceps', suggestedSets: 3, suggestedRepsOrSeconds: '10 reps por lado', restSeconds: 45, description: 'Inclina el torso con espalda neutra y extiende el antebrazo hacia atrás.', tips: ['Apoya una mano en silla si hace falta', 'Codo fijo'], requiresEquipment: '1 mancuerna y silla opcional', difficulty: 'avanzado', animationType: 'curl_biceps', levelNumeric: 3, exerciseDbId: 'UmpPAAe', media: VERIFIED_LOCAL_MEDIA },
  { id: 'ex_adv_alternating_triceps_kickback', name: 'Patada de Tríceps Alternada', category: 'mancuernas', targetMuscle: 'Tríceps', suggestedSets: 3, suggestedRepsOrSeconds: '10 reps por lado', restSeconds: 45, description: 'Alterna la extensión de cada brazo manteniendo la espalda neutra.', tips: ['Cadera estable', 'No subas el codo'], requiresEquipment: '2 mancuernas ligeras', difficulty: 'avanzado', animationType: 'curl_biceps', levelNumeric: 3, exerciseDbId: 'Gi2BXfK', media: VERIFIED_LOCAL_MEDIA },
  { id: 'ex_begin_one_arm_shoulder_press', name: 'Press de Hombro a una Mano', category: 'mancuernas', targetMuscle: 'Hombros', suggestedSets: 2, suggestedRepsOrSeconds: '8 reps por lado', restSeconds: 45, description: 'Sentado con respaldo, empuja una mancuerna ligera sobre la cabeza sin arquear la espalda.', tips: ['Abdomen firme', 'Muñeca neutra'], requiresEquipment: '1 mancuerna ligera y silla estable', difficulty: 'principiante', animationType: 'shoulder_press', levelNumeric: 1, exerciseDbId: '84RyJf8', media: VERIFIED_LOCAL_MEDIA },
  { id: 'ex_begin_rear_delt_fly', name: 'Apertura Posterior con Mancuernas', category: 'mancuernas', targetMuscle: 'Hombros', suggestedSets: 2, suggestedRepsOrSeconds: '8 - 10 reps', restSeconds: 45, description: 'Inclina el torso ligeramente y abre los brazos con carga ligera, sin encoger los hombros.', tips: ['Cuello relajado', 'Rango corto si eres principiante'], requiresEquipment: '2 mancuernas ligeras', difficulty: 'principiante', animationType: 'lateral_raise', levelNumeric: 1, exerciseDbId: 'mu5Guxt', media: VERIFIED_LOCAL_MEDIA },
  { id: 'ex_begin_band_y_raise', name: 'Elevación en Y con Banda', category: 'bandas_pierna', targetMuscle: 'Hombros', suggestedSets: 2, suggestedRepsOrSeconds: '8 - 10 reps', restSeconds: 45, description: 'Eleva los brazos formando una Y con banda ligera y escápulas controladas.', tips: ['No arquees la zona lumbar', 'Reduce rango si molesta'], requiresEquipment: 'Banda elástica ligera', difficulty: 'principiante', animationType: 'lateral_raise', levelNumeric: 1, exerciseDbId: 'aHDy5O5', media: VERIFIED_LOCAL_MEDIA },
  { id: 'ex_int_side_plank', name: 'Plancha Lateral', category: 'peso_corporal', targetMuscle: 'Oblicuos', suggestedSets: 3, suggestedRepsOrSeconds: '20 - 30 segundos por lado', restSeconds: 30, description: 'Apoya antebrazo y pies, formando una línea recta; baja la rodilla inferior para regresión.', tips: ['Cadera alta', 'Respira continuo'], requiresEquipment: 'Colchoneta', difficulty: 'intermedio', animationType: 'band_vup', levelNumeric: 2, exerciseDbId: 'RKjH6Lt', media: VERIFIED_LOCAL_MEDIA },
  { id: 'ex_int_russian_twist', name: 'Giro Ruso Controlado', category: 'peso_corporal', targetMuscle: 'Oblicuos', suggestedSets: 3, suggestedRepsOrSeconds: '10 reps por lado', restSeconds: 30, description: 'Sentado con pies apoyados, gira el torso de lado a lado lentamente.', tips: ['Mantén pecho alto', 'No fuerces la zona lumbar'], requiresEquipment: 'Colchoneta', difficulty: 'intermedio', animationType: 'band_vup', levelNumeric: 2, exerciseDbId: 'XVDdcoj', media: VERIFIED_LOCAL_MEDIA },
  { id: 'ex_int_bear_walk', name: 'Caminata de Oso', category: 'peso_corporal', targetMuscle: 'Core', suggestedSets: 3, suggestedRepsOrSeconds: '20 - 30 segundos', restSeconds: 45, description: 'Avanza con manos y pies manteniendo rodillas cerca del suelo y espalda neutra.', tips: ['Pasos cortos', 'Usa apoyo elevado como regresión'], requiresEquipment: 'Suelo firme', difficulty: 'intermedio', animationType: 'mountain_climber', levelNumeric: 2, exerciseDbId: '0Yz8WdV', media: VERIFIED_LOCAL_MEDIA },
  { id: 'ex_int_concentration_curl', name: 'Curl de Concentración de Pie', category: 'mancuernas', targetMuscle: 'Bíceps', suggestedSets: 3, suggestedRepsOrSeconds: '10 reps por lado', restSeconds: 45, description: 'Flexiona una mancuerna con el codo estable y sin girar el torso.', tips: ['Baja lento', 'Usa una carga moderada'], requiresEquipment: '1 mancuerna', difficulty: 'intermedio', animationType: 'curl_biceps', levelNumeric: 2, exerciseDbId: '7inpWch', media: VERIFIED_LOCAL_MEDIA },
  { id: 'ex_int_one_arm_concentration_curl', name: 'Curl de Concentración a una Mano', category: 'mancuernas', targetMuscle: 'Bíceps', suggestedSets: 3, suggestedRepsOrSeconds: '10 reps por lado', restSeconds: 45, description: 'Realiza el curl de forma deliberada, manteniendo el codo junto al cuerpo.', tips: ['No balancees el cuerpo', 'Exhala al subir'], requiresEquipment: '1 mancuerna', difficulty: 'intermedio', animationType: 'curl_biceps', levelNumeric: 2, exerciseDbId: '8fgqP5a', media: VERIFIED_LOCAL_MEDIA },
  { id: 'ex_int_bent_over_triceps_extension', name: 'Extensión de Tríceps Inclinada a una Mano', category: 'mancuernas', targetMuscle: 'Tríceps', suggestedSets: 3, suggestedRepsOrSeconds: '10 reps por lado', restSeconds: 45, description: 'Inclina el torso con espalda neutra y extiende el antebrazo hacia atrás.', tips: ['Apoya una mano en silla si necesitas estabilidad', 'Codo fijo'], requiresEquipment: '1 mancuerna y silla opcional', difficulty: 'intermedio', animationType: 'curl_biceps', levelNumeric: 2, exerciseDbId: 'CJwa0vD', media: VERIFIED_LOCAL_MEDIA },
  { id: 'ex_begin_full_can_raise', name: 'Elevación Lateral en Plano Escapular', category: 'mancuernas', targetMuscle: 'Hombros', suggestedSets: 2, suggestedRepsOrSeconds: '8 - 10 reps', restSeconds: 45, description: 'Eleva mancuernas ligeras ligeramente al frente, con pulgares apuntando arriba.', tips: ['No pases la altura del hombro', 'Carga muy ligera'], requiresEquipment: '2 mancuernas ligeras', difficulty: 'principiante', animationType: 'lateral_raise', levelNumeric: 1, exerciseDbId: 'AQ0mC4Y', media: VERIFIED_LOCAL_MEDIA },
  { id: 'ex_adv_cross_body_mountain_climber', name: 'Escalador Cruzado', category: 'peso_corporal', targetMuscle: 'Core', suggestedSets: 3, suggestedRepsOrSeconds: '30 - 45 segundos', restSeconds: 30, description: 'Desde plancha alta, lleva cada rodilla hacia el codo contrario manteniendo cadera estable.', tips: ['Reduce velocidad si rota la pelvis', 'Usa manos elevadas como regresión'], requiresEquipment: 'Suelo firme', difficulty: 'avanzado', animationType: 'mountain_climber', levelNumeric: 3, exerciseDbId: '9c6T1YX', media: VERIFIED_LOCAL_MEDIA },
  { id: 'ex_adv_alternate_overhead_press', name: 'Press Alternado de Hombro', category: 'mancuernas', targetMuscle: 'Hombros', suggestedSets: 3, suggestedRepsOrSeconds: '8 - 10 reps por lado', restSeconds: 60, description: 'De pie, presiona una mancuerna arriba mientras la otra permanece controlada a la altura del hombro.', tips: ['No arquees la espalda', 'Regresión: sentado con respaldo y carga ligera'], requiresEquipment: '2 mancuernas', difficulty: 'avanzado', animationType: 'shoulder_press', levelNumeric: 3, exerciseDbId: 'bBi35y3', media: VERIFIED_LOCAL_MEDIA },
  { id: 'ex_adv_alternate_side_press', name: 'Press Lateral Alternado', category: 'mancuernas', targetMuscle: 'Hombros', suggestedSets: 3, suggestedRepsOrSeconds: '8 reps por lado', restSeconds: 60, description: 'Presiona una mancuerna de forma alternada manteniendo el tronco alto y estable.', tips: ['Activa abdomen', 'Regresión: reduce rango y realiza sentado'], requiresEquipment: '2 mancuernas', difficulty: 'avanzado', animationType: 'shoulder_press', levelNumeric: 3, exerciseDbId: 'izMnLqz', media: VERIFIED_LOCAL_MEDIA },
  { id: 'ex_adv_one_arm_lateral_raise', name: 'Elevación Lateral a una Mano', category: 'mancuernas', targetMuscle: 'Hombros', suggestedSets: 3, suggestedRepsOrSeconds: '10 reps por lado', restSeconds: 45, description: 'Eleva una mancuerna hacia el lado hasta la altura del hombro, sin inclinar el torso.', tips: ['Carga moderada', 'Regresión: usa apoyo de pared'], requiresEquipment: '1 mancuerna', difficulty: 'avanzado', animationType: 'lateral_raise', levelNumeric: 3, exerciseDbId: 'n5cWCsI', media: VERIFIED_LOCAL_MEDIA },
  { id: 'ex_adv_rotating_reverse_fly', name: 'Apertura Posterior con Rotación', category: 'mancuernas', targetMuscle: 'Hombros', suggestedSets: 3, suggestedRepsOrSeconds: '10 reps', restSeconds: 45, description: 'Con torso inclinado y espalda neutra, abre los brazos con rotación controlada.', tips: ['Cuello relajado', 'Regresión: apertura posterior sin carga'], requiresEquipment: '2 mancuernas ligeras', difficulty: 'avanzado', animationType: 'lateral_raise', levelNumeric: 3, exerciseDbId: 'prbWx1D', media: VERIFIED_LOCAL_MEDIA },
  { id: 'ex_begin_wall_pushup_v2', name: 'Flexión en Pared Controlada', category: 'peso_corporal', targetMuscle: 'Pectoral', suggestedSets: 2, suggestedRepsOrSeconds: '8 - 10 reps', restSeconds: 45, description: 'Con manos en la pared, acerca el pecho y empuja sin perder la alineación corporal.', tips: ['Codos a 45°', 'Regresión: acércate más a la pared'], requiresEquipment: 'Pared', difficulty: 'principiante', animationType: 'pushup_incline', levelNumeric: 1, exerciseDbId: 'NCmbLCw', media: VERIFIED_LOCAL_MEDIA },
  { id: 'ex_begin_chest_squeeze', name: 'Compresión Isométrica de Pecho', category: 'peso_corporal', targetMuscle: 'Pectoral', suggestedSets: 2, suggestedRepsOrSeconds: '20 - 30 segundos', restSeconds: 30, description: 'Junta las palmas al frente del pecho y presiona con fuerza moderada sin elevar los hombros.', tips: ['Respira continuo', 'Detén ante dolor de hombro'], requiresEquipment: 'Ninguno', difficulty: 'principiante', animationType: 'band_chest_press', levelNumeric: 1, exerciseDbId: 'HbSG1Pw', media: VERIFIED_LOCAL_MEDIA },
  { id: 'ex_int_rotational_bent_row', name: 'Remo Inclinado con Rotación de Palma', category: 'mancuernas', targetMuscle: 'Espalda Alta', suggestedSets: 3, suggestedRepsOrSeconds: '10 reps', restSeconds: 45, description: 'Inclina el torso con espalda neutra y lleva las mancuernas hacia las costillas con giro controlado.', tips: ['No redondees la espalda', 'Regresión: menor carga'], requiresEquipment: '2 mancuernas', difficulty: 'intermedio', animationType: 'row_dumbbell', levelNumeric: 2, exerciseDbId: 'wt6rwjk', media: VERIFIED_LOCAL_MEDIA },
  { id: 'ex_int_standing_bodyweight_row', name: 'Remo de Pie con Peso Corporal', category: 'peso_corporal', targetMuscle: 'Espalda Alta', suggestedSets: 3, suggestedRepsOrSeconds: '10 reps', restSeconds: 45, description: 'Desde una postura estable, realiza el gesto de remo manteniendo pecho alto y escápulas activas.', tips: ['Sin balanceo', 'Regresión: reduce el recorrido'], requiresEquipment: 'Suelo firme', difficulty: 'intermedio', animationType: 'row_band', levelNumeric: 2, exerciseDbId: 'wd4ds3s', media: VERIFIED_LOCAL_MEDIA },
  { id: 'ex_begin_pushup_plus', name: 'Flexión con Activación Escapular', category: 'peso_corporal', targetMuscle: 'Pectoral', suggestedSets: 2, suggestedRepsOrSeconds: '8 reps', restSeconds: 45, description: 'Desde plancha inclinada o de rodillas, empuja el suelo y separa suavemente los omóplatos al final.', tips: ['Cuerpo alineado', 'Regresión: realiza en pared'], requiresEquipment: 'Colchoneta o pared', difficulty: 'principiante', animationType: 'pushup_incline', levelNumeric: 1, exerciseDbId: 'pvBMLHA', media: VERIFIED_LOCAL_MEDIA },
  { id: 'ex_int_wide_pushup', name: 'Flexión con Manos Amplias', category: 'peso_corporal', targetMuscle: 'Pectoral', suggestedSets: 3, suggestedRepsOrSeconds: '8 - 12 reps', restSeconds: 45, description: 'Con manos más abiertas que los hombros, baja el pecho con el cuerpo alineado y empuja al inicio.', tips: ['No hundas la cadera', 'Regresión: rodillas o pared'], requiresEquipment: 'Colchoneta', difficulty: 'intermedio', animationType: 'pushup_incline', levelNumeric: 2, exerciseDbId: 'JmMVpR3', media: VERIFIED_LOCAL_MEDIA },
  { id: 'ex_adv_deep_pushup_db', name: 'Flexión Profunda con Mancuernas', category: 'mancuernas', targetMuscle: 'Pectoral', suggestedSets: 3, suggestedRepsOrSeconds: '8 - 10 reps', restSeconds: 60, description: 'Usa mancuernas estables como agarres para bajar con mayor rango y empuja de forma controlada.', tips: ['Mancuernas firmes', 'Regresión: flexión normal'], requiresEquipment: '2 mancuernas estables', difficulty: 'avanzado', animationType: 'pushup_incline', levelNumeric: 3, exerciseDbId: 'vptOQ4N', media: VERIFIED_LOCAL_MEDIA },
  { id: 'ex_adv_chest_tap_pushup', name: 'Flexión con Toque de Pecho', category: 'peso_corporal', targetMuscle: 'Pectoral', suggestedSets: 3, suggestedRepsOrSeconds: '8 reps por lado', restSeconds: 60, description: 'Durante la flexión controla el peso corporal y alterna el toque sin perder alineación.', tips: ['Cadera estable', 'Regresión: flexión normal'], requiresEquipment: 'Colchoneta', difficulty: 'avanzado', animationType: 'pushup_incline', levelNumeric: 3, exerciseDbId: '7E06s6d', media: VERIFIED_LOCAL_MEDIA },
  { id: 'ex_adv_clock_pushup', name: 'Flexión Reloj', category: 'peso_corporal', targetMuscle: 'Pectoral', suggestedSets: 3, suggestedRepsOrSeconds: '6 - 8 reps por lado', restSeconds: 60, description: 'Realiza una flexión y rota de forma controlada hacia cada dirección, sin perder control del core.', tips: ['No fuerces hombros', 'Regresión: flexión fija'], requiresEquipment: 'Colchoneta', difficulty: 'avanzado', animationType: 'pushup_incline', levelNumeric: 3, exerciseDbId: 'CMAxnsG', media: VERIFIED_LOCAL_MEDIA },
  { id: 'ex_adv_shoulder_tap_pushup', name: 'Flexión con Toque de Hombro', category: 'peso_corporal', targetMuscle: 'Pectoral', suggestedSets: 3, suggestedRepsOrSeconds: '8 reps por lado', restSeconds: 60, description: 'Completa una flexión y toca el hombro contrario sin rotar el tronco.', tips: ['Apoya rodillas como regresión', 'Movimiento lento'], requiresEquipment: 'Colchoneta', difficulty: 'avanzado', animationType: 'pushup_incline', levelNumeric: 3, exerciseDbId: 'qEse6fe', media: VERIFIED_LOCAL_MEDIA },
];

/** Devuelve el catálogo filtrado por nivel, sin mezclar niveles incompatibles */
export function getExercisesByLevel(level: 1 | 2 | 3): ExtendedExerciseItem[] {
  return EXERCISES_CATALOG.filter((e) => e.levelNumeric === level);
}

/** Devuelve ejercicios para el generador de planes según tiempo y nivel */
export function selectExercisesForPlan(
  preferredMinutes: 20 | 30 | 60,
  levelNumeric: 1 | 2 | 3
): ExtendedExerciseItem[] {
  const pool = getExercisesByLevel(levelNumeric);
  const count = preferredMinutes === 20 ? 4 : preferredMinutes === 30 ? 5 : 8;

  // Asegurar variedad de categorías
  const categories = ['cardio', 'peso_corporal', 'mancuernas', 'ligas', 'bandas_pierna'] as const;
  const selected: ExtendedExerciseItem[] = [];

  // Primero incluir cardio como calentamiento si está disponible
  const cardio = pool.find((e) => e.category === 'cardio');
  if (cardio) selected.push(cardio);

  // Luego rellenar con variedad
  for (const cat of categories) {
    if (selected.length >= count) break;
    const fromCat = pool.find((e) => e.category === cat && !selected.includes(e));
    if (fromCat) selected.push(fromCat);
  }

  // Completar si faltan
  while (selected.length < count) {
    const remaining = pool.filter((e) => !selected.includes(e));
    if (remaining.length === 0) break;
    selected.push(remaining[0]);
  }

  return selected.slice(0, count);
}

// Re-export recipes from old catalogs (unchanged)
export { RECIPES_CATALOG } from './catalogs';
